-- Agrega cancelaciones y devoluciones como eventos transaccionales auditables.

ALTER TABLE ventas
  ALTER COLUMN estado TYPE VARCHAR(30);

ALTER TABLE ventas DROP CONSTRAINT IF EXISTS ventas_estado_check;
ALTER TABLE ventas
  ADD CONSTRAINT ventas_estado_check CHECK (
    estado IN (
      'COMPLETADA',
      'CANCELADA',
      'PARCIALMENTE_DEVUELTA',
      'DEVUELTA'
    )
  );

CREATE TABLE IF NOT EXISTS cancelaciones_venta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id INTEGER NOT NULL UNIQUE REFERENCES ventas(id) ON DELETE RESTRICT,
  sesion_id INTEGER NOT NULL,
  caja_id INTEGER NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(240) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT cancelaciones_venta_sesion_caja_fk
    FOREIGN KEY (sesion_id, caja_id)
    REFERENCES sesiones_caja(id, caja_id)
    ON DELETE RESTRICT,
  CONSTRAINT cancelaciones_venta_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT cancelaciones_venta_total_check CHECK (total >= 0)
);

CREATE INDEX IF NOT EXISTS cancelaciones_venta_sesion_idx
  ON cancelaciones_venta (sesion_id);
CREATE INDEX IF NOT EXISTS cancelaciones_venta_usuario_idx
  ON cancelaciones_venta (usuario_id);

CREATE TABLE IF NOT EXISTS devoluciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id INTEGER NOT NULL REFERENCES ventas(id) ON DELETE RESTRICT,
  sesion_id INTEGER NOT NULL,
  caja_id INTEGER NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(240) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT devoluciones_sesion_caja_fk
    FOREIGN KEY (sesion_id, caja_id)
    REFERENCES sesiones_caja(id, caja_id)
    ON DELETE RESTRICT,
  CONSTRAINT devoluciones_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT devoluciones_total_check CHECK (total >= 0)
);

CREATE INDEX IF NOT EXISTS devoluciones_venta_idx ON devoluciones (venta_id);
CREATE INDEX IF NOT EXISTS devoluciones_sesion_idx ON devoluciones (sesion_id);
CREATE INDEX IF NOT EXISTS devoluciones_usuario_idx ON devoluciones (usuario_id);

CREATE TABLE IF NOT EXISTS detalle_devoluciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  devolucion_id BIGINT NOT NULL REFERENCES devoluciones(id) ON DELETE RESTRICT,
  detalle_venta_id INTEGER NOT NULL REFERENCES detalle_ventas(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL,
  importe NUMERIC(12,2) NOT NULL,
  CONSTRAINT detalle_devoluciones_cantidad_check CHECK (cantidad > 0),
  CONSTRAINT detalle_devoluciones_importe_check CHECK (importe >= 0),
  CONSTRAINT detalle_devoluciones_linea_uq UNIQUE (devolucion_id, detalle_venta_id)
);

CREATE INDEX IF NOT EXISTS detalle_devoluciones_detalle_venta_idx
  ON detalle_devoluciones (detalle_venta_id);

ALTER TABLE movimientos
  ADD COLUMN IF NOT EXISTS cancelacion_id BIGINT,
  ADD COLUMN IF NOT EXISTS devolucion_id BIGINT;

DO $migration$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'movimientos'::regclass
      AND conname = 'movimientos_cancelacion_fk'
  ) THEN
    ALTER TABLE movimientos
      ADD CONSTRAINT movimientos_cancelacion_fk
      FOREIGN KEY (cancelacion_id)
      REFERENCES cancelaciones_venta(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'movimientos'::regclass
      AND conname = 'movimientos_devolucion_fk'
  ) THEN
    ALTER TABLE movimientos
      ADD CONSTRAINT movimientos_devolucion_fk
      FOREIGN KEY (devolucion_id)
      REFERENCES devoluciones(id)
      ON DELETE RESTRICT;
  END IF;
END
$migration$;

ALTER TABLE movimientos DROP CONSTRAINT IF EXISTS movimientos_tipo_check;
ALTER TABLE movimientos
  ADD CONSTRAINT movimientos_tipo_check
  CHECK (tipo IN (
    'APERTURA', 'VENTA', 'RETIRO', 'INGRESO', 'CIERRE',
    'CANCELACION', 'DEVOLUCION'
  ));

ALTER TABLE movimientos DROP CONSTRAINT IF EXISTS movimientos_origen_check;
ALTER TABLE movimientos
  ADD CONSTRAINT movimientos_origen_check CHECK (
    (
      tipo = 'VENTA'
      AND venta_id IS NOT NULL
      AND cancelacion_id IS NULL
      AND devolucion_id IS NULL
    )
    OR
    (
      tipo = 'CANCELACION'
      AND venta_id IS NULL
      AND cancelacion_id IS NOT NULL
      AND devolucion_id IS NULL
    )
    OR
    (
      tipo = 'DEVOLUCION'
      AND venta_id IS NULL
      AND cancelacion_id IS NULL
      AND devolucion_id IS NOT NULL
    )
    OR
    (
      tipo IN ('APERTURA', 'RETIRO', 'INGRESO', 'CIERRE')
      AND venta_id IS NULL
      AND cancelacion_id IS NULL
      AND devolucion_id IS NULL
    )
  );

CREATE UNIQUE INDEX IF NOT EXISTS movimientos_cancelacion_uq
  ON movimientos (cancelacion_id) WHERE tipo = 'CANCELACION';
CREATE UNIQUE INDEX IF NOT EXISTS movimientos_devolucion_uq
  ON movimientos (devolucion_id) WHERE tipo = 'DEVOLUCION';

ALTER TABLE cortes
  ADD COLUMN IF NOT EXISTS devoluciones_efectivo NUMERIC(12,2);

UPDATE cortes
SET devoluciones_efectivo = 0
WHERE devoluciones_efectivo IS NULL;

ALTER TABLE cortes
  ALTER COLUMN devoluciones_efectivo SET DEFAULT 0,
  ALTER COLUMN devoluciones_efectivo SET NOT NULL;

ALTER TABLE cortes DROP CONSTRAINT IF EXISTS cortes_devoluciones_efectivo_check;
ALTER TABLE cortes
  ADD CONSTRAINT cortes_devoluciones_efectivo_check
  CHECK (devoluciones_efectivo >= 0);
