-- Núcleo de inventario: saldo físico, saldo reservado y kardex inmutable.
-- El backfill establece un punto de partida honesto desde productos.stock;
-- no intenta reconstruir historial desde movimientos de caja (incluido CIERRE).

ALTER TABLE productos
  ADD COLUMN IF NOT EXISTS stock_reservado INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stock_disponible INTEGER
    GENERATED ALWAYS AS (stock - stock_reservado) STORED;

DO $migration$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'productos'::regclass
      AND conname = 'productos_stock_reservado_check'
  ) THEN
    ALTER TABLE productos
      ADD CONSTRAINT productos_stock_reservado_check
      CHECK (stock_reservado >= 0 AND stock_reservado <= stock);
  END IF;
END
$migration$;

CREATE TABLE IF NOT EXISTS inventario_movimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  tipo VARCHAR(30) NOT NULL,
  delta_fisico INTEGER NOT NULL DEFAULT 0,
  delta_reservado INTEGER NOT NULL DEFAULT 0,
  stock_fisico_resultante INTEGER NOT NULL,
  stock_reservado_resultante INTEGER NOT NULL,
  actor VARCHAR(12) NOT NULL,
  usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(240),
  venta_id INTEGER REFERENCES ventas(id) ON DELETE RESTRICT,
  cancelacion_id BIGINT REFERENCES cancelaciones_venta(id) ON DELETE RESTRICT,
  devolucion_id BIGINT REFERENCES devoluciones(id) ON DELETE RESTRICT,
  origen_clave VARCHAR(160) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT inventario_movimientos_tipo_check CHECK (
    tipo IN ('INICIAL', 'AJUSTE', 'VENTA', 'CANCELACION', 'DEVOLUCION')
  ),
  CONSTRAINT inventario_movimientos_delta_check CHECK (
    tipo = 'INICIAL' OR delta_fisico <> 0 OR delta_reservado <> 0
  ),
  CONSTRAINT inventario_movimientos_saldos_check CHECK (
    stock_fisico_resultante >= 0
    AND stock_reservado_resultante >= 0
    AND stock_reservado_resultante <= stock_fisico_resultante
  ),
  CONSTRAINT inventario_movimientos_actor_check CHECK (
    actor IN ('USUARIO', 'SISTEMA', 'MIGRACION')
    AND ((actor = 'USUARIO' AND usuario_id IS NOT NULL) OR actor <> 'USUARIO')
  ),
  CONSTRAINT inventario_movimientos_inicial_check CHECK (
    tipo <> 'INICIAL'
    OR (
      actor = 'MIGRACION'
      AND usuario_id IS NULL
      AND delta_fisico >= 0
      AND delta_reservado >= 0
      AND venta_id IS NULL
      AND cancelacion_id IS NULL
      AND devolucion_id IS NULL
    )
  ),
  CONSTRAINT inventario_movimientos_ajuste_check CHECK (
    tipo <> 'AJUSTE'
    OR (
      actor = 'USUARIO'
      AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
      AND delta_fisico <> 0
      AND delta_reservado = 0
      AND venta_id IS NULL
      AND cancelacion_id IS NULL
      AND devolucion_id IS NULL
    )
  ),
  CONSTRAINT inventario_movimientos_origen_pos_check CHECK (
    (
      tipo = 'VENTA'
      AND venta_id IS NOT NULL
      AND cancelacion_id IS NULL
      AND devolucion_id IS NULL
      AND delta_fisico < 0
      AND delta_reservado = 0
    )
    OR
    (
      tipo = 'CANCELACION'
      AND venta_id IS NULL
      AND cancelacion_id IS NOT NULL
      AND devolucion_id IS NULL
      AND delta_fisico > 0
      AND delta_reservado = 0
    )
    OR
    (
      tipo = 'DEVOLUCION'
      AND venta_id IS NULL
      AND cancelacion_id IS NULL
      AND devolucion_id IS NOT NULL
      AND delta_fisico > 0
      AND delta_reservado = 0
    )
    OR tipo IN ('INICIAL', 'AJUSTE')
  )
);

CREATE INDEX IF NOT EXISTS inventario_movimientos_producto_fecha_idx
  ON inventario_movimientos (producto_id, creado_en DESC, id DESC);
CREATE INDEX IF NOT EXISTS inventario_movimientos_usuario_fecha_idx
  ON inventario_movimientos (usuario_id, creado_en DESC)
  WHERE usuario_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS inventario_movimientos_venta_producto_uq
  ON inventario_movimientos (venta_id, producto_id)
  WHERE tipo = 'VENTA';
CREATE UNIQUE INDEX IF NOT EXISTS inventario_movimientos_cancelacion_producto_uq
  ON inventario_movimientos (cancelacion_id, producto_id)
  WHERE tipo = 'CANCELACION';
CREATE UNIQUE INDEX IF NOT EXISTS inventario_movimientos_devolucion_producto_uq
  ON inventario_movimientos (devolucion_id, producto_id)
  WHERE tipo = 'DEVOLUCION';

INSERT INTO inventario_movimientos (
  producto_id,
  tipo,
  delta_fisico,
  delta_reservado,
  stock_fisico_resultante,
  stock_reservado_resultante,
  actor,
  usuario_id,
  motivo,
  origen_clave,
  creado_en
)
SELECT
  p.id,
  'INICIAL',
  p.stock,
  p.stock_reservado,
  p.stock,
  p.stock_reservado,
  'MIGRACION',
  NULL,
  'Saldo inicial importado; no representa movimientos históricos.',
  'MIGRACION:003:PRODUCTO:' || p.id::text,
  NOW()
FROM productos p
ON CONFLICT (origen_clave) DO NOTHING;

CREATE OR REPLACE FUNCTION impedir_mutacion_inventario_movimientos()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  RAISE EXCEPTION 'El kardex es inmutable; no se permite % en inventario_movimientos.', TG_OP
    USING ERRCODE = '55000';
END
$function$;

DROP TRIGGER IF EXISTS inventario_movimientos_inmutable_trg
  ON inventario_movimientos;
CREATE TRIGGER inventario_movimientos_inmutable_trg
  BEFORE UPDATE OR DELETE ON inventario_movimientos
  FOR EACH ROW
  EXECUTE FUNCTION impedir_mutacion_inventario_movimientos();
