-- Catálogo comercial y motor de precios compartido por POS y web.

ALTER TABLE categorias
  ADD COLUMN IF NOT EXISTS slug VARCHAR(120),
  ADD COLUMN IF NOT EXISTS descripcion TEXT,
  ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS orden INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW();

UPDATE categorias
SET slug = 'categoria-' || id::text
WHERE slug IS NULL OR btrim(slug) = '';

DO $migration$
BEGIN
  IF EXISTS (
    SELECT lower(nombre)
    FROM categorias
    GROUP BY lower(nombre)
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'Hay categorías duplicadas ignorando mayúsculas; deben resolverse antes de migrar.';
  END IF;
END
$migration$;

CREATE OR REPLACE FUNCTION completar_slug_categoria()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.slug IS NULL OR btrim(NEW.slug) = '' THEN
    NEW.slug := 'categoria-' || NEW.id::text;
  END IF;
  RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS categorias_completar_slug_trg ON categorias;
CREATE TRIGGER categorias_completar_slug_trg
  BEFORE INSERT ON categorias
  FOR EACH ROW
  EXECUTE FUNCTION completar_slug_categoria();

ALTER TABLE categorias
  ALTER COLUMN slug SET NOT NULL;
ALTER TABLE categorias DROP CONSTRAINT IF EXISTS categorias_slug_check;
ALTER TABLE categorias
  ADD CONSTRAINT categorias_slug_check
  CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$');
ALTER TABLE categorias DROP CONSTRAINT IF EXISTS categorias_orden_check;
ALTER TABLE categorias
  ADD CONSTRAINT categorias_orden_check CHECK (orden >= 0);

CREATE UNIQUE INDEX IF NOT EXISTS categorias_slug_uq ON categorias (slug);
CREATE UNIQUE INDEX IF NOT EXISTS categorias_nombre_lower_uq
  ON categorias (lower(nombre));
CREATE INDEX IF NOT EXISTS categorias_catalogo_idx
  ON categorias (orden, nombre) WHERE activo;

CREATE OR REPLACE FUNCTION marcar_actualizado_en()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.actualizado_en := NOW();
  RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS categorias_actualizado_en_trg ON categorias;
CREATE TRIGGER categorias_actualizado_en_trg
  BEFORE UPDATE ON categorias
  FOR EACH ROW
  EXECUTE FUNCTION marcar_actualizado_en();

ALTER TABLE productos
  ADD COLUMN IF NOT EXISTS publicado_web BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS slug VARCHAR(180),
  ADD COLUMN IF NOT EXISTS descripcion_comercial TEXT,
  ADD COLUMN IF NOT EXISTS publicado_en TIMESTAMPTZ;

ALTER TABLE productos DROP CONSTRAINT IF EXISTS productos_slug_check;
ALTER TABLE productos
  ADD CONSTRAINT productos_slug_check
  CHECK (slug IS NULL OR slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$');
ALTER TABLE productos DROP CONSTRAINT IF EXISTS productos_publicacion_check;
ALTER TABLE productos
  ADD CONSTRAINT productos_publicacion_check CHECK (
    NOT publicado_web
    OR (slug IS NOT NULL AND btrim(COALESCE(descripcion_comercial, '')) <> '')
  );
ALTER TABLE productos DROP CONSTRAINT IF EXISTS productos_publicado_en_check;
ALTER TABLE productos
  ADD CONSTRAINT productos_publicado_en_check CHECK (
    (publicado_web AND publicado_en IS NOT NULL)
    OR (NOT publicado_web AND publicado_en IS NULL)
  );

CREATE UNIQUE INDEX IF NOT EXISTS productos_slug_uq
  ON productos (slug) WHERE slug IS NOT NULL;
CREATE INDEX IF NOT EXISTS productos_catalogo_publico_idx
  ON productos (categoria_id, titulo, id) WHERE activo AND publicado_web;

CREATE TABLE IF NOT EXISTS producto_imagenes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  texto_alternativo VARCHAR(180) NOT NULL,
  orden INTEGER NOT NULL DEFAULT 0,
  principal BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT producto_imagenes_url_check CHECK (btrim(url) <> ''),
  CONSTRAINT producto_imagenes_alt_check CHECK (btrim(texto_alternativo) <> ''),
  CONSTRAINT producto_imagenes_orden_check CHECK (orden >= 0),
  CONSTRAINT producto_imagenes_producto_orden_uq UNIQUE (producto_id, orden)
);

CREATE INDEX IF NOT EXISTS producto_imagenes_producto_idx
  ON producto_imagenes (producto_id, orden, id);
CREATE UNIQUE INDEX IF NOT EXISTS producto_imagenes_principal_uq
  ON producto_imagenes (producto_id) WHERE principal;

CREATE OR REPLACE FUNCTION validar_publicacion_producto()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.publicado_web THEN
    IF NEW.slug IS NULL OR btrim(COALESCE(NEW.descripcion_comercial, '')) = '' THEN
      RAISE EXCEPTION 'Un producto publicado requiere slug y descripción comercial.'
        USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
      SELECT 1
      FROM producto_imagenes
      WHERE producto_id = NEW.id AND principal
    ) THEN
      RAISE EXCEPTION 'Un producto publicado requiere una imagen principal.'
        USING ERRCODE = '23514';
    END IF;
    NEW.publicado_en := COALESCE(NEW.publicado_en, NOW());
  ELSE
    NEW.publicado_en := NULL;
  END IF;
  RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS productos_validar_publicacion_trg ON productos;
CREATE TRIGGER productos_validar_publicacion_trg
  BEFORE INSERT OR UPDATE OF publicado_web, slug, descripcion_comercial ON productos
  FOR EACH ROW
  EXECUTE FUNCTION validar_publicacion_producto();

CREATE OR REPLACE FUNCTION proteger_imagen_principal_publicada()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_retirada BOOLEAN;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_retirada := OLD.principal;
  ELSE
    v_retirada := OLD.principal
      AND (NOT NEW.principal OR NEW.producto_id <> OLD.producto_id);
  END IF;

  IF v_retirada
     AND EXISTS (
       SELECT 1 FROM productos WHERE id = OLD.producto_id AND publicado_web
     )
     AND NOT EXISTS (
       SELECT 1
       FROM producto_imagenes
       WHERE producto_id = OLD.producto_id
         AND principal
         AND id <> OLD.id
     ) THEN
    RAISE EXCEPTION 'No se puede retirar la imagen principal de un producto publicado.'
      USING ERRCODE = '23514';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS producto_imagenes_proteger_principal_trg
  ON producto_imagenes;
CREATE TRIGGER producto_imagenes_proteger_principal_trg
  BEFORE DELETE OR UPDATE OF principal, producto_id ON producto_imagenes
  FOR EACH ROW
  EXECUTE FUNCTION proteger_imagen_principal_publicada();

CREATE TABLE IF NOT EXISTS reglas_precio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  canal VARCHAR(8) NOT NULL,
  tipo VARCHAR(16) NOT NULL,
  valor NUMERIC(12,2) NOT NULL,
  producto_id INTEGER REFERENCES productos(id) ON DELETE RESTRICT,
  categoria_id INTEGER REFERENCES categorias(id) ON DELETE RESTRICT,
  cantidad_minima INTEGER NOT NULL DEFAULT 1,
  prioridad INTEGER NOT NULL DEFAULT 0,
  vigente_desde TIMESTAMPTZ,
  vigente_hasta TIMESTAMPTZ,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT reglas_precio_nombre_check CHECK (btrim(nombre) <> ''),
  CONSTRAINT reglas_precio_canal_check CHECK (canal IN ('AMBOS', 'POS', 'WEB')),
  CONSTRAINT reglas_precio_tipo_check
    CHECK (tipo IN ('PORCENTAJE', 'MONTO_FIJO', 'PRECIO_FIJO')),
  CONSTRAINT reglas_precio_valor_check CHECK (
    (tipo = 'PORCENTAJE' AND valor BETWEEN 0 AND 100)
    OR (tipo IN ('MONTO_FIJO', 'PRECIO_FIJO') AND valor >= 0)
  ),
  CONSTRAINT reglas_precio_alcance_check
    CHECK (num_nonnulls(producto_id, categoria_id) <= 1),
  CONSTRAINT reglas_precio_cantidad_check CHECK (cantidad_minima > 0),
  CONSTRAINT reglas_precio_vigencia_check CHECK (
    vigente_hasta IS NULL OR vigente_desde IS NULL OR vigente_hasta > vigente_desde
  )
);

CREATE INDEX IF NOT EXISTS reglas_precio_producto_idx
  ON reglas_precio (producto_id, canal, prioridad DESC, id) WHERE activo;
CREATE INDEX IF NOT EXISTS reglas_precio_categoria_idx
  ON reglas_precio (categoria_id, canal, prioridad DESC, id) WHERE activo;

DROP TRIGGER IF EXISTS reglas_precio_actualizado_en_trg ON reglas_precio;
CREATE TRIGGER reglas_precio_actualizado_en_trg
  BEFORE UPDATE ON reglas_precio
  FOR EACH ROW
  EXECUTE FUNCTION marcar_actualizado_en();

CREATE OR REPLACE FUNCTION calcular_precio_comun(
  p_producto_id INTEGER,
  p_cantidad INTEGER,
  p_canal TEXT,
  p_fecha TIMESTAMPTZ DEFAULT NOW()
)
RETURNS TABLE (
  precio_lista NUMERIC(12,2),
  descuento_unitario NUMERIC(12,2),
  precio_unitario NUMERIC(12,2),
  regla_precio_id BIGINT
)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
  v_precio NUMERIC(12,2);
  v_categoria_id INTEGER;
  v_regla reglas_precio%ROWTYPE;
  v_precio_final NUMERIC(12,2);
  v_fecha TIMESTAMPTZ := COALESCE(p_fecha, NOW());
BEGIN
  IF p_producto_id IS NULL OR p_cantidad IS NULL OR p_cantidad <= 0 THEN
    RAISE EXCEPTION 'Producto y cantidad positiva son obligatorios.'
      USING ERRCODE = '22023';
  END IF;
  IF p_canal NOT IN ('POS', 'WEB') THEN
    RAISE EXCEPTION 'Canal de precio inválido: %', p_canal
      USING ERRCODE = '22023';
  END IF;

  SELECT p.precio, p.categoria_id
  INTO v_precio, v_categoria_id
  FROM productos p
  WHERE p.id = p_producto_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Producto % no encontrado.', p_producto_id
      USING ERRCODE = 'P0002';
  END IF;

  SELECT r.*
  INTO v_regla
  FROM reglas_precio r
  WHERE r.activo
    AND r.cantidad_minima <= p_cantidad
    AND r.canal IN ('AMBOS', p_canal)
    AND (r.vigente_desde IS NULL OR r.vigente_desde <= v_fecha)
    AND (r.vigente_hasta IS NULL OR r.vigente_hasta > v_fecha)
    AND (
      r.producto_id = p_producto_id
      OR (r.producto_id IS NULL AND r.categoria_id = v_categoria_id)
      OR (r.producto_id IS NULL AND r.categoria_id IS NULL)
    )
  ORDER BY
    r.prioridad DESC,
    CASE
      WHEN r.producto_id IS NOT NULL THEN 2
      WHEN r.categoria_id IS NOT NULL THEN 1
      ELSE 0
    END DESC,
    r.id
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN QUERY
      SELECT v_precio, 0.00::NUMERIC(12,2), v_precio, NULL::BIGINT;
    RETURN;
  END IF;

  v_precio_final := ROUND(
    CASE v_regla.tipo
      WHEN 'PORCENTAJE' THEN v_precio * (1 - v_regla.valor / 100)
      WHEN 'MONTO_FIJO' THEN v_precio - v_regla.valor
      WHEN 'PRECIO_FIJO' THEN v_regla.valor
    END,
    2
  );
  v_precio_final := GREATEST(
    0.00::NUMERIC,
    LEAST(v_precio, v_precio_final)
  );

  RETURN QUERY
    SELECT
      v_precio,
      (v_precio - v_precio_final)::NUMERIC(12,2),
      v_precio_final,
      v_regla.id;
END
$function$;

ALTER TABLE detalle_ventas
  ADD COLUMN IF NOT EXISTS precio_lista NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS descuento_unitario NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS regla_precio_id BIGINT;

UPDATE detalle_ventas
SET precio_lista = COALESCE(precio_lista, precio_unitario),
    descuento_unitario = COALESCE(
      descuento_unitario,
      COALESCE(precio_lista, precio_unitario) - precio_unitario
    )
WHERE precio_lista IS NULL OR descuento_unitario IS NULL;

CREATE OR REPLACE FUNCTION completar_snapshot_detalle_venta()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.precio_lista := COALESCE(NEW.precio_lista, NEW.precio_unitario);
  NEW.descuento_unitario := COALESCE(
    NEW.descuento_unitario,
    NEW.precio_lista - NEW.precio_unitario
  );
  RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS detalle_ventas_completar_snapshot_trg ON detalle_ventas;
CREATE TRIGGER detalle_ventas_completar_snapshot_trg
  BEFORE INSERT ON detalle_ventas
  FOR EACH ROW
  EXECUTE FUNCTION completar_snapshot_detalle_venta();

ALTER TABLE detalle_ventas
  ALTER COLUMN precio_lista SET NOT NULL,
  ALTER COLUMN descuento_unitario SET DEFAULT 0,
  ALTER COLUMN descuento_unitario SET NOT NULL;

DO $migration$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'detalle_ventas'::regclass
      AND conname = 'detalle_ventas_regla_precio_fk'
  ) THEN
    ALTER TABLE detalle_ventas
      ADD CONSTRAINT detalle_ventas_regla_precio_fk
      FOREIGN KEY (regla_precio_id)
      REFERENCES reglas_precio(id)
      ON DELETE RESTRICT;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM detalle_ventas
    WHERE importe <> ROUND(precio_unitario * cantidad, 2)
  ) THEN
    RAISE EXCEPTION 'Hay importes históricos que no coinciden con precio por cantidad; no se alteraron.';
  END IF;
END
$migration$;

ALTER TABLE detalle_ventas DROP CONSTRAINT IF EXISTS detalle_ventas_precio_lista_check;
ALTER TABLE detalle_ventas
  ADD CONSTRAINT detalle_ventas_precio_lista_check CHECK (precio_lista >= 0);
ALTER TABLE detalle_ventas DROP CONSTRAINT IF EXISTS detalle_ventas_descuento_check;
ALTER TABLE detalle_ventas
  ADD CONSTRAINT detalle_ventas_descuento_check CHECK (
    descuento_unitario >= 0
    AND precio_unitario = precio_lista - descuento_unitario
  );
ALTER TABLE detalle_ventas DROP CONSTRAINT IF EXISTS detalle_ventas_importe_snapshot_check;
ALTER TABLE detalle_ventas
  ADD CONSTRAINT detalle_ventas_importe_snapshot_check CHECK (
    importe = ROUND(precio_unitario * cantidad, 2)
  );

CREATE INDEX IF NOT EXISTS detalle_ventas_regla_precio_idx
  ON detalle_ventas (regla_precio_id)
  WHERE regla_precio_id IS NOT NULL;
