-- Clientes, pedidos y reservas sobre el inventario y precios compartidos.
-- Los datos históricos no se convierten artificialmente en clientes ni pedidos.

CREATE TABLE clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL CHECK (btrim(nombre) <> ''),
  telefono VARCHAR(30),
  email VARCHAR(254),
  direccion TEXT,
  notas TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (telefono IS NULL OR btrim(telefono) <> ''),
  CHECK (email IS NULL OR btrim(email) <> ''),
  CHECK (direccion IS NULL OR btrim(direccion) <> '')
);

CREATE INDEX clientes_nombre_lower_idx ON clientes (lower(nombre));
CREATE INDEX clientes_telefono_idx ON clientes (telefono) WHERE telefono IS NOT NULL;
CREATE UNIQUE INDEX clientes_email_lower_uq
  ON clientes (lower(email)) WHERE email IS NOT NULL;
CREATE TRIGGER clientes_actualizado_en_trg
  BEFORE UPDATE ON clientes FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE SEQUENCE pedidos_folio_seq START WITH 1;

CREATE TABLE pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('P-' || LPAD(nextval('pedidos_folio_seq')::text, 10, '0')),
  canal VARCHAR(8) NOT NULL CHECK (canal IN ('WEB', 'INTERNO')),
  canal_precio VARCHAR(3) NOT NULL CHECK (canal_precio IN ('POS', 'WEB')),
  estado VARCHAR(16) NOT NULL DEFAULT 'RESERVADO'
    CHECK (estado IN ('RESERVADO', 'LISTO', 'COMPLETADO', 'CANCELADO', 'EXPIRADO')),
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE RESTRICT,
  creado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  cliente_nombre VARCHAR(120) NOT NULL CHECK (btrim(cliente_nombre) <> ''),
  cliente_telefono VARCHAR(30) NOT NULL CHECK (btrim(cliente_telefono) <> ''),
  cliente_email VARCHAR(254),
  cliente_direccion TEXT,
  tipo_entrega VARCHAR(12) NOT NULL CHECK (tipo_entrega IN ('ENVIO', 'RECOLECCION')),
  notas TEXT,
  subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
  descuento NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
  iva NUMERIC(12,2) NOT NULL CHECK (iva >= 0),
  total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
  expira_en TIMESTAMPTZ NOT NULL,
  whatsapp_notificado_en TIMESTAMPTZ,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (
    (canal = 'WEB' AND canal_precio = 'WEB' AND creado_por_usuario_id IS NULL)
    OR (canal = 'INTERNO' AND canal_precio = 'POS' AND creado_por_usuario_id IS NOT NULL)
  ),
  CHECK (cliente_email IS NULL OR btrim(cliente_email) <> ''),
  CHECK (
    (tipo_entrega = 'ENVIO' AND btrim(COALESCE(cliente_direccion, '')) <> '')
    OR tipo_entrega = 'RECOLECCION'
  ),
  CHECK (total = ROUND(subtotal + iva, 2)),
  CHECK (expira_en > creado_en)
);

CREATE INDEX pedidos_estado_expiracion_idx ON pedidos (estado, expira_en);
CREATE INDEX pedidos_canal_fecha_idx ON pedidos (canal, creado_en DESC, id DESC);
CREATE INDEX pedidos_cliente_fecha_idx
  ON pedidos (cliente_id, creado_en DESC, id DESC) WHERE cliente_id IS NOT NULL;
CREATE TRIGGER pedidos_actualizado_en_trg
  BEFORE UPDATE ON pedidos FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE TABLE detalle_pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  producto_sku VARCHAR(24) NOT NULL CHECK (btrim(producto_sku) <> ''),
  producto_titulo VARCHAR(160) NOT NULL CHECK (btrim(producto_titulo) <> ''),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  precio_lista NUMERIC(12,2) NOT NULL CHECK (precio_lista >= 0),
  descuento_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
  precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
  iva_porcentaje NUMERIC(5,2) NOT NULL CHECK (iva_porcentaje BETWEEN 0 AND 100),
  regla_precio_id BIGINT REFERENCES reglas_precio(id) ON DELETE RESTRICT,
  importe NUMERIC(12,2) NOT NULL CHECK (importe >= 0),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (pedido_id, producto_id),
  UNIQUE (id, pedido_id, producto_id),
  CHECK (descuento_unitario >= 0 AND precio_unitario = precio_lista - descuento_unitario),
  CHECK (importe = ROUND(precio_unitario * cantidad, 2))
);

CREATE INDEX detalle_pedidos_producto_idx ON detalle_pedidos (producto_id);

CREATE TABLE reservas_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
  detalle_pedido_id BIGINT NOT NULL,
  producto_id INTEGER NOT NULL,
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  estado VARCHAR(12) NOT NULL DEFAULT 'ACTIVA'
    CHECK (estado IN ('ACTIVA', 'LIBERADA', 'CONSUMIDA', 'EXPIRADA')),
  expira_en TIMESTAMPTZ NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finalizada_en TIMESTAMPTZ,
  FOREIGN KEY (detalle_pedido_id, pedido_id, producto_id)
    REFERENCES detalle_pedidos(id, pedido_id, producto_id) ON DELETE RESTRICT,
  UNIQUE (pedido_id, producto_id),
  UNIQUE (detalle_pedido_id),
  UNIQUE (id, pedido_id, producto_id),
  CHECK (expira_en > creado_en),
  CHECK (
    (estado = 'ACTIVA' AND finalizada_en IS NULL)
    OR (estado <> 'ACTIVA' AND finalizada_en IS NOT NULL)
  )
);

CREATE INDEX reservas_stock_expiracion_activa_idx
  ON reservas_stock (expira_en, pedido_id) WHERE estado = 'ACTIVA';
CREATE INDEX reservas_stock_producto_estado_idx ON reservas_stock (producto_id, estado);

CREATE TABLE pedido_transiciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
  estado_anterior VARCHAR(16),
  estado_nuevo VARCHAR(16) NOT NULL,
  actor VARCHAR(12) NOT NULL CHECK (actor IN ('USUARIO', 'PUBLICO', 'SISTEMA')),
  usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(240) NOT NULL CHECK (btrim(motivo) <> ''),
  origen_clave VARCHAR(180) NOT NULL UNIQUE CHECK (btrim(origen_clave) <> ''),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (estado_anterior IS NULL OR estado_anterior IN (
    'RESERVADO', 'LISTO', 'COMPLETADO', 'CANCELADO', 'EXPIRADO'
  )),
  CHECK (estado_nuevo IN (
    'RESERVADO', 'LISTO', 'COMPLETADO', 'CANCELADO', 'EXPIRADO'
  )),
  CHECK (estado_anterior IS NULL OR estado_anterior <> estado_nuevo),
  CHECK (estado_anterior IS NOT NULL OR estado_nuevo = 'RESERVADO'),
  CHECK (
    (actor = 'USUARIO' AND usuario_id IS NOT NULL)
    OR (actor <> 'USUARIO' AND usuario_id IS NULL)
  )
);

CREATE INDEX pedido_transiciones_pedido_idx ON pedido_transiciones (pedido_id, id DESC);

ALTER TABLE ventas
  ADD COLUMN pedido_id BIGINT,
  ADD COLUMN cliente_id BIGINT;
ALTER TABLE ventas ADD CONSTRAINT ventas_pedido_fk
  FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE RESTRICT;
ALTER TABLE ventas ADD CONSTRAINT ventas_cliente_fk
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT;
ALTER TABLE ventas ADD CONSTRAINT ventas_id_pedido_uq UNIQUE (id, pedido_id);
CREATE UNIQUE INDEX ventas_pedido_uq ON ventas (pedido_id) WHERE pedido_id IS NOT NULL;
CREATE INDEX ventas_cliente_idx ON ventas (cliente_id) WHERE cliente_id IS NOT NULL;

-- Idempotencia pública reutiliza la tabla existente sin romper el conflict target del POS.
ALTER TABLE operaciones_idempotentes ADD COLUMN actor_clave VARCHAR(160);
UPDATE operaciones_idempotentes
SET actor_clave = 'USUARIO:' || usuario_id::text
WHERE actor_clave IS NULL;
ALTER TABLE operaciones_idempotentes ALTER COLUMN usuario_id DROP NOT NULL;
ALTER TABLE operaciones_idempotentes ALTER COLUMN actor_clave SET NOT NULL;
ALTER TABLE operaciones_idempotentes ADD CONSTRAINT operaciones_idempotentes_actor_check CHECK (
  (usuario_id IS NOT NULL AND actor_clave = 'USUARIO:' || usuario_id::text)
  OR (usuario_id IS NULL AND actor_clave ~ '^PUBLICO:[0-9a-f]{64}$')
);
ALTER TABLE operaciones_idempotentes ADD CONSTRAINT operaciones_idempotentes_actor_operacion_clave_uq
  UNIQUE (actor_clave, operacion, clave);

CREATE OR REPLACE FUNCTION completar_actor_idempotencia()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.usuario_id IS NOT NULL THEN
    NEW.actor_clave := COALESCE(NEW.actor_clave, 'USUARIO:' || NEW.usuario_id::text);
    IF NEW.actor_clave <> 'USUARIO:' || NEW.usuario_id::text THEN
      RAISE EXCEPTION 'actor_clave no corresponde al usuario.' USING ERRCODE = '23514';
    END IF;
  ELSIF NEW.actor_clave IS NULL OR NEW.actor_clave !~ '^PUBLICO:[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'Una operación pública requiere un actor opaco válido.' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;
CREATE TRIGGER operaciones_idempotentes_actor_trg
  BEFORE INSERT OR UPDATE OF usuario_id, actor_clave ON operaciones_idempotentes
  FOR EACH ROW EXECUTE FUNCTION completar_actor_idempotencia();

ALTER TABLE inventario_movimientos
  ADD COLUMN pedido_id BIGINT,
  ADD COLUMN reserva_id BIGINT;
ALTER TABLE inventario_movimientos ADD CONSTRAINT inventario_movimientos_pedido_fk
  FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE RESTRICT;
ALTER TABLE inventario_movimientos ADD CONSTRAINT inventario_movimientos_reserva_fk
  FOREIGN KEY (reserva_id, pedido_id, producto_id)
  REFERENCES reservas_stock(id, pedido_id, producto_id) ON DELETE RESTRICT;
ALTER TABLE inventario_movimientos ADD CONSTRAINT inventario_movimientos_venta_pedido_fk
  FOREIGN KEY (venta_id, pedido_id) REFERENCES ventas(id, pedido_id) ON DELETE RESTRICT;

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_tipo_check;
ALTER TABLE inventario_movimientos ADD CONSTRAINT inventario_movimientos_tipo_check CHECK (
  tipo IN (
    'INICIAL', 'AJUSTE', 'VENTA', 'CANCELACION', 'DEVOLUCION',
    'RESERVA', 'LIBERACION_RESERVA', 'EXPIRACION_RESERVA', 'CONSUMO_RESERVA'
  )
);
ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_inicial_check;
ALTER TABLE inventario_movimientos ADD CONSTRAINT inventario_movimientos_inicial_check CHECK (
  tipo <> 'INICIAL' OR (
    actor = 'MIGRACION' AND usuario_id IS NULL
    AND delta_fisico >= 0 AND delta_reservado >= 0
    AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
    AND pedido_id IS NULL AND reserva_id IS NULL
  )
);
ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_ajuste_check;
ALTER TABLE inventario_movimientos ADD CONSTRAINT inventario_movimientos_ajuste_check CHECK (
  tipo <> 'AJUSTE' OR (
    actor = 'USUARIO' AND usuario_id IS NOT NULL
    AND btrim(COALESCE(motivo, '')) <> ''
    AND delta_fisico <> 0 AND delta_reservado = 0
    AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
    AND pedido_id IS NULL AND reserva_id IS NULL
  )
);
ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_origen_pos_check;
ALTER TABLE inventario_movimientos ADD CONSTRAINT inventario_movimientos_origen_check CHECK (
  (tipo = 'INICIAL' AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
    AND pedido_id IS NULL AND reserva_id IS NULL)
  OR (tipo = 'AJUSTE' AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
    AND pedido_id IS NULL AND reserva_id IS NULL)
  OR (tipo = 'VENTA' AND venta_id IS NOT NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
    AND pedido_id IS NULL AND reserva_id IS NULL AND delta_fisico < 0 AND delta_reservado = 0)
  OR (tipo = 'CANCELACION' AND venta_id IS NULL AND cancelacion_id IS NOT NULL AND devolucion_id IS NULL
    AND pedido_id IS NULL AND reserva_id IS NULL AND delta_fisico > 0 AND delta_reservado = 0)
  OR (tipo = 'DEVOLUCION' AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NOT NULL
    AND pedido_id IS NULL AND reserva_id IS NULL AND delta_fisico > 0 AND delta_reservado = 0)
  OR (tipo = 'RESERVA' AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
    AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL AND delta_fisico = 0 AND delta_reservado > 0)
  OR (tipo IN ('LIBERACION_RESERVA', 'EXPIRACION_RESERVA')
    AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
    AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL AND delta_fisico = 0 AND delta_reservado < 0)
  OR (tipo = 'CONSUMO_RESERVA' AND venta_id IS NOT NULL
    AND cancelacion_id IS NULL AND devolucion_id IS NULL
    AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
    AND delta_fisico < 0 AND delta_reservado = delta_fisico)
);

CREATE INDEX inventario_movimientos_pedido_idx
  ON inventario_movimientos (pedido_id, id DESC) WHERE pedido_id IS NOT NULL;
CREATE UNIQUE INDEX inventario_movimientos_reserva_creacion_uq
  ON inventario_movimientos (reserva_id) WHERE tipo = 'RESERVA';
CREATE UNIQUE INDEX inventario_movimientos_reserva_final_uq
  ON inventario_movimientos (reserva_id)
  WHERE tipo IN ('LIBERACION_RESERVA', 'EXPIRACION_RESERVA', 'CONSUMO_RESERVA');
CREATE UNIQUE INDEX inventario_movimientos_consumo_venta_producto_uq
  ON inventario_movimientos (venta_id, producto_id) WHERE tipo = 'CONSUMO_RESERVA';

CREATE OR REPLACE FUNCTION impedir_mutacion_detalle_pedido()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  RAISE EXCEPTION 'El detalle de un pedido es inmutable.' USING ERRCODE = '55000';
END
$function$;
CREATE TRIGGER detalle_pedidos_inmutable_trg
  BEFORE UPDATE OR DELETE ON detalle_pedidos
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_detalle_pedido();

CREATE OR REPLACE FUNCTION impedir_mutacion_pedido_transiciones()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  RAISE EXCEPTION 'El historial de pedidos es inmutable.' USING ERRCODE = '55000';
END
$function$;
CREATE TRIGGER pedido_transiciones_inmutable_trg
  BEFORE UPDATE OR DELETE ON pedido_transiciones
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_pedido_transiciones();

CREATE OR REPLACE FUNCTION validar_cambio_reserva_stock()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Las reservas no se eliminan.' USING ERRCODE = '55000';
  END IF;
  IF ROW(NEW.pedido_id, NEW.detalle_pedido_id, NEW.producto_id, NEW.cantidad, NEW.expira_en, NEW.creado_en)
     IS DISTINCT FROM
     ROW(OLD.pedido_id, OLD.detalle_pedido_id, OLD.producto_id, OLD.cantidad, OLD.expira_en, OLD.creado_en) THEN
    RAISE EXCEPTION 'No se puede alterar el origen de una reserva.' USING ERRCODE = '55000';
  END IF;
  IF OLD.estado <> 'ACTIVA' OR NEW.estado NOT IN ('LIBERADA', 'CONSUMIDA', 'EXPIRADA') THEN
    RAISE EXCEPTION 'Transición de reserva inválida.' USING ERRCODE = '23514';
  END IF;
  NEW.finalizada_en := COALESCE(NEW.finalizada_en, NOW());
  RETURN NEW;
END
$function$;
CREATE TRIGGER reservas_stock_validar_cambio_trg
  BEFORE UPDATE OR DELETE ON reservas_stock
  FOR EACH ROW EXECUTE FUNCTION validar_cambio_reserva_stock();

CREATE OR REPLACE FUNCTION validar_transicion_pedido()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.estado = OLD.estado THEN RETURN NEW; END IF;
  IF NOT (
    (OLD.estado = 'RESERVADO' AND NEW.estado IN ('LISTO', 'COMPLETADO', 'CANCELADO', 'EXPIRADO'))
    OR (OLD.estado = 'LISTO' AND NEW.estado IN ('COMPLETADO', 'CANCELADO', 'EXPIRADO'))
  ) THEN
    RAISE EXCEPTION 'Transición de pedido no permitida: % -> %.', OLD.estado, NEW.estado
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;
CREATE TRIGGER pedidos_validar_transicion_trg
  BEFORE UPDATE OF estado ON pedidos FOR EACH ROW EXECUTE FUNCTION validar_transicion_pedido();

CREATE OR REPLACE VIEW inventario_conciliacion AS
WITH kardex AS (
  SELECT producto_id,
         COALESCE(SUM(delta_fisico), 0)::BIGINT AS fisico_kardex,
         COALESCE(SUM(delta_reservado), 0)::BIGINT AS reservado_kardex
  FROM inventario_movimientos GROUP BY producto_id
), reservas AS (
  SELECT producto_id, COALESCE(SUM(cantidad), 0)::BIGINT AS reservado_activo
  FROM reservas_stock WHERE estado = 'ACTIVA' GROUP BY producto_id
)
SELECT p.id AS producto_id, p.sku, p.titulo,
       p.stock::BIGINT AS stock_fisico,
       COALESCE(k.fisico_kardex, 0) AS stock_fisico_kardex,
       p.stock::BIGINT - COALESCE(k.fisico_kardex, 0) AS diferencia_fisico_kardex,
       p.stock_reservado::BIGINT AS stock_reservado,
       COALESCE(r.reservado_activo, 0) AS reservado_activo,
       COALESCE(k.reservado_kardex, 0) AS stock_reservado_kardex,
       p.stock_reservado::BIGINT - COALESCE(r.reservado_activo, 0) AS diferencia_reservas_activas,
       p.stock_reservado::BIGINT - COALESCE(k.reservado_kardex, 0) AS diferencia_reservado_kardex,
       p.stock_disponible::BIGINT AS stock_disponible,
       (p.stock = COALESCE(k.fisico_kardex, 0)
        AND p.stock_reservado = COALESCE(r.reservado_activo, 0)
        AND p.stock_reservado = COALESCE(k.reservado_kardex, 0)) AS conciliado
FROM productos p
LEFT JOIN kardex k ON k.producto_id = p.id
LEFT JOIN reservas r ON r.producto_id = p.id;

-- El historial es la única vía de cambio de estado y los snapshots son inmutables.
DROP TRIGGER IF EXISTS pedidos_validar_transicion_trg ON pedidos;
DROP FUNCTION IF EXISTS validar_transicion_pedido();

CREATE OR REPLACE FUNCTION proteger_snapshot_pedido()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Los pedidos son auditables y no pueden eliminarse.' USING ERRCODE = '55000';
  END IF;
  IF ROW(
    NEW.id, NEW.folio, NEW.canal, NEW.canal_precio, NEW.cliente_id,
    NEW.creado_por_usuario_id, NEW.cliente_nombre, NEW.cliente_telefono,
    NEW.cliente_email, NEW.cliente_direccion, NEW.tipo_entrega, NEW.notas,
    NEW.subtotal, NEW.descuento, NEW.iva, NEW.total, NEW.expira_en, NEW.creado_en
  ) IS DISTINCT FROM ROW(
    OLD.id, OLD.folio, OLD.canal, OLD.canal_precio, OLD.cliente_id,
    OLD.creado_por_usuario_id, OLD.cliente_nombre, OLD.cliente_telefono,
    OLD.cliente_email, OLD.cliente_direccion, OLD.tipo_entrega, OLD.notas,
    OLD.subtotal, OLD.descuento, OLD.iva, OLD.total, OLD.expira_en, OLD.creado_en
  ) THEN
    RAISE EXCEPTION 'El contenido comercial de un pedido es inmutable.' USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;
CREATE TRIGGER pedidos_proteger_snapshot_trg
  BEFORE UPDATE OR DELETE ON pedidos FOR EACH ROW EXECUTE FUNCTION proteger_snapshot_pedido();

CREATE OR REPLACE FUNCTION proteger_estado_pedido()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.estado IS DISTINCT FROM OLD.estado
     AND COALESCE(current_setting('libra.aplicando_transicion_pedido', TRUE), '') <> '1' THEN
    RAISE EXCEPTION 'El estado sólo cambia mediante pedido_transiciones.' USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;
CREATE TRIGGER pedidos_proteger_estado_trg
  BEFORE UPDATE OF estado ON pedidos FOR EACH ROW EXECUTE FUNCTION proteger_estado_pedido();

CREATE OR REPLACE FUNCTION validar_insert_transicion_pedido()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_estado VARCHAR(16);
BEGIN
  SELECT estado INTO v_estado FROM pedidos WHERE id = NEW.pedido_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pedido % no encontrado.', NEW.pedido_id USING ERRCODE = '23503';
  END IF;

  IF NEW.estado_anterior IS NULL THEN
    IF v_estado <> 'RESERVADO' OR NEW.estado_nuevo <> 'RESERVADO'
       OR EXISTS (SELECT 1 FROM pedido_transiciones WHERE pedido_id = NEW.pedido_id) THEN
      RAISE EXCEPTION 'Transición inicial inválida.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
  END IF;

  IF v_estado <> NEW.estado_anterior THEN
    RAISE EXCEPTION 'El pedido está en %, no en %.', v_estado, NEW.estado_anterior
      USING ERRCODE = '40001';
  END IF;
  IF NOT (
    (NEW.estado_anterior = 'RESERVADO'
      AND NEW.estado_nuevo IN ('LISTO', 'COMPLETADO', 'CANCELADO', 'EXPIRADO'))
    OR (NEW.estado_anterior = 'LISTO'
      AND NEW.estado_nuevo IN ('COMPLETADO', 'CANCELADO', 'EXPIRADO'))
  ) THEN
    RAISE EXCEPTION 'Transición no permitida: % -> %.', NEW.estado_anterior, NEW.estado_nuevo
      USING ERRCODE = '23514';
  END IF;
  IF NEW.estado_nuevo IN ('LISTO', 'COMPLETADO') AND NEW.actor <> 'USUARIO' THEN
    RAISE EXCEPTION 'La transición requiere un usuario autenticado.' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;
CREATE TRIGGER pedido_transiciones_validar_trg
  BEFORE INSERT ON pedido_transiciones FOR EACH ROW EXECUTE FUNCTION validar_insert_transicion_pedido();

CREATE OR REPLACE FUNCTION aplicar_transicion_pedido()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_actualizados INTEGER;
BEGIN
  IF NEW.estado_anterior IS NULL THEN RETURN NULL; END IF;
  PERFORM set_config('libra.aplicando_transicion_pedido', '1', TRUE);
  UPDATE pedidos SET estado = NEW.estado_nuevo
  WHERE id = NEW.pedido_id AND estado = NEW.estado_anterior;
  GET DIAGNOSTICS v_actualizados = ROW_COUNT;
  PERFORM set_config('libra.aplicando_transicion_pedido', '0', TRUE);
  IF v_actualizados <> 1 THEN
    RAISE EXCEPTION 'El pedido cambió concurrentemente.' USING ERRCODE = '40001';
  END IF;
  RETURN NULL;
END
$function$;
CREATE TRIGGER pedido_transiciones_aplicar_trg
  AFTER INSERT ON pedido_transiciones FOR EACH ROW EXECUTE FUNCTION aplicar_transicion_pedido();

CREATE OR REPLACE FUNCTION registrar_creacion_pedido()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.estado <> 'RESERVADO' THEN
    RAISE EXCEPTION 'Todo pedido debe iniciar RESERVADO.' USING ERRCODE = '23514';
  END IF;
  INSERT INTO pedido_transiciones (
    pedido_id, estado_anterior, estado_nuevo, actor, usuario_id, motivo, origen_clave, creado_en
  ) VALUES (
    NEW.id, NULL, 'RESERVADO',
    CASE WHEN NEW.creado_por_usuario_id IS NULL THEN 'PUBLICO' ELSE 'USUARIO' END,
    NEW.creado_por_usuario_id, 'Creación y reserva atómica del pedido.',
    'PEDIDO:' || NEW.id::text || ':CREACION', NEW.creado_en
  );
  RETURN NULL;
END
$function$;
CREATE TRIGGER pedidos_registrar_creacion_trg
  AFTER INSERT ON pedidos FOR EACH ROW EXECUTE FUNCTION registrar_creacion_pedido();

-- Conciliación diferida: ninguna transacción puede confirmar un pedido parcial.
CREATE OR REPLACE FUNCTION validar_pedido_conciliado(p_pedido_id BIGINT)
RETURNS VOID LANGUAGE plpgsql AS $function$
DECLARE
  v_pedido pedidos%ROWTYPE;
  v_total NUMERIC(12,2);
  v_descuento NUMERIC(12,2);
  v_subtotal NUMERIC(12,2);
  v_iva NUMERIC(12,2);
  v_ultimo_estado VARCHAR(16);
BEGIN
  IF p_pedido_id IS NULL THEN RETURN; END IF;
  SELECT * INTO v_pedido FROM pedidos WHERE id = p_pedido_id;
  IF NOT FOUND THEN RETURN; END IF;

  IF NOT EXISTS (SELECT 1 FROM detalle_pedidos WHERE pedido_id = p_pedido_id) THEN
    RAISE EXCEPTION 'El pedido % no contiene artículos.', p_pedido_id USING ERRCODE = '23514';
  END IF;
  IF EXISTS (
    SELECT 1 FROM detalle_pedidos d
    LEFT JOIN reservas_stock r
      ON r.pedido_id = d.pedido_id AND r.producto_id = d.producto_id
    WHERE d.pedido_id = p_pedido_id
      AND (r.id IS NULL OR r.detalle_pedido_id <> d.id OR r.cantidad <> d.cantidad
           OR r.expira_en <> v_pedido.expira_en)
  ) THEN
    RAISE EXCEPTION 'Las reservas no corresponden al detalle del pedido %.', p_pedido_id
      USING ERRCODE = '23514';
  END IF;

  SELECT ROUND(COALESCE(SUM(importe), 0), 2),
         ROUND(COALESCE(SUM(descuento_unitario * cantidad), 0), 2),
         ROUND(COALESCE(SUM(importe / (1 + iva_porcentaje / 100)), 0), 2)
  INTO v_total, v_descuento, v_subtotal
  FROM detalle_pedidos WHERE pedido_id = p_pedido_id;
  v_iva := ROUND(v_total - v_subtotal, 2);
  IF v_total <> v_pedido.total OR v_descuento <> v_pedido.descuento
     OR v_subtotal <> v_pedido.subtotal OR v_iva <> v_pedido.iva THEN
    RAISE EXCEPTION 'Los totales del pedido % no concilian.', p_pedido_id USING ERRCODE = '23514';
  END IF;

  SELECT estado_nuevo INTO v_ultimo_estado
  FROM pedido_transiciones WHERE pedido_id = p_pedido_id ORDER BY id DESC LIMIT 1;
  IF v_ultimo_estado IS DISTINCT FROM v_pedido.estado THEN
    RAISE EXCEPTION 'El historial del pedido % no concilia con su estado.', p_pedido_id
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1 FROM reservas_stock r
    WHERE r.pedido_id = p_pedido_id
      AND NOT EXISTS (
        SELECT 1 FROM inventario_movimientos im
        WHERE im.reserva_id = r.id AND im.pedido_id = r.pedido_id
          AND im.producto_id = r.producto_id AND im.tipo = 'RESERVA'
          AND im.delta_fisico = 0 AND im.delta_reservado = r.cantidad
      )
  ) THEN
    RAISE EXCEPTION 'Hay reservas sin alta exacta en kardex para el pedido %.', p_pedido_id
      USING ERRCODE = '23514';
  END IF;

  IF v_pedido.estado IN ('RESERVADO', 'LISTO') THEN
    IF EXISTS (SELECT 1 FROM reservas_stock WHERE pedido_id = p_pedido_id AND estado <> 'ACTIVA')
       OR EXISTS (SELECT 1 FROM ventas WHERE pedido_id = p_pedido_id)
       OR EXISTS (
         SELECT 1 FROM inventario_movimientos
         WHERE pedido_id = p_pedido_id
           AND tipo IN ('LIBERACION_RESERVA', 'EXPIRACION_RESERVA', 'CONSUMO_RESERVA')
       ) THEN
      RAISE EXCEPTION 'El pedido activo % no concilia.', p_pedido_id USING ERRCODE = '23514';
    END IF;
  ELSIF v_pedido.estado = 'COMPLETADO' THEN
    IF NOT EXISTS (SELECT 1 FROM ventas WHERE pedido_id = p_pedido_id)
       OR EXISTS (
         SELECT 1 FROM reservas_stock r
         WHERE r.pedido_id = p_pedido_id AND (
           r.estado <> 'CONSUMIDA' OR NOT EXISTS (
             SELECT 1 FROM inventario_movimientos im
             JOIN ventas v ON v.id = im.venta_id AND v.pedido_id = p_pedido_id
             WHERE im.reserva_id = r.id AND im.tipo = 'CONSUMO_RESERVA'
               AND im.delta_fisico = -r.cantidad AND im.delta_reservado = -r.cantidad
           )
         )
       ) THEN
      RAISE EXCEPTION 'El pedido completado % no concilia.', p_pedido_id USING ERRCODE = '23514';
    END IF;
  ELSIF v_pedido.estado = 'CANCELADO' THEN
    IF EXISTS (SELECT 1 FROM ventas WHERE pedido_id = p_pedido_id)
       OR EXISTS (
         SELECT 1 FROM reservas_stock r
         WHERE r.pedido_id = p_pedido_id AND (
           r.estado <> 'LIBERADA' OR NOT EXISTS (
             SELECT 1 FROM inventario_movimientos im
             WHERE im.reserva_id = r.id AND im.tipo = 'LIBERACION_RESERVA'
               AND im.delta_fisico = 0 AND im.delta_reservado = -r.cantidad
           )
         )
       ) THEN
      RAISE EXCEPTION 'El pedido cancelado % no concilia.', p_pedido_id USING ERRCODE = '23514';
    END IF;
  ELSIF v_pedido.estado = 'EXPIRADO' THEN
    IF EXISTS (SELECT 1 FROM ventas WHERE pedido_id = p_pedido_id)
       OR EXISTS (
         SELECT 1 FROM reservas_stock r
         WHERE r.pedido_id = p_pedido_id AND (
           r.estado <> 'EXPIRADA' OR NOT EXISTS (
             SELECT 1 FROM inventario_movimientos im
             WHERE im.reserva_id = r.id AND im.tipo = 'EXPIRACION_RESERVA'
               AND im.delta_fisico = 0 AND im.delta_reservado = -r.cantidad
           )
         )
       ) THEN
      RAISE EXCEPTION 'El pedido expirado % no concilia.', p_pedido_id USING ERRCODE = '23514';
    END IF;
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_pedido_conciliado_trg()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_id BIGINT;
BEGIN
  IF TG_TABLE_NAME = 'pedidos' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
  ELSIF TG_TABLE_NAME IN ('detalle_pedidos', 'reservas_stock') THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.pedido_id ELSE NEW.pedido_id END;
  ELSIF TG_TABLE_NAME = 'inventario_movimientos' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.pedido_id ELSE NEW.pedido_id END;
  ELSIF TG_TABLE_NAME = 'ventas' THEN
    IF TG_OP = 'DELETE' THEN v_id := OLD.pedido_id; ELSE v_id := NEW.pedido_id; END IF;
  END IF;
  PERFORM validar_pedido_conciliado(v_id);
  RETURN NULL;
END
$function$;

CREATE CONSTRAINT TRIGGER pedidos_conciliacion_trg
  AFTER INSERT OR UPDATE ON pedidos DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_pedido_conciliado_trg();
CREATE CONSTRAINT TRIGGER detalle_pedidos_conciliacion_trg
  AFTER INSERT ON detalle_pedidos DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_pedido_conciliado_trg();
CREATE CONSTRAINT TRIGGER reservas_stock_conciliacion_trg
  AFTER INSERT OR UPDATE ON reservas_stock DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_pedido_conciliado_trg();
CREATE CONSTRAINT TRIGGER inventario_pedido_conciliacion_trg
  AFTER INSERT ON inventario_movimientos DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_pedido_conciliado_trg();
CREATE CONSTRAINT TRIGGER ventas_pedido_conciliacion_trg
  AFTER INSERT OR UPDATE OR DELETE ON ventas DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_pedido_conciliado_trg();

CREATE OR REPLACE FUNCTION validar_armado_pedido()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_estado VARCHAR(16);
  v_creado_en TIMESTAMPTZ;
BEGIN
  SELECT estado, creado_en INTO v_estado, v_creado_en
  FROM pedidos WHERE id = NEW.pedido_id FOR KEY SHARE;
  IF NOT FOUND OR v_estado <> 'RESERVADO' OR v_creado_en <> transaction_timestamp() THEN
    RAISE EXCEPTION 'El detalle y las reservas sólo se crean junto con el pedido.'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;
CREATE TRIGGER detalle_pedidos_validar_armado_trg
  BEFORE INSERT ON detalle_pedidos FOR EACH ROW EXECUTE FUNCTION validar_armado_pedido();
CREATE TRIGGER reservas_stock_validar_armado_trg
  BEFORE INSERT ON reservas_stock FOR EACH ROW EXECUTE FUNCTION validar_armado_pedido();
