-- Proveedores y compras sobre la misma existencia física y kardex.
-- Los documentos se publican completos: sus partidas y movimientos son append-only.
-- Una orden PARCIAL puede cancelarse para cerrar el remanente; lo ya recibido
-- permanece en inventario y sólo sale mediante una devolución a proveedor.

CREATE TABLE proveedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(160) NOT NULL,
  razon_social VARCHAR(180),
  rfc VARCHAR(20),
  contacto VARCHAR(120),
  telefono VARCHAR(30),
  email VARCHAR(254),
  direccion TEXT,
  notas TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT proveedores_nombre_check CHECK (btrim(nombre) <> ''),
  CONSTRAINT proveedores_razon_social_check CHECK (
    razon_social IS NULL OR btrim(razon_social) <> ''
  ),
  CONSTRAINT proveedores_rfc_check CHECK (rfc IS NULL OR btrim(rfc) <> ''),
  CONSTRAINT proveedores_contacto_check CHECK (contacto IS NULL OR btrim(contacto) <> ''),
  CONSTRAINT proveedores_telefono_check CHECK (telefono IS NULL OR btrim(telefono) <> ''),
  CONSTRAINT proveedores_email_check CHECK (email IS NULL OR btrim(email) <> ''),
  CONSTRAINT proveedores_direccion_check CHECK (direccion IS NULL OR btrim(direccion) <> '')
);

CREATE UNIQUE INDEX proveedores_nombre_lower_uq ON proveedores (lower(nombre));
CREATE UNIQUE INDEX proveedores_rfc_lower_uq
  ON proveedores (lower(rfc)) WHERE rfc IS NOT NULL;
CREATE INDEX proveedores_activos_nombre_idx
  ON proveedores (nombre, id) WHERE activo;
CREATE INDEX proveedores_creado_por_idx ON proveedores (creado_por_usuario_id);

CREATE TRIGGER proveedores_actualizado_en_trg
  BEFORE UPDATE ON proveedores
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE SEQUENCE ordenes_compra_folio_seq START WITH 1;

CREATE TABLE ordenes_compra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('OC-' || LPAD(nextval('ordenes_compra_folio_seq')::text, 10, '0')),
  proveedor_id BIGINT NOT NULL REFERENCES proveedores(id) ON DELETE RESTRICT,
  proveedor_nombre VARCHAR(160) NOT NULL,
  estado VARCHAR(16) NOT NULL DEFAULT 'EMITIDA',
  referencia VARCHAR(100),
  notas TEXT,
  subtotal NUMERIC(12,2) NOT NULL,
  iva NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ordenes_compra_proveedor_nombre_check CHECK (btrim(proveedor_nombre) <> ''),
  CONSTRAINT ordenes_compra_estado_check CHECK (
    estado IN ('EMITIDA', 'PARCIAL', 'RECIBIDA', 'CANCELADA')
  ),
  CONSTRAINT ordenes_compra_referencia_check CHECK (
    referencia IS NULL OR btrim(referencia) <> ''
  ),
  CONSTRAINT ordenes_compra_subtotal_check CHECK (subtotal >= 0),
  CONSTRAINT ordenes_compra_iva_check CHECK (iva >= 0),
  CONSTRAINT ordenes_compra_total_check CHECK (
    total >= 0 AND total = ROUND(subtotal + iva, 2)
  ),
  CONSTRAINT ordenes_compra_id_proveedor_uq UNIQUE (id, proveedor_id)
);

CREATE INDEX ordenes_compra_proveedor_fecha_idx
  ON ordenes_compra (proveedor_id, creado_en DESC, id DESC);
CREATE INDEX ordenes_compra_estado_fecha_idx
  ON ordenes_compra (estado, creado_en DESC, id DESC);
CREATE INDEX ordenes_compra_usuario_fecha_idx
  ON ordenes_compra (creado_por_usuario_id, creado_en DESC, id DESC);

CREATE TRIGGER ordenes_compra_actualizado_en_trg
  BEFORE UPDATE ON ordenes_compra
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE TABLE detalle_ordenes_compra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_compra_id BIGINT NOT NULL REFERENCES ordenes_compra(id) ON DELETE RESTRICT,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  producto_sku VARCHAR(24) NOT NULL,
  producto_titulo VARCHAR(160) NOT NULL,
  cantidad INTEGER NOT NULL,
  costo_unitario NUMERIC(12,2) NOT NULL,
  iva_porcentaje NUMERIC(5,2) NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL,
  iva NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT detalle_ordenes_compra_sku_check CHECK (btrim(producto_sku) <> ''),
  CONSTRAINT detalle_ordenes_compra_titulo_check CHECK (btrim(producto_titulo) <> ''),
  CONSTRAINT detalle_ordenes_compra_cantidad_check CHECK (cantidad > 0),
  CONSTRAINT detalle_ordenes_compra_costo_check CHECK (costo_unitario >= 0),
  CONSTRAINT detalle_ordenes_compra_iva_porcentaje_check
    CHECK (iva_porcentaje BETWEEN 0 AND 100),
  CONSTRAINT detalle_ordenes_compra_importes_check CHECK (
    subtotal = ROUND(costo_unitario * cantidad, 2)
    AND iva = ROUND(subtotal * iva_porcentaje / 100, 2)
    AND total = ROUND(subtotal + iva, 2)
  ),
  CONSTRAINT detalle_ordenes_compra_orden_producto_uq
    UNIQUE (orden_compra_id, producto_id),
  CONSTRAINT detalle_ordenes_compra_id_orden_producto_uq
    UNIQUE (id, orden_compra_id, producto_id)
);

CREATE INDEX detalle_ordenes_compra_producto_idx
  ON detalle_ordenes_compra (producto_id, orden_compra_id);

CREATE TABLE orden_compra_transiciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_compra_id BIGINT NOT NULL REFERENCES ordenes_compra(id) ON DELETE RESTRICT,
  estado_anterior VARCHAR(16),
  estado_nuevo VARCHAR(16) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(240) NOT NULL,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT orden_compra_transiciones_anterior_check CHECK (
    estado_anterior IS NULL
    OR estado_anterior IN ('EMITIDA', 'PARCIAL', 'RECIBIDA', 'CANCELADA')
  ),
  CONSTRAINT orden_compra_transiciones_nuevo_check CHECK (
    estado_nuevo IN ('EMITIDA', 'PARCIAL', 'RECIBIDA', 'CANCELADA')
  ),
  CONSTRAINT orden_compra_transiciones_cambio_check CHECK (
    (estado_anterior IS NULL AND estado_nuevo = 'EMITIDA')
    OR (estado_anterior IS NOT NULL AND estado_anterior <> estado_nuevo)
  ),
  CONSTRAINT orden_compra_transiciones_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT orden_compra_transiciones_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE INDEX orden_compra_transiciones_orden_idx
  ON orden_compra_transiciones (orden_compra_id, id DESC);

CREATE SEQUENCE recepciones_compra_folio_seq START WITH 1;

CREATE TABLE recepciones_compra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('RC-' || LPAD(nextval('recepciones_compra_folio_seq')::text, 10, '0')),
  orden_compra_id BIGINT NOT NULL,
  proveedor_id BIGINT NOT NULL,
  documento_proveedor VARCHAR(100),
  notas TEXT,
  subtotal NUMERIC(12,2) NOT NULL,
  iva NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  recibido_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT recepciones_compra_orden_proveedor_fk
    FOREIGN KEY (orden_compra_id, proveedor_id)
    REFERENCES ordenes_compra(id, proveedor_id) ON DELETE RESTRICT,
  CONSTRAINT recepciones_compra_documento_check CHECK (
    documento_proveedor IS NULL OR btrim(documento_proveedor) <> ''
  ),
  CONSTRAINT recepciones_compra_subtotal_check CHECK (subtotal >= 0),
  CONSTRAINT recepciones_compra_iva_check CHECK (iva >= 0),
  CONSTRAINT recepciones_compra_total_check CHECK (
    total >= 0 AND total = ROUND(subtotal + iva, 2)
  ),
  CONSTRAINT recepciones_compra_id_orden_proveedor_uq
    UNIQUE (id, orden_compra_id, proveedor_id)
);

CREATE INDEX recepciones_compra_orden_fecha_idx
  ON recepciones_compra (orden_compra_id, creado_en DESC, id DESC);
CREATE INDEX recepciones_compra_proveedor_fecha_idx
  ON recepciones_compra (proveedor_id, creado_en DESC, id DESC);
CREATE INDEX recepciones_compra_documento_idx
  ON recepciones_compra (proveedor_id, documento_proveedor)
  WHERE documento_proveedor IS NOT NULL;

CREATE TABLE detalle_recepciones_compra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recepcion_compra_id BIGINT NOT NULL,
  orden_compra_id BIGINT NOT NULL,
  proveedor_id BIGINT NOT NULL,
  detalle_orden_compra_id BIGINT NOT NULL,
  producto_id INTEGER NOT NULL,
  cantidad INTEGER NOT NULL,
  costo_unitario NUMERIC(12,2) NOT NULL,
  costo_anterior NUMERIC(12,2) NOT NULL,
  costo_nuevo NUMERIC(12,2) NOT NULL,
  iva_porcentaje NUMERIC(5,2) NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL,
  iva NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT detalle_recepciones_compra_cabecera_fk
    FOREIGN KEY (recepcion_compra_id, orden_compra_id, proveedor_id)
    REFERENCES recepciones_compra(id, orden_compra_id, proveedor_id) ON DELETE RESTRICT,
  CONSTRAINT detalle_recepciones_compra_orden_detalle_fk
    FOREIGN KEY (detalle_orden_compra_id, orden_compra_id, producto_id)
    REFERENCES detalle_ordenes_compra(id, orden_compra_id, producto_id) ON DELETE RESTRICT,
  CONSTRAINT detalle_recepciones_compra_cantidad_check CHECK (cantidad > 0),
  CONSTRAINT detalle_recepciones_compra_costo_check CHECK (costo_unitario >= 0),
  CONSTRAINT detalle_recepciones_compra_cambio_costo_check CHECK (
    costo_anterior >= 0 AND costo_nuevo >= 0 AND costo_nuevo = costo_unitario
  ),
  CONSTRAINT detalle_recepciones_compra_iva_porcentaje_check
    CHECK (iva_porcentaje BETWEEN 0 AND 100),
  CONSTRAINT detalle_recepciones_compra_importes_check CHECK (
    subtotal = ROUND(costo_unitario * cantidad, 2)
    AND iva = ROUND(subtotal * iva_porcentaje / 100, 2)
    AND total = ROUND(subtotal + iva, 2)
  ),
  CONSTRAINT detalle_recepciones_compra_recepcion_producto_uq
    UNIQUE (recepcion_compra_id, producto_id),
  CONSTRAINT detalle_recepciones_compra_id_recepcion_producto_uq
    UNIQUE (id, recepcion_compra_id, producto_id),
  CONSTRAINT detalle_recepciones_compra_id_origen_producto_uq
    UNIQUE (id, orden_compra_id, proveedor_id, producto_id)
);

CREATE INDEX detalle_recepciones_compra_orden_detalle_idx
  ON detalle_recepciones_compra (detalle_orden_compra_id, id);
CREATE INDEX detalle_recepciones_compra_producto_idx
  ON detalle_recepciones_compra (producto_id, id DESC);

CREATE SEQUENCE devoluciones_proveedor_folio_seq START WITH 1;

CREATE TABLE devoluciones_proveedor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('DP-' || LPAD(nextval('devoluciones_proveedor_folio_seq')::text, 10, '0')),
  orden_compra_id BIGINT NOT NULL,
  proveedor_id BIGINT NOT NULL,
  motivo VARCHAR(240) NOT NULL,
  referencia VARCHAR(100),
  notas TEXT,
  subtotal NUMERIC(12,2) NOT NULL,
  iva NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT devoluciones_proveedor_orden_proveedor_fk
    FOREIGN KEY (orden_compra_id, proveedor_id)
    REFERENCES ordenes_compra(id, proveedor_id) ON DELETE RESTRICT,
  CONSTRAINT devoluciones_proveedor_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT devoluciones_proveedor_referencia_check CHECK (
    referencia IS NULL OR btrim(referencia) <> ''
  ),
  CONSTRAINT devoluciones_proveedor_subtotal_check CHECK (subtotal >= 0),
  CONSTRAINT devoluciones_proveedor_iva_check CHECK (iva >= 0),
  CONSTRAINT devoluciones_proveedor_total_check CHECK (
    total >= 0 AND total = ROUND(subtotal + iva, 2)
  ),
  CONSTRAINT devoluciones_proveedor_id_orden_proveedor_uq
    UNIQUE (id, orden_compra_id, proveedor_id)
);

CREATE INDEX devoluciones_proveedor_orden_fecha_idx
  ON devoluciones_proveedor (orden_compra_id, creado_en DESC, id DESC);
CREATE INDEX devoluciones_proveedor_proveedor_fecha_idx
  ON devoluciones_proveedor (proveedor_id, creado_en DESC, id DESC);

CREATE TABLE detalle_devoluciones_proveedor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  devolucion_proveedor_id BIGINT NOT NULL,
  orden_compra_id BIGINT NOT NULL,
  proveedor_id BIGINT NOT NULL,
  detalle_recepcion_compra_id BIGINT NOT NULL,
  producto_id INTEGER NOT NULL,
  cantidad INTEGER NOT NULL,
  costo_unitario NUMERIC(12,2) NOT NULL,
  iva_porcentaje NUMERIC(5,2) NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL,
  iva NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT detalle_devoluciones_proveedor_cabecera_fk
    FOREIGN KEY (devolucion_proveedor_id, orden_compra_id, proveedor_id)
    REFERENCES devoluciones_proveedor(id, orden_compra_id, proveedor_id) ON DELETE RESTRICT,
  CONSTRAINT detalle_devoluciones_proveedor_recepcion_fk
    FOREIGN KEY (detalle_recepcion_compra_id, orden_compra_id, proveedor_id, producto_id)
    REFERENCES detalle_recepciones_compra(id, orden_compra_id, proveedor_id, producto_id)
    ON DELETE RESTRICT,
  CONSTRAINT detalle_devoluciones_proveedor_cantidad_check CHECK (cantidad > 0),
  CONSTRAINT detalle_devoluciones_proveedor_costo_check CHECK (costo_unitario >= 0),
  CONSTRAINT detalle_devoluciones_proveedor_iva_porcentaje_check
    CHECK (iva_porcentaje BETWEEN 0 AND 100),
  CONSTRAINT detalle_devoluciones_proveedor_importes_check CHECK (
    subtotal = ROUND(costo_unitario * cantidad, 2)
    AND iva = ROUND(subtotal * iva_porcentaje / 100, 2)
    AND total = ROUND(subtotal + iva, 2)
  ),
  CONSTRAINT detalle_devoluciones_proveedor_origen_uq
    UNIQUE (devolucion_proveedor_id, detalle_recepcion_compra_id),
  CONSTRAINT detalle_devoluciones_proveedor_id_devolucion_producto_uq
    UNIQUE (id, devolucion_proveedor_id, producto_id)
);

CREATE INDEX detalle_devoluciones_proveedor_recepcion_idx
  ON detalle_devoluciones_proveedor (detalle_recepcion_compra_id, id);
CREATE INDEX detalle_devoluciones_proveedor_producto_idx
  ON detalle_devoluciones_proveedor (producto_id, id DESC);

-- Cada entrada/salida de compras conserva su documento y partida exactos.
ALTER TABLE inventario_movimientos
  ADD COLUMN recepcion_compra_id BIGINT,
  ADD COLUMN detalle_recepcion_compra_id BIGINT,
  ADD COLUMN devolucion_proveedor_id BIGINT,
  ADD COLUMN detalle_devolucion_proveedor_id BIGINT;

ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_detalle_recepcion_compra_fk
    FOREIGN KEY (detalle_recepcion_compra_id, recepcion_compra_id, producto_id)
    REFERENCES detalle_recepciones_compra(id, recepcion_compra_id, producto_id)
    ON DELETE RESTRICT,
  ADD CONSTRAINT inventario_movimientos_detalle_devolucion_proveedor_fk
    FOREIGN KEY (detalle_devolucion_proveedor_id, devolucion_proveedor_id, producto_id)
    REFERENCES detalle_devoluciones_proveedor(id, devolucion_proveedor_id, producto_id)
    ON DELETE RESTRICT;

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_tipo_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_tipo_check CHECK (
    tipo IN (
      'INICIAL', 'AJUSTE', 'VENTA', 'CANCELACION', 'DEVOLUCION',
      'RESERVA', 'LIBERACION_RESERVA', 'EXPIRACION_RESERVA', 'CONSUMO_RESERVA',
      'RECEPCION_COMPRA', 'DEVOLUCION_PROVEEDOR'
    )
  );

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_inicial_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_inicial_check CHECK (
    tipo <> 'INICIAL' OR (
      actor = 'MIGRACION' AND usuario_id IS NULL
      AND delta_fisico >= 0 AND delta_reservado >= 0
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
    )
  );

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_ajuste_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_ajuste_check CHECK (
    tipo <> 'AJUSTE' OR (
      actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
      AND delta_fisico <> 0 AND delta_reservado = 0
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
    )
  );

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_origen_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_origen_check CHECK (
    (
      tipo = 'INICIAL'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
    )
    OR (
      tipo = 'AJUSTE'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
    )
    OR (
      tipo = 'VENTA'
      AND venta_id IS NOT NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = 0
    )
    OR (
      tipo = 'CANCELACION'
      AND venta_id IS NULL AND cancelacion_id IS NOT NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
    )
    OR (
      tipo = 'DEVOLUCION'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NOT NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
    )
    OR (
      tipo = 'RESERVA'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND delta_fisico = 0 AND delta_reservado > 0
    )
    OR (
      tipo IN ('LIBERACION_RESERVA', 'EXPIRACION_RESERVA')
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND delta_fisico = 0 AND delta_reservado < 0
    )
    OR (
      tipo = 'CONSUMO_RESERVA'
      AND venta_id IS NOT NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = delta_fisico
    )
    OR (
      tipo = 'RECEPCION_COMPRA'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NOT NULL AND detalle_recepcion_compra_id IS NOT NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'DEVOLUCION_PROVEEDOR'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NOT NULL AND detalle_devolucion_proveedor_id IS NOT NULL
      AND delta_fisico < 0 AND delta_reservado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
  );

CREATE UNIQUE INDEX inventario_movimientos_recepcion_detalle_uq
  ON inventario_movimientos (detalle_recepcion_compra_id)
  WHERE tipo = 'RECEPCION_COMPRA';
CREATE UNIQUE INDEX inventario_movimientos_devolucion_proveedor_detalle_uq
  ON inventario_movimientos (detalle_devolucion_proveedor_id)
  WHERE tipo = 'DEVOLUCION_PROVEEDOR';
CREATE INDEX inventario_movimientos_recepcion_compra_idx
  ON inventario_movimientos (recepcion_compra_id, id)
  WHERE recepcion_compra_id IS NOT NULL;
CREATE INDEX inventario_movimientos_devolucion_proveedor_idx
  ON inventario_movimientos (devolucion_proveedor_id, id)
  WHERE devolucion_proveedor_id IS NOT NULL;

-- Protección append-only de documentos y partidas.
CREATE OR REPLACE FUNCTION proteger_orden_compra()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Las órdenes de compra son auditables y no pueden eliminarse.'
      USING ERRCODE = '55000';
  END IF;
  IF ROW(
    NEW.id, NEW.folio, NEW.proveedor_id, NEW.proveedor_nombre, NEW.referencia,
    NEW.notas, NEW.subtotal, NEW.iva, NEW.total, NEW.creado_por_usuario_id,
    NEW.creado_en
  ) IS DISTINCT FROM ROW(
    OLD.id, OLD.folio, OLD.proveedor_id, OLD.proveedor_nombre, OLD.referencia,
    OLD.notas, OLD.subtotal, OLD.iva, OLD.total, OLD.creado_por_usuario_id,
    OLD.creado_en
  ) THEN
    RAISE EXCEPTION 'El contenido comercial de una orden de compra es inmutable.'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER ordenes_compra_proteger_snapshot_trg
  BEFORE UPDATE OR DELETE ON ordenes_compra
  FOR EACH ROW EXECUTE FUNCTION proteger_orden_compra();

CREATE OR REPLACE FUNCTION proteger_estado_orden_compra()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.estado IS DISTINCT FROM OLD.estado
     AND COALESCE(current_setting('libra.aplicando_transicion_orden_compra', TRUE), '') <> '1' THEN
    RAISE EXCEPTION 'El estado sólo cambia mediante orden_compra_transiciones.'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER ordenes_compra_proteger_estado_trg
  BEFORE UPDATE OF estado ON ordenes_compra
  FOR EACH ROW EXECUTE FUNCTION proteger_estado_orden_compra();

CREATE OR REPLACE FUNCTION impedir_mutacion_documento_compra()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  RAISE EXCEPTION '% es auditable; no se permite %.', TG_TABLE_NAME, TG_OP
    USING ERRCODE = '55000';
END
$function$;

CREATE TRIGGER detalle_ordenes_compra_inmutable_trg
  BEFORE UPDATE OR DELETE ON detalle_ordenes_compra
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_documento_compra();
CREATE TRIGGER orden_compra_transiciones_inmutable_trg
  BEFORE UPDATE OR DELETE ON orden_compra_transiciones
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_documento_compra();
CREATE TRIGGER recepciones_compra_inmutable_trg
  BEFORE UPDATE OR DELETE ON recepciones_compra
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_documento_compra();
CREATE TRIGGER detalle_recepciones_compra_inmutable_trg
  BEFORE UPDATE OR DELETE ON detalle_recepciones_compra
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_documento_compra();
CREATE TRIGGER devoluciones_proveedor_inmutable_trg
  BEFORE UPDATE OR DELETE ON devoluciones_proveedor
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_documento_compra();
CREATE TRIGGER detalle_devoluciones_proveedor_inmutable_trg
  BEFORE UPDATE OR DELETE ON detalle_devoluciones_proveedor
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_documento_compra();

-- Las partidas sólo pueden armarse en la misma transacción que su cabecera.
CREATE OR REPLACE FUNCTION validar_armado_documento_compra()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_creado_en TIMESTAMPTZ;
BEGIN
  IF TG_TABLE_NAME = 'detalle_ordenes_compra' THEN
    SELECT creado_en INTO v_creado_en
    FROM ordenes_compra WHERE id = NEW.orden_compra_id FOR KEY SHARE;
  ELSIF TG_TABLE_NAME = 'detalle_recepciones_compra' THEN
    SELECT creado_en INTO v_creado_en
    FROM recepciones_compra WHERE id = NEW.recepcion_compra_id FOR KEY SHARE;
  ELSE
    SELECT creado_en INTO v_creado_en
    FROM devoluciones_proveedor WHERE id = NEW.devolucion_proveedor_id FOR KEY SHARE;
  END IF;

  IF NOT FOUND OR v_creado_en <> transaction_timestamp() THEN
    RAISE EXCEPTION 'Las partidas sólo se crean junto con su documento.'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER detalle_ordenes_compra_validar_armado_trg
  BEFORE INSERT ON detalle_ordenes_compra
  FOR EACH ROW EXECUTE FUNCTION validar_armado_documento_compra();
CREATE TRIGGER detalle_recepciones_compra_validar_armado_trg
  BEFORE INSERT ON detalle_recepciones_compra
  FOR EACH ROW EXECUTE FUNCTION validar_armado_documento_compra();
CREATE TRIGGER detalle_devoluciones_proveedor_validar_armado_trg
  BEFORE INSERT ON detalle_devoluciones_proveedor
  FOR EACH ROW EXECUTE FUNCTION validar_armado_documento_compra();

CREATE OR REPLACE FUNCTION validar_creacion_recepcion_compra()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_estado VARCHAR(16);
BEGIN
  SELECT estado INTO v_estado
  FROM ordenes_compra
  WHERE id = NEW.orden_compra_id AND proveedor_id = NEW.proveedor_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Orden de compra o proveedor inválido.' USING ERRCODE = '23503';
  END IF;
  IF v_estado NOT IN ('EMITIDA', 'PARCIAL') THEN
    RAISE EXCEPTION 'La orden % no admite recepciones en estado %.', NEW.orden_compra_id, v_estado
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER recepciones_compra_validar_creacion_trg
  BEFORE INSERT ON recepciones_compra
  FOR EACH ROW EXECUTE FUNCTION validar_creacion_recepcion_compra();

-- Último costo realmente recibido. El detalle inmutable conserva la evidencia.
CREATE OR REPLACE FUNCTION aplicar_ultimo_costo_recibido()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_costo_actual NUMERIC(12,2);
BEGIN
  SELECT costo INTO v_costo_actual
  FROM productos WHERE id = NEW.producto_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Producto % no encontrado.', NEW.producto_id USING ERRCODE = '23503';
  END IF;
  IF NEW.costo_anterior <> v_costo_actual THEN
    RAISE EXCEPTION 'El costo anterior de producto % cambió concurrentemente.', NEW.producto_id
      USING ERRCODE = '40001';
  END IF;
  UPDATE productos
  SET costo = NEW.costo_nuevo, actualizado_en = NOW()
  WHERE id = NEW.producto_id;
  RETURN NEW;
END
$function$;

CREATE TRIGGER detalle_recepciones_compra_aplicar_costo_trg
  BEFORE INSERT ON detalle_recepciones_compra
  FOR EACH ROW EXECUTE FUNCTION aplicar_ultimo_costo_recibido();

-- Historial de estados append-only.
CREATE OR REPLACE FUNCTION validar_insert_transicion_orden_compra()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_estado VARCHAR(16);
BEGIN
  SELECT estado INTO v_estado FROM ordenes_compra
  WHERE id = NEW.orden_compra_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Orden de compra % no encontrada.', NEW.orden_compra_id
      USING ERRCODE = '23503';
  END IF;

  IF NEW.estado_anterior IS NULL THEN
    IF v_estado <> 'EMITIDA' OR NEW.estado_nuevo <> 'EMITIDA'
       OR EXISTS (
         SELECT 1 FROM orden_compra_transiciones
         WHERE orden_compra_id = NEW.orden_compra_id
       ) THEN
      RAISE EXCEPTION 'Transición inicial de orden de compra inválida.'
        USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
  END IF;

  IF v_estado <> NEW.estado_anterior THEN
    RAISE EXCEPTION 'La orden está en %, no en %.', v_estado, NEW.estado_anterior
      USING ERRCODE = '40001';
  END IF;
  IF NOT (
    (NEW.estado_anterior = 'EMITIDA'
      AND NEW.estado_nuevo IN ('PARCIAL', 'RECIBIDA', 'CANCELADA'))
    OR (NEW.estado_anterior = 'PARCIAL'
      AND NEW.estado_nuevo IN ('RECIBIDA', 'CANCELADA'))
  ) THEN
    RAISE EXCEPTION 'Transición de orden no permitida: % -> %.',
      NEW.estado_anterior, NEW.estado_nuevo USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER orden_compra_transiciones_validar_trg
  BEFORE INSERT ON orden_compra_transiciones
  FOR EACH ROW EXECUTE FUNCTION validar_insert_transicion_orden_compra();

CREATE OR REPLACE FUNCTION aplicar_transicion_orden_compra()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_actualizados INTEGER;
BEGIN
  IF NEW.estado_anterior IS NULL THEN RETURN NULL; END IF;
  PERFORM set_config('libra.aplicando_transicion_orden_compra', '1', TRUE);
  UPDATE ordenes_compra SET estado = NEW.estado_nuevo
  WHERE id = NEW.orden_compra_id AND estado = NEW.estado_anterior;
  GET DIAGNOSTICS v_actualizados = ROW_COUNT;
  PERFORM set_config('libra.aplicando_transicion_orden_compra', '0', TRUE);
  IF v_actualizados <> 1 THEN
    RAISE EXCEPTION 'La orden de compra cambió concurrentemente.' USING ERRCODE = '40001';
  END IF;
  RETURN NULL;
END
$function$;

CREATE TRIGGER orden_compra_transiciones_aplicar_trg
  AFTER INSERT ON orden_compra_transiciones
  FOR EACH ROW EXECUTE FUNCTION aplicar_transicion_orden_compra();

CREATE OR REPLACE FUNCTION registrar_creacion_orden_compra()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.estado <> 'EMITIDA' THEN
    RAISE EXCEPTION 'Toda orden de compra debe iniciar EMITIDA.' USING ERRCODE = '23514';
  END IF;
  INSERT INTO orden_compra_transiciones (
    orden_compra_id, estado_anterior, estado_nuevo, usuario_id,
    motivo, origen_clave, creado_en
  ) VALUES (
    NEW.id, NULL, 'EMITIDA', NEW.creado_por_usuario_id,
    'Creación de la orden de compra.',
    'ORDEN_COMPRA:' || NEW.id::text || ':CREACION', NEW.creado_en
  );
  RETURN NULL;
END
$function$;

CREATE TRIGGER ordenes_compra_registrar_creacion_trg
  AFTER INSERT ON ordenes_compra
  FOR EACH ROW EXECUTE FUNCTION registrar_creacion_orden_compra();

-- Conciliación diferida de orden, recepciones, devoluciones y kardex.
CREATE OR REPLACE FUNCTION validar_orden_compra_conciliada(p_orden_id BIGINT)
RETURNS VOID LANGUAGE plpgsql AS $function$
DECLARE
  v_orden ordenes_compra%ROWTYPE;
  v_lineas BIGINT;
  v_subtotal NUMERIC(12,2);
  v_iva NUMERIC(12,2);
  v_total NUMERIC(12,2);
  v_recibido BIGINT;
  v_ultimo_estado VARCHAR(16);
  v_hay_remanente BOOLEAN;
BEGIN
  IF p_orden_id IS NULL THEN RETURN; END IF;
  SELECT * INTO v_orden FROM ordenes_compra WHERE id = p_orden_id;
  IF NOT FOUND THEN RETURN; END IF;

  SELECT COUNT(*), ROUND(COALESCE(SUM(subtotal), 0), 2),
         ROUND(COALESCE(SUM(iva), 0), 2), ROUND(COALESCE(SUM(total), 0), 2)
  INTO v_lineas, v_subtotal, v_iva, v_total
  FROM detalle_ordenes_compra WHERE orden_compra_id = p_orden_id;
  IF v_lineas = 0 THEN
    RAISE EXCEPTION 'La orden de compra % no contiene partidas.', p_orden_id
      USING ERRCODE = '23514';
  END IF;
  IF v_subtotal <> v_orden.subtotal OR v_iva <> v_orden.iva OR v_total <> v_orden.total THEN
    RAISE EXCEPTION 'Los totales de la orden de compra % no concilian.', p_orden_id
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM detalle_ordenes_compra d
    LEFT JOIN (
      SELECT detalle_orden_compra_id, SUM(cantidad)::BIGINT AS cantidad
      FROM detalle_recepciones_compra GROUP BY detalle_orden_compra_id
    ) r ON r.detalle_orden_compra_id = d.id
    WHERE d.orden_compra_id = p_orden_id
      AND COALESCE(r.cantidad, 0) > d.cantidad
  ) THEN
    RAISE EXCEPTION 'La orden de compra % tiene cantidades recibidas en exceso.', p_orden_id
      USING ERRCODE = '23514';
  END IF;

  SELECT COALESCE(SUM(r.cantidad), 0)::BIGINT,
         COALESCE(BOOL_OR(COALESCE(r.cantidad, 0) < d.cantidad), FALSE)
  INTO v_recibido, v_hay_remanente
  FROM detalle_ordenes_compra d
  LEFT JOIN (
    SELECT detalle_orden_compra_id, SUM(cantidad)::BIGINT AS cantidad
    FROM detalle_recepciones_compra GROUP BY detalle_orden_compra_id
  ) r ON r.detalle_orden_compra_id = d.id
  WHERE d.orden_compra_id = p_orden_id;

  IF v_orden.estado = 'EMITIDA' AND v_recibido <> 0 THEN
    RAISE EXCEPTION 'Una orden EMITIDA no puede tener recepciones.' USING ERRCODE = '23514';
  ELSIF v_orden.estado = 'PARCIAL' AND (v_recibido = 0 OR NOT v_hay_remanente) THEN
    RAISE EXCEPTION 'El estado PARCIAL no corresponde a las recepciones.' USING ERRCODE = '23514';
  ELSIF v_orden.estado = 'RECIBIDA' AND (v_recibido = 0 OR v_hay_remanente) THEN
    RAISE EXCEPTION 'El estado RECIBIDA no corresponde a las recepciones.' USING ERRCODE = '23514';
  ELSIF v_orden.estado = 'CANCELADA' AND NOT v_hay_remanente THEN
    RAISE EXCEPTION 'Una orden totalmente recibida no puede cancelarse.' USING ERRCODE = '23514';
  END IF;

  SELECT estado_nuevo INTO v_ultimo_estado
  FROM orden_compra_transiciones
  WHERE orden_compra_id = p_orden_id ORDER BY id DESC LIMIT 1;
  IF v_ultimo_estado IS DISTINCT FROM v_orden.estado THEN
    RAISE EXCEPTION 'El historial de la orden % no concilia con su estado.', p_orden_id
      USING ERRCODE = '23514';
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_recepcion_compra_conciliada(p_recepcion_id BIGINT)
RETURNS VOID LANGUAGE plpgsql AS $function$
DECLARE
  v_recepcion recepciones_compra%ROWTYPE;
  v_lineas BIGINT;
  v_subtotal NUMERIC(12,2);
  v_iva NUMERIC(12,2);
  v_total NUMERIC(12,2);
BEGIN
  IF p_recepcion_id IS NULL THEN RETURN; END IF;
  SELECT * INTO v_recepcion FROM recepciones_compra WHERE id = p_recepcion_id;
  IF NOT FOUND THEN RETURN; END IF;

  SELECT COUNT(*), ROUND(COALESCE(SUM(subtotal), 0), 2),
         ROUND(COALESCE(SUM(iva), 0), 2), ROUND(COALESCE(SUM(total), 0), 2)
  INTO v_lineas, v_subtotal, v_iva, v_total
  FROM detalle_recepciones_compra WHERE recepcion_compra_id = p_recepcion_id;
  IF v_lineas = 0 THEN
    RAISE EXCEPTION 'La recepción % no contiene partidas.', p_recepcion_id
      USING ERRCODE = '23514';
  END IF;
  IF v_subtotal <> v_recepcion.subtotal OR v_iva <> v_recepcion.iva
     OR v_total <> v_recepcion.total THEN
    RAISE EXCEPTION 'Los totales de la recepción % no concilian.', p_recepcion_id
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM detalle_recepciones_compra d
    LEFT JOIN inventario_movimientos im
      ON im.detalle_recepcion_compra_id = d.id AND im.tipo = 'RECEPCION_COMPRA'
    WHERE d.recepcion_compra_id = p_recepcion_id
      AND (
        im.id IS NULL OR im.recepcion_compra_id <> d.recepcion_compra_id
        OR im.producto_id <> d.producto_id OR im.delta_fisico <> d.cantidad
        OR im.delta_reservado <> 0 OR im.actor <> 'USUARIO'
        OR im.usuario_id <> v_recepcion.recibido_por_usuario_id
      )
  ) THEN
    RAISE EXCEPTION 'La recepción % no concilia con el kardex.', p_recepcion_id
      USING ERRCODE = '23514';
  END IF;
  PERFORM validar_orden_compra_conciliada(v_recepcion.orden_compra_id);
END
$function$;

CREATE OR REPLACE FUNCTION validar_devolucion_proveedor_conciliada(p_devolucion_id BIGINT)
RETURNS VOID LANGUAGE plpgsql AS $function$
DECLARE
  v_devolucion devoluciones_proveedor%ROWTYPE;
  v_lineas BIGINT;
  v_subtotal NUMERIC(12,2);
  v_iva NUMERIC(12,2);
  v_total NUMERIC(12,2);
BEGIN
  IF p_devolucion_id IS NULL THEN RETURN; END IF;
  SELECT * INTO v_devolucion FROM devoluciones_proveedor WHERE id = p_devolucion_id;
  IF NOT FOUND THEN RETURN; END IF;

  SELECT COUNT(*), ROUND(COALESCE(SUM(subtotal), 0), 2),
         ROUND(COALESCE(SUM(iva), 0), 2), ROUND(COALESCE(SUM(total), 0), 2)
  INTO v_lineas, v_subtotal, v_iva, v_total
  FROM detalle_devoluciones_proveedor WHERE devolucion_proveedor_id = p_devolucion_id;
  IF v_lineas = 0 THEN
    RAISE EXCEPTION 'La devolución a proveedor % no contiene partidas.', p_devolucion_id
      USING ERRCODE = '23514';
  END IF;
  IF v_subtotal <> v_devolucion.subtotal OR v_iva <> v_devolucion.iva
     OR v_total <> v_devolucion.total THEN
    RAISE EXCEPTION 'Los totales de la devolución % no concilian.', p_devolucion_id
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM detalle_devoluciones_proveedor d
    JOIN detalle_recepciones_compra r ON r.id = d.detalle_recepcion_compra_id
    WHERE d.devolucion_proveedor_id = p_devolucion_id
      AND (d.costo_unitario <> r.costo_unitario OR d.iva_porcentaje <> r.iva_porcentaje)
  ) THEN
    RAISE EXCEPTION 'La devolución % alteró el costo o IVA recibido.', p_devolucion_id
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM detalle_recepciones_compra r
    JOIN (
      SELECT detalle_recepcion_compra_id, SUM(cantidad)::BIGINT AS cantidad
      FROM detalle_devoluciones_proveedor GROUP BY detalle_recepcion_compra_id
    ) d ON d.detalle_recepcion_compra_id = r.id
    WHERE d.cantidad > r.cantidad
  ) THEN
    RAISE EXCEPTION 'La devolución % excede la cantidad recibida.', p_devolucion_id
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM detalle_devoluciones_proveedor d
    LEFT JOIN inventario_movimientos im
      ON im.detalle_devolucion_proveedor_id = d.id
      AND im.tipo = 'DEVOLUCION_PROVEEDOR'
    WHERE d.devolucion_proveedor_id = p_devolucion_id
      AND (
        im.id IS NULL OR im.devolucion_proveedor_id <> d.devolucion_proveedor_id
        OR im.producto_id <> d.producto_id OR im.delta_fisico <> -d.cantidad
        OR im.delta_reservado <> 0 OR im.actor <> 'USUARIO'
        OR im.usuario_id <> v_devolucion.creado_por_usuario_id
      )
  ) THEN
    RAISE EXCEPTION 'La devolución % no concilia con el kardex.', p_devolucion_id
      USING ERRCODE = '23514';
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_orden_compra_conciliada_trg()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_id BIGINT;
BEGIN
  IF TG_TABLE_NAME = 'ordenes_compra' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
  ELSIF TG_TABLE_NAME = 'detalle_ordenes_compra' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.orden_compra_id ELSE NEW.orden_compra_id END;
  ELSIF TG_TABLE_NAME = 'orden_compra_transiciones' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.orden_compra_id ELSE NEW.orden_compra_id END;
  ELSE
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.orden_compra_id ELSE NEW.orden_compra_id END;
  END IF;
  PERFORM validar_orden_compra_conciliada(v_id);
  RETURN NULL;
END
$function$;

CREATE OR REPLACE FUNCTION validar_recepcion_compra_conciliada_trg()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_id BIGINT;
BEGIN
  IF TG_TABLE_NAME = 'recepciones_compra' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
  ELSIF TG_TABLE_NAME = 'detalle_recepciones_compra' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.recepcion_compra_id ELSE NEW.recepcion_compra_id END;
  ELSE
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.recepcion_compra_id ELSE NEW.recepcion_compra_id END;
  END IF;
  PERFORM validar_recepcion_compra_conciliada(v_id);
  RETURN NULL;
END
$function$;

CREATE OR REPLACE FUNCTION validar_devolucion_proveedor_conciliada_trg()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
DECLARE
  v_id BIGINT;
BEGIN
  IF TG_TABLE_NAME = 'devoluciones_proveedor' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
  ELSIF TG_TABLE_NAME = 'detalle_devoluciones_proveedor' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.devolucion_proveedor_id ELSE NEW.devolucion_proveedor_id END;
  ELSE
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.devolucion_proveedor_id ELSE NEW.devolucion_proveedor_id END;
  END IF;
  PERFORM validar_devolucion_proveedor_conciliada(v_id);
  RETURN NULL;
END
$function$;

CREATE CONSTRAINT TRIGGER ordenes_compra_conciliacion_trg
  AFTER INSERT OR UPDATE ON ordenes_compra DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_orden_compra_conciliada_trg();
CREATE CONSTRAINT TRIGGER detalle_ordenes_compra_conciliacion_trg
  AFTER INSERT ON detalle_ordenes_compra DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_orden_compra_conciliada_trg();
CREATE CONSTRAINT TRIGGER orden_compra_transiciones_conciliacion_trg
  AFTER INSERT ON orden_compra_transiciones DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_orden_compra_conciliada_trg();
CREATE CONSTRAINT TRIGGER detalle_recepciones_orden_conciliacion_trg
  AFTER INSERT ON detalle_recepciones_compra DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_orden_compra_conciliada_trg();

CREATE CONSTRAINT TRIGGER recepciones_compra_conciliacion_trg
  AFTER INSERT ON recepciones_compra DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_recepcion_compra_conciliada_trg();
CREATE CONSTRAINT TRIGGER detalle_recepciones_compra_conciliacion_trg
  AFTER INSERT ON detalle_recepciones_compra DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_recepcion_compra_conciliada_trg();

CREATE CONSTRAINT TRIGGER devoluciones_proveedor_conciliacion_trg
  AFTER INSERT ON devoluciones_proveedor DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_devolucion_proveedor_conciliada_trg();
CREATE CONSTRAINT TRIGGER detalle_devoluciones_proveedor_conciliacion_trg
  AFTER INSERT ON detalle_devoluciones_proveedor DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_devolucion_proveedor_conciliada_trg();

CREATE CONSTRAINT TRIGGER inventario_recepcion_compra_conciliacion_trg
  AFTER INSERT ON inventario_movimientos DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  WHEN (NEW.recepcion_compra_id IS NOT NULL)
  EXECUTE FUNCTION validar_recepcion_compra_conciliada_trg();
CREATE CONSTRAINT TRIGGER inventario_devolucion_proveedor_conciliacion_trg
  AFTER INSERT ON inventario_movimientos DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  WHEN (NEW.devolucion_proveedor_id IS NOT NULL)
  EXECUTE FUNCTION validar_devolucion_proveedor_conciliada_trg();
