-- Reposición y conteos para una sola existencia omnicanal.
-- Las sugerencias consideran stock disponible y órdenes de compra en tránsito.
-- Un conteo sólo puede aplicarse si ningún movimiento ocurrió después de su captura.

CREATE TABLE politicas_reposicion (
  producto_id INTEGER PRIMARY KEY REFERENCES productos(id) ON DELETE RESTRICT,
  stock_minimo INTEGER NOT NULL DEFAULT 0,
  stock_objetivo INTEGER NOT NULL DEFAULT 0,
  proveedor_preferido_id BIGINT REFERENCES proveedores(id) ON DELETE RESTRICT,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  actualizado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT politicas_reposicion_minimo_check CHECK (
    stock_minimo BETWEEN 0 AND 1000000
  ),
  CONSTRAINT politicas_reposicion_objetivo_check CHECK (
    stock_objetivo BETWEEN stock_minimo AND 1000000
  )
);

CREATE INDEX politicas_reposicion_proveedor_idx
  ON politicas_reposicion (proveedor_preferido_id, producto_id)
  WHERE proveedor_preferido_id IS NOT NULL;

CREATE TABLE politicas_reposicion_historial (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  stock_minimo_anterior INTEGER,
  stock_objetivo_anterior INTEGER,
  proveedor_anterior_id BIGINT REFERENCES proveedores(id) ON DELETE RESTRICT,
  stock_minimo_nuevo INTEGER NOT NULL,
  stock_objetivo_nuevo INTEGER NOT NULL,
  proveedor_nuevo_id BIGINT REFERENCES proveedores(id) ON DELETE RESTRICT,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(240) NOT NULL,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT politicas_reposicion_historial_anterior_check CHECK (
    (stock_minimo_anterior IS NULL AND stock_objetivo_anterior IS NULL)
    OR (
      stock_minimo_anterior BETWEEN 0 AND 1000000
      AND stock_objetivo_anterior BETWEEN stock_minimo_anterior AND 1000000
    )
  ),
  CONSTRAINT politicas_reposicion_historial_nuevo_check CHECK (
    stock_minimo_nuevo BETWEEN 0 AND 1000000
    AND stock_objetivo_nuevo BETWEEN stock_minimo_nuevo AND 1000000
  ),
  CONSTRAINT politicas_reposicion_historial_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT politicas_reposicion_historial_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE INDEX politicas_reposicion_historial_producto_idx
  ON politicas_reposicion_historial (producto_id, id DESC);

CREATE SEQUENCE conteos_inventario_folio_seq START WITH 1;

CREATE TABLE conteos_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('CI-' || LPAD(nextval('conteos_inventario_folio_seq')::text, 10, '0')),
  estado VARCHAR(12) NOT NULL DEFAULT 'BORRADOR',
  notas TEXT,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  aplicado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  aplicado_en TIMESTAMPTZ,
  cancelado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  cancelado_en TIMESTAMPTZ,
  cancelacion_motivo VARCHAR(240),
  CONSTRAINT conteos_inventario_estado_check CHECK (
    estado IN ('BORRADOR', 'APLICADO', 'CANCELADO')
  ),
  CONSTRAINT conteos_inventario_notas_check CHECK (
    notas IS NULL OR btrim(notas) <> ''
  ),
  CONSTRAINT conteos_inventario_estado_datos_check CHECK (
    (
      estado = 'BORRADOR'
      AND aplicado_por_usuario_id IS NULL AND aplicado_en IS NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado = 'APLICADO'
      AND aplicado_por_usuario_id IS NOT NULL AND aplicado_en IS NOT NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado = 'CANCELADO'
      AND aplicado_por_usuario_id IS NULL AND aplicado_en IS NULL
      AND cancelado_por_usuario_id IS NOT NULL AND cancelado_en IS NOT NULL
      AND btrim(COALESCE(cancelacion_motivo, '')) <> ''
    )
  )
);

CREATE INDEX conteos_inventario_estado_fecha_idx
  ON conteos_inventario (estado, creado_en DESC, id DESC);
CREATE INDEX conteos_inventario_usuario_fecha_idx
  ON conteos_inventario (creado_por_usuario_id, creado_en DESC, id DESC);

ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_id_producto_uq UNIQUE (id, producto_id);

CREATE TABLE detalle_conteos_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conteo_inventario_id BIGINT NOT NULL REFERENCES conteos_inventario(id) ON DELETE RESTRICT,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  producto_sku VARCHAR(24) NOT NULL,
  producto_titulo VARCHAR(160) NOT NULL,
  stock_fisico_al_abrir INTEGER NOT NULL,
  stock_reservado_al_abrir INTEGER NOT NULL,
  movimiento_al_abrir_id BIGINT,
  captura_aplicada_id BIGINT,
  diferencia_aplicada INTEGER,
  stock_fisico_aplicado INTEGER,
  stock_reservado_aplicado INTEGER,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT detalle_conteos_inventario_sku_check CHECK (btrim(producto_sku) <> ''),
  CONSTRAINT detalle_conteos_inventario_titulo_check CHECK (btrim(producto_titulo) <> ''),
  CONSTRAINT detalle_conteos_inventario_saldos_check CHECK (
    stock_fisico_al_abrir >= 0
    AND stock_reservado_al_abrir BETWEEN 0 AND stock_fisico_al_abrir
  ),
  CONSTRAINT detalle_conteos_inventario_movimiento_base_fk
    FOREIGN KEY (movimiento_al_abrir_id, producto_id)
    REFERENCES inventario_movimientos(id, producto_id) ON DELETE RESTRICT,
  CONSTRAINT detalle_conteos_inventario_aplicacion_check CHECK (
    (
      captura_aplicada_id IS NULL AND diferencia_aplicada IS NULL
      AND stock_fisico_aplicado IS NULL AND stock_reservado_aplicado IS NULL
    )
    OR (
      captura_aplicada_id IS NOT NULL AND diferencia_aplicada IS NOT NULL
      AND stock_fisico_aplicado >= 0
      AND stock_reservado_aplicado BETWEEN 0 AND stock_fisico_aplicado
    )
  ),
  CONSTRAINT detalle_conteos_inventario_conteo_producto_uq
    UNIQUE (conteo_inventario_id, producto_id),
  CONSTRAINT detalle_conteos_inventario_id_conteo_producto_uq
    UNIQUE (id, conteo_inventario_id, producto_id)
);

CREATE INDEX detalle_conteos_inventario_producto_idx
  ON detalle_conteos_inventario (producto_id, conteo_inventario_id DESC);

CREATE TABLE capturas_conteo_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conteo_inventario_id BIGINT NOT NULL,
  detalle_conteo_inventario_id BIGINT NOT NULL,
  producto_id INTEGER NOT NULL,
  cantidad_contada INTEGER NOT NULL,
  stock_fisico_base INTEGER NOT NULL,
  stock_reservado_base INTEGER NOT NULL,
  movimiento_base_id BIGINT,
  capturado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT capturas_conteo_inventario_detalle_fk
    FOREIGN KEY (detalle_conteo_inventario_id, conteo_inventario_id, producto_id)
    REFERENCES detalle_conteos_inventario(id, conteo_inventario_id, producto_id)
    ON DELETE RESTRICT,
  CONSTRAINT capturas_conteo_inventario_cantidad_check CHECK (
    cantidad_contada BETWEEN 0 AND 1000000
  ),
  CONSTRAINT capturas_conteo_inventario_saldos_check CHECK (
    stock_fisico_base >= 0
    AND stock_reservado_base BETWEEN 0 AND stock_fisico_base
  ),
  CONSTRAINT capturas_conteo_inventario_movimiento_base_fk
    FOREIGN KEY (movimiento_base_id, producto_id)
    REFERENCES inventario_movimientos(id, producto_id) ON DELETE RESTRICT,
  CONSTRAINT capturas_conteo_inventario_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE INDEX capturas_conteo_inventario_detalle_idx
  ON capturas_conteo_inventario (detalle_conteo_inventario_id, id DESC);
CREATE INDEX capturas_conteo_inventario_conteo_idx
  ON capturas_conteo_inventario (conteo_inventario_id, id DESC);

ALTER TABLE detalle_conteos_inventario
  ADD CONSTRAINT detalle_conteos_inventario_captura_aplicada_fk
  FOREIGN KEY (captura_aplicada_id)
  REFERENCES capturas_conteo_inventario(id) ON DELETE RESTRICT;

CREATE TABLE conteo_inventario_transiciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conteo_inventario_id BIGINT NOT NULL REFERENCES conteos_inventario(id) ON DELETE RESTRICT,
  estado_anterior VARCHAR(12),
  estado_nuevo VARCHAR(12) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(240) NOT NULL,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT conteo_inventario_transiciones_anterior_check CHECK (
    estado_anterior IS NULL OR estado_anterior IN ('BORRADOR', 'APLICADO', 'CANCELADO')
  ),
  CONSTRAINT conteo_inventario_transiciones_nuevo_check CHECK (
    estado_nuevo IN ('BORRADOR', 'APLICADO', 'CANCELADO')
  ),
  CONSTRAINT conteo_inventario_transiciones_cambio_check CHECK (
    (estado_anterior IS NULL AND estado_nuevo = 'BORRADOR')
    OR (estado_anterior = 'BORRADOR' AND estado_nuevo IN ('APLICADO', 'CANCELADO'))
  ),
  CONSTRAINT conteo_inventario_transiciones_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT conteo_inventario_transiciones_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE INDEX conteo_inventario_transiciones_conteo_idx
  ON conteo_inventario_transiciones (conteo_inventario_id, id DESC);

ALTER TABLE inventario_movimientos
  ADD COLUMN conteo_inventario_id BIGINT,
  ADD COLUMN detalle_conteo_inventario_id BIGINT;

ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_detalle_conteo_fk
    FOREIGN KEY (detalle_conteo_inventario_id, conteo_inventario_id, producto_id)
    REFERENCES detalle_conteos_inventario(id, conteo_inventario_id, producto_id)
    ON DELETE RESTRICT;

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_tipo_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_tipo_check CHECK (
    tipo IN (
      'INICIAL', 'AJUSTE', 'VENTA', 'CANCELACION', 'DEVOLUCION',
      'RESERVA', 'LIBERACION_RESERVA', 'EXPIRACION_RESERVA', 'CONSUMO_RESERVA',
      'RECEPCION_COMPRA', 'DEVOLUCION_PROVEEDOR', 'CONTEO'
    )
  );

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_inicial_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_inicial_check CHECK (
    tipo <> 'INICIAL' OR (
      actor = 'MIGRACION' AND usuario_id IS NULL
      AND delta_fisico >= 0 AND delta_reservado >= 0
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
    )
  );

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_ajuste_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_ajuste_check CHECK (
    tipo <> 'AJUSTE' OR (
      actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
      AND delta_fisico <> 0 AND delta_reservado = 0
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
    )
  );

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_origen_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_origen_check CHECK (
    (
      tipo = 'INICIAL'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
    )
    OR (
      tipo = 'AJUSTE'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
    )
    OR (
      tipo = 'VENTA'
      AND venta_id IS NOT NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = 0
    )
    OR (
      tipo = 'CANCELACION'
      AND venta_id IS NULL AND cancelacion_id IS NOT NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
    )
    OR (
      tipo = 'DEVOLUCION'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NOT NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
    )
    OR (
      tipo = 'RESERVA'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico = 0 AND delta_reservado > 0
    )
    OR (
      tipo IN ('LIBERACION_RESERVA', 'EXPIRACION_RESERVA')
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico = 0 AND delta_reservado < 0
    )
    OR (
      tipo = 'CONSUMO_RESERVA'
      AND venta_id IS NOT NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = delta_fisico
    )
    OR (
      tipo = 'RECEPCION_COMPRA'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NOT NULL AND detalle_recepcion_compra_id IS NOT NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'DEVOLUCION_PROVEEDOR'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NOT NULL AND detalle_devolucion_proveedor_id IS NOT NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'CONTEO'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NOT NULL AND detalle_conteo_inventario_id IS NOT NULL
      AND delta_fisico <> 0 AND delta_reservado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
  );

CREATE UNIQUE INDEX inventario_movimientos_conteo_detalle_uq
  ON inventario_movimientos (detalle_conteo_inventario_id)
  WHERE tipo = 'CONTEO';
CREATE INDEX inventario_movimientos_conteo_idx
  ON inventario_movimientos (conteo_inventario_id, id)
  WHERE conteo_inventario_id IS NOT NULL;

CREATE OR REPLACE FUNCTION impedir_mutacion_registro_auditoria()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  RAISE EXCEPTION 'El registro de auditoría % es inmutable.', TG_TABLE_NAME
    USING ERRCODE = '55000';
END
$function$;

CREATE TRIGGER politicas_reposicion_historial_inmutable_trg
  BEFORE UPDATE OR DELETE ON politicas_reposicion_historial
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();
CREATE TRIGGER capturas_conteo_inventario_inmutable_trg
  BEFORE UPDATE OR DELETE ON capturas_conteo_inventario
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();
CREATE TRIGGER conteo_inventario_transiciones_inmutable_trg
  BEFORE UPDATE OR DELETE ON conteo_inventario_transiciones
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();

CREATE OR REPLACE FUNCTION validar_politica_reposicion_auditada(p_producto_id INTEGER)
RETURNS VOID
LANGUAGE plpgsql
AS $function$
DECLARE
  v_politica politicas_reposicion%ROWTYPE;
  v_historial politicas_reposicion_historial%ROWTYPE;
BEGIN
  SELECT * INTO v_politica FROM politicas_reposicion WHERE producto_id=p_producto_id;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT * INTO v_historial
  FROM politicas_reposicion_historial
  WHERE producto_id=p_producto_id ORDER BY id DESC LIMIT 1;
  IF NOT FOUND
     OR v_historial.stock_minimo_nuevo <> v_politica.stock_minimo
     OR v_historial.stock_objetivo_nuevo <> v_politica.stock_objetivo
     OR v_historial.proveedor_nuevo_id IS DISTINCT FROM v_politica.proveedor_preferido_id
     OR v_historial.usuario_id <> v_politica.actualizado_por_usuario_id THEN
    RAISE EXCEPTION 'La política de reposición % carece de auditoría conciliada.', p_producto_id
      USING ERRCODE = '23514';
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_politica_reposicion_auditada_trg()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  PERFORM validar_politica_reposicion_auditada(
    CASE WHEN TG_OP='DELETE' THEN OLD.producto_id ELSE NEW.producto_id END
  );
  RETURN NULL;
END
$function$;

CREATE CONSTRAINT TRIGGER politicas_reposicion_auditoria_trg
  AFTER INSERT OR UPDATE ON politicas_reposicion DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_politica_reposicion_auditada_trg();
CREATE CONSTRAINT TRIGGER politicas_reposicion_historial_conciliacion_trg
  AFTER INSERT ON politicas_reposicion_historial DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_politica_reposicion_auditada_trg();

CREATE OR REPLACE FUNCTION validar_captura_conteo_borrador()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_estado VARCHAR(12);
BEGIN
  SELECT estado INTO v_estado
  FROM conteos_inventario
  WHERE id=NEW.conteo_inventario_id
  FOR KEY SHARE;
  IF v_estado IS DISTINCT FROM 'BORRADOR' THEN
    RAISE EXCEPTION 'Sólo un conteo en borrador acepta capturas.' USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER capturas_conteo_inventario_estado_trg
  BEFORE INSERT ON capturas_conteo_inventario
  FOR EACH ROW EXECUTE FUNCTION validar_captura_conteo_borrador();

CREATE OR REPLACE FUNCTION proteger_conteo_inventario()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Los conteos no se eliminan; deben cancelarse.' USING ERRCODE = '55000';
  END IF;
  IF OLD.estado <> 'BORRADOR' THEN
    RAISE EXCEPTION 'Un conteo finalizado es inmutable.' USING ERRCODE = '55000';
  END IF;
  IF NEW.id <> OLD.id OR NEW.folio <> OLD.folio OR NEW.notas IS DISTINCT FROM OLD.notas
     OR NEW.creado_por_usuario_id <> OLD.creado_por_usuario_id
     OR NEW.creado_en <> OLD.creado_en THEN
    RAISE EXCEPTION 'No se puede modificar la identidad del conteo.' USING ERRCODE = '55000';
  END IF;
  IF NEW.estado = 'BORRADOR' THEN
    RETURN NEW;
  END IF;
  IF NEW.estado NOT IN ('APLICADO', 'CANCELADO') THEN
    RAISE EXCEPTION 'Transición de conteo no permitida.' USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER conteos_inventario_proteger_trg
  BEFORE UPDATE OR DELETE ON conteos_inventario
  FOR EACH ROW EXECUTE FUNCTION proteger_conteo_inventario();

CREATE OR REPLACE FUNCTION proteger_detalle_conteo_inventario()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Las partidas de conteo son inmutables.' USING ERRCODE = '55000';
  END IF;
  IF NEW.id <> OLD.id
     OR NEW.conteo_inventario_id <> OLD.conteo_inventario_id
     OR NEW.producto_id <> OLD.producto_id
     OR NEW.producto_sku <> OLD.producto_sku
     OR NEW.producto_titulo <> OLD.producto_titulo
     OR NEW.stock_fisico_al_abrir <> OLD.stock_fisico_al_abrir
     OR NEW.stock_reservado_al_abrir <> OLD.stock_reservado_al_abrir
     OR NEW.movimiento_al_abrir_id IS DISTINCT FROM OLD.movimiento_al_abrir_id
     OR NEW.creado_en <> OLD.creado_en THEN
    RAISE EXCEPTION 'No se puede modificar el snapshot de la partida.' USING ERRCODE = '55000';
  END IF;
  IF OLD.captura_aplicada_id IS NOT NULL
     OR NEW.captura_aplicada_id IS NULL
     OR NEW.diferencia_aplicada IS NULL
     OR NEW.stock_fisico_aplicado IS NULL
     OR NEW.stock_reservado_aplicado IS NULL THEN
    RAISE EXCEPTION 'La aplicación de una partida sólo puede registrarse una vez.' USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER detalle_conteos_inventario_proteger_trg
  BEFORE UPDATE OR DELETE ON detalle_conteos_inventario
  FOR EACH ROW EXECUTE FUNCTION proteger_detalle_conteo_inventario();

CREATE OR REPLACE FUNCTION validar_conteo_inventario_conciliado(p_conteo_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $function$
DECLARE
  v_conteo conteos_inventario%ROWTYPE;
  v_lineas INTEGER;
  v_ultima_transicion VARCHAR(12);
BEGIN
  SELECT * INTO v_conteo FROM conteos_inventario WHERE id = p_conteo_id;
  IF NOT FOUND THEN RETURN; END IF;

  SELECT COUNT(*) INTO v_lineas
  FROM detalle_conteos_inventario WHERE conteo_inventario_id = p_conteo_id;
  IF v_lineas = 0 THEN
    RAISE EXCEPTION 'El conteo % no contiene partidas.', p_conteo_id USING ERRCODE = '23514';
  END IF;

  SELECT estado_nuevo INTO v_ultima_transicion
  FROM conteo_inventario_transiciones
  WHERE conteo_inventario_id = p_conteo_id
  ORDER BY id DESC LIMIT 1;
  IF v_ultima_transicion IS DISTINCT FROM v_conteo.estado THEN
    RAISE EXCEPTION 'El historial del conteo % no coincide con su estado.', p_conteo_id
      USING ERRCODE = '23514';
  END IF;

  IF v_conteo.estado IN ('BORRADOR', 'CANCELADO') THEN
    IF EXISTS (
      SELECT 1 FROM detalle_conteos_inventario
      WHERE conteo_inventario_id = p_conteo_id
        AND captura_aplicada_id IS NOT NULL
    ) OR EXISTS (
      SELECT 1 FROM inventario_movimientos
      WHERE conteo_inventario_id = p_conteo_id
    ) THEN
      RAISE EXCEPTION 'El conteo % no aplicado contiene efectos de inventario.', p_conteo_id
        USING ERRCODE = '23514';
    END IF;
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM detalle_conteos_inventario d
    LEFT JOIN capturas_conteo_inventario c ON c.id = d.captura_aplicada_id
    LEFT JOIN inventario_movimientos im
      ON im.detalle_conteo_inventario_id = d.id AND im.tipo = 'CONTEO'
    WHERE d.conteo_inventario_id = p_conteo_id
      AND (
        c.id IS NULL
        OR c.detalle_conteo_inventario_id <> d.id
        OR c.conteo_inventario_id <> d.conteo_inventario_id
        OR c.producto_id <> d.producto_id
        OR d.diferencia_aplicada <> c.cantidad_contada - c.stock_fisico_base
        OR d.stock_fisico_aplicado <> c.cantidad_contada
        OR d.stock_reservado_aplicado <> c.stock_reservado_base
        OR (d.diferencia_aplicada = 0 AND im.id IS NOT NULL)
        OR (
          d.diferencia_aplicada <> 0
          AND (
            im.id IS NULL OR im.producto_id <> d.producto_id
            OR im.conteo_inventario_id <> d.conteo_inventario_id
            OR im.delta_fisico <> d.diferencia_aplicada OR im.delta_reservado <> 0
            OR im.stock_fisico_resultante <> d.stock_fisico_aplicado
            OR im.stock_reservado_resultante <> d.stock_reservado_aplicado
          )
        )
      )
  ) THEN
    RAISE EXCEPTION 'Las partidas aplicadas del conteo % no están conciliadas.', p_conteo_id
      USING ERRCODE = '23514';
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_conteo_inventario_conciliado_trg()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_id BIGINT;
BEGIN
  IF TG_TABLE_NAME = 'conteos_inventario' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
  ELSIF TG_TABLE_NAME = 'detalle_conteos_inventario' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.conteo_inventario_id ELSE NEW.conteo_inventario_id END;
  ELSIF TG_TABLE_NAME = 'conteo_inventario_transiciones' THEN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.conteo_inventario_id ELSE NEW.conteo_inventario_id END;
  ELSE
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.conteo_inventario_id ELSE NEW.conteo_inventario_id END;
  END IF;
  PERFORM validar_conteo_inventario_conciliado(v_id);
  RETURN NULL;
END
$function$;

CREATE CONSTRAINT TRIGGER conteos_inventario_conciliacion_trg
  AFTER INSERT OR UPDATE ON conteos_inventario DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_conteo_inventario_conciliado_trg();
CREATE CONSTRAINT TRIGGER detalle_conteos_inventario_conciliacion_trg
  AFTER INSERT OR UPDATE ON detalle_conteos_inventario DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_conteo_inventario_conciliado_trg();
CREATE CONSTRAINT TRIGGER conteo_inventario_transiciones_conciliacion_trg
  AFTER INSERT ON conteo_inventario_transiciones DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_conteo_inventario_conciliado_trg();
CREATE CONSTRAINT TRIGGER inventario_conteo_conciliacion_trg
  AFTER INSERT ON inventario_movimientos DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  WHEN (NEW.conteo_inventario_id IS NOT NULL)
  EXECUTE FUNCTION validar_conteo_inventario_conciliado_trg();
