-- Núcleo editorial: obras/manuscritos, colaboradores, ediciones vinculadas,
-- contratos, derechos y flujos auditables.
--
-- productos continúa siendo la única edición vendible y la fuente común de
-- precio, inventario, POS y tienda. Las obras sólo agrupan productos existentes.

CREATE SEQUENCE obras_editoriales_folio_seq START WITH 1;
CREATE SEQUENCE contratos_editoriales_folio_seq START WITH 1;

CREATE TABLE colaboradores_editoriales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_legal VARCHAR(160) NOT NULL,
  nombre_publico VARCHAR(160),
  email VARCHAR(254),
  telefono VARCHAR(30),
  identificador_fiscal VARCHAR(40),
  notas TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT colaboradores_editoriales_nombre_check CHECK (btrim(nombre_legal) <> ''),
  CONSTRAINT colaboradores_editoriales_nombre_publico_check CHECK (
    nombre_publico IS NULL OR btrim(nombre_publico) <> ''
  ),
  CONSTRAINT colaboradores_editoriales_email_check CHECK (
    email IS NULL OR btrim(email) <> ''
  ),
  CONSTRAINT colaboradores_editoriales_telefono_check CHECK (
    telefono IS NULL OR btrim(telefono) <> ''
  ),
  CONSTRAINT colaboradores_editoriales_fiscal_check CHECK (
    identificador_fiscal IS NULL OR btrim(identificador_fiscal) <> ''
  ),
  CONSTRAINT colaboradores_editoriales_notas_check CHECK (
    notas IS NULL OR btrim(notas) <> ''
  )
);

CREATE UNIQUE INDEX colaboradores_editoriales_email_lower_uq
  ON colaboradores_editoriales (lower(email)) WHERE email IS NOT NULL;
CREATE INDEX colaboradores_editoriales_nombre_fts_idx
  ON colaboradores_editoriales USING GIN (
    to_tsvector(
      'spanish',
      nombre_legal || ' ' || COALESCE(nombre_publico, '')
    )
  );
CREATE INDEX colaboradores_editoriales_activo_nombre_idx
  ON colaboradores_editoriales (activo, nombre_legal, id);
CREATE TRIGGER colaboradores_editoriales_actualizado_en_trg
  BEFORE UPDATE ON colaboradores_editoriales
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE TABLE obras_editoriales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('OBR-' || LPAD(nextval('obras_editoriales_folio_seq')::text, 10, '0')),
  titulo VARCHAR(240) NOT NULL,
  subtitulo VARCHAR(240),
  sinopsis TEXT,
  idioma VARCHAR(60) NOT NULL DEFAULT 'Español',
  estado VARCHAR(16) NOT NULL DEFAULT 'PROPUESTA',
  fecha_recepcion DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_objetivo_publicacion DATE,
  editor_responsable_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  notas TEXT,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT obras_editoriales_titulo_check CHECK (btrim(titulo) <> ''),
  CONSTRAINT obras_editoriales_subtitulo_check CHECK (
    subtitulo IS NULL OR btrim(subtitulo) <> ''
  ),
  CONSTRAINT obras_editoriales_sinopsis_check CHECK (
    sinopsis IS NULL OR btrim(sinopsis) <> ''
  ),
  CONSTRAINT obras_editoriales_idioma_check CHECK (btrim(idioma) <> ''),
  CONSTRAINT obras_editoriales_estado_check CHECK (
    estado IN (
      'PROPUESTA', 'EVALUACION', 'CONTRATADA', 'EDICION',
      'DISENO', 'IMPRESION', 'PUBLICADA', 'ARCHIVADA'
    )
  ),
  CONSTRAINT obras_editoriales_fechas_check CHECK (
    fecha_objetivo_publicacion IS NULL
    OR fecha_objetivo_publicacion >= fecha_recepcion
  ),
  CONSTRAINT obras_editoriales_notas_check CHECK (
    notas IS NULL OR btrim(notas) <> ''
  )
);

CREATE INDEX obras_editoriales_estado_fecha_idx
  ON obras_editoriales (estado, actualizado_en DESC, id DESC);
CREATE INDEX obras_editoriales_editor_idx
  ON obras_editoriales (editor_responsable_usuario_id, estado, id)
  WHERE editor_responsable_usuario_id IS NOT NULL;
CREATE INDEX obras_editoriales_busqueda_fts_idx
  ON obras_editoriales USING GIN (
    to_tsvector(
      'spanish',
      titulo || ' ' || COALESCE(subtitulo, '') || ' ' || COALESCE(sinopsis, '')
    )
  );
CREATE TRIGGER obras_editoriales_actualizado_en_trg
  BEFORE UPDATE ON obras_editoriales
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE TABLE obra_editorial_transiciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  obra_editorial_id BIGINT NOT NULL REFERENCES obras_editoriales(id) ON DELETE RESTRICT,
  estado_anterior VARCHAR(16),
  estado_nuevo VARCHAR(16) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(500) NOT NULL,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT obra_editorial_transiciones_anterior_check CHECK (
    estado_anterior IS NULL OR estado_anterior IN (
      'PROPUESTA', 'EVALUACION', 'CONTRATADA', 'EDICION',
      'DISENO', 'IMPRESION', 'PUBLICADA', 'ARCHIVADA'
    )
  ),
  CONSTRAINT obra_editorial_transiciones_nuevo_check CHECK (
    estado_nuevo IN (
      'PROPUESTA', 'EVALUACION', 'CONTRATADA', 'EDICION',
      'DISENO', 'IMPRESION', 'PUBLICADA', 'ARCHIVADA'
    )
  ),
  CONSTRAINT obra_editorial_transiciones_cambio_check CHECK (
    (estado_anterior IS NULL AND estado_nuevo = 'PROPUESTA')
    OR (estado_anterior = 'PROPUESTA' AND estado_nuevo IN ('EVALUACION', 'ARCHIVADA'))
    OR (estado_anterior = 'EVALUACION' AND estado_nuevo IN ('PROPUESTA', 'CONTRATADA', 'ARCHIVADA'))
    OR (estado_anterior = 'CONTRATADA' AND estado_nuevo IN ('EVALUACION', 'EDICION', 'ARCHIVADA'))
    OR (estado_anterior = 'EDICION' AND estado_nuevo IN ('CONTRATADA', 'DISENO', 'ARCHIVADA'))
    OR (estado_anterior = 'DISENO' AND estado_nuevo IN ('EDICION', 'IMPRESION', 'ARCHIVADA'))
    OR (estado_anterior = 'IMPRESION' AND estado_nuevo IN ('DISENO', 'PUBLICADA', 'ARCHIVADA'))
    OR (estado_anterior = 'PUBLICADA' AND estado_nuevo = 'ARCHIVADA')
  ),
  CONSTRAINT obra_editorial_transiciones_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT obra_editorial_transiciones_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE UNIQUE INDEX obra_editorial_transiciones_inicial_uq
  ON obra_editorial_transiciones (obra_editorial_id)
  WHERE estado_anterior IS NULL;
CREATE INDEX obra_editorial_transiciones_obra_idx
  ON obra_editorial_transiciones (obra_editorial_id, id);
CREATE TRIGGER obra_editorial_transiciones_inmutables_trg
  BEFORE UPDATE OR DELETE ON obra_editorial_transiciones
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();

CREATE TABLE obra_editorial_colaboradores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  obra_editorial_id BIGINT NOT NULL REFERENCES obras_editoriales(id) ON DELETE RESTRICT,
  colaborador_editorial_id BIGINT NOT NULL
    REFERENCES colaboradores_editoriales(id) ON DELETE RESTRICT,
  rol VARCHAR(20) NOT NULL,
  nombre_credito VARCHAR(160),
  orden_credito INTEGER NOT NULL DEFAULT 0,
  credito_publico BOOLEAN NOT NULL DEFAULT TRUE,
  notas TEXT,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT obra_editorial_colaboradores_rol_check CHECK (
    rol IN (
      'AUTOR', 'TRADUCTOR', 'ILUSTRADOR', 'EDITOR', 'CORRECTOR',
      'COORDINADOR', 'DISENADOR'
    )
  ),
  CONSTRAINT obra_editorial_colaboradores_nombre_check CHECK (
    nombre_credito IS NULL OR btrim(nombre_credito) <> ''
  ),
  CONSTRAINT obra_editorial_colaboradores_orden_check CHECK (orden_credito >= 0),
  CONSTRAINT obra_editorial_colaboradores_notas_check CHECK (
    notas IS NULL OR btrim(notas) <> ''
  ),
  CONSTRAINT obra_editorial_colaboradores_uq
    UNIQUE (obra_editorial_id, colaborador_editorial_id, rol),
  CONSTRAINT obra_editorial_colaboradores_id_obra_colaborador_uq
    UNIQUE (id, obra_editorial_id, colaborador_editorial_id)
);

CREATE INDEX obra_editorial_colaboradores_obra_idx
  ON obra_editorial_colaboradores (obra_editorial_id, orden_credito, id);
CREATE INDEX obra_editorial_colaboradores_colaborador_idx
  ON obra_editorial_colaboradores (colaborador_editorial_id, obra_editorial_id, id);
CREATE TRIGGER obra_editorial_colaboradores_actualizado_en_trg
  BEFORE UPDATE ON obra_editorial_colaboradores
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

ALTER TABLE productos
  ADD COLUMN obra_editorial_id BIGINT REFERENCES obras_editoriales(id) ON DELETE RESTRICT;
CREATE INDEX productos_obra_editorial_idx
  ON productos (obra_editorial_id, id) WHERE obra_editorial_id IS NOT NULL;

CREATE TABLE producto_obra_editorial_historial (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  obra_anterior_id BIGINT REFERENCES obras_editoriales(id) ON DELETE RESTRICT,
  obra_nueva_id BIGINT REFERENCES obras_editoriales(id) ON DELETE RESTRICT,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(500) NOT NULL,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT producto_obra_editorial_historial_cambio_check CHECK (
    obra_anterior_id IS DISTINCT FROM obra_nueva_id
  ),
  CONSTRAINT producto_obra_editorial_historial_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT producto_obra_editorial_historial_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE INDEX producto_obra_editorial_historial_producto_idx
  ON producto_obra_editorial_historial (producto_id, id);
CREATE INDEX producto_obra_editorial_historial_obra_idx
  ON producto_obra_editorial_historial (obra_nueva_id, id)
  WHERE obra_nueva_id IS NOT NULL;
CREATE TRIGGER producto_obra_editorial_historial_inmutable_trg
  BEFORE UPDATE OR DELETE ON producto_obra_editorial_historial
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();

CREATE TABLE contratos_editoriales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('CON-' || LPAD(nextval('contratos_editoriales_folio_seq')::text, 10, '0')),
  obra_editorial_id BIGINT NOT NULL REFERENCES obras_editoriales(id) ON DELETE RESTRICT,
  colaborador_editorial_id BIGINT NOT NULL
    REFERENCES colaboradores_editoriales(id) ON DELETE RESTRICT,
  obra_folio VARCHAR(24) NOT NULL,
  obra_titulo VARCHAR(240) NOT NULL,
  colaborador_nombre VARCHAR(160) NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  derechos TEXT NOT NULL,
  territorio VARCHAR(120) NOT NULL DEFAULT 'México',
  idioma_derechos VARCHAR(80) NOT NULL DEFAULT 'Todos',
  exclusividad BOOLEAN NOT NULL DEFAULT FALSE,
  vigente_desde DATE NOT NULL,
  vigente_hasta DATE,
  base_regalia VARCHAR(20) NOT NULL DEFAULT 'VENTA_NETA',
  porcentaje_regalia NUMERIC(7,4) NOT NULL,
  anticipo NUMERIC(12,2) NOT NULL DEFAULT 0,
  moneda CHAR(3) NOT NULL DEFAULT 'MXN',
  periodicidad_liquidacion VARCHAR(12) NOT NULL DEFAULT 'SEMESTRAL',
  estado VARCHAR(12) NOT NULL DEFAULT 'BORRADOR',
  notas TEXT,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT contratos_editoriales_obra_snapshot_check CHECK (
    btrim(obra_folio) <> '' AND btrim(obra_titulo) <> ''
  ),
  CONSTRAINT contratos_editoriales_colaborador_snapshot_check CHECK (
    btrim(colaborador_nombre) <> ''
  ),
  CONSTRAINT contratos_editoriales_tipo_check CHECK (
    tipo IN ('EDICION', 'CESION', 'LICENCIA', 'COLABORACION')
  ),
  CONSTRAINT contratos_editoriales_derechos_check CHECK (btrim(derechos) <> ''),
  CONSTRAINT contratos_editoriales_territorio_check CHECK (btrim(territorio) <> ''),
  CONSTRAINT contratos_editoriales_idioma_check CHECK (btrim(idioma_derechos) <> ''),
  CONSTRAINT contratos_editoriales_fechas_check CHECK (
    vigente_hasta IS NULL OR vigente_hasta >= vigente_desde
  ),
  CONSTRAINT contratos_editoriales_base_check CHECK (
    base_regalia IN ('VENTA_NETA', 'PRECIO_LISTA')
  ),
  CONSTRAINT contratos_editoriales_porcentaje_check CHECK (
    porcentaje_regalia >= 0 AND porcentaje_regalia <= 100
  ),
  CONSTRAINT contratos_editoriales_anticipo_check CHECK (anticipo >= 0),
  CONSTRAINT contratos_editoriales_moneda_check CHECK (moneda ~ '^[A-Z]{3}$'),
  CONSTRAINT contratos_editoriales_periodicidad_check CHECK (
    periodicidad_liquidacion IN ('MENSUAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', 'UNICA')
  ),
  CONSTRAINT contratos_editoriales_estado_check CHECK (
    estado IN ('BORRADOR', 'VIGENTE', 'SUSPENDIDO', 'TERMINADO')
  ),
  CONSTRAINT contratos_editoriales_notas_check CHECK (
    notas IS NULL OR btrim(notas) <> ''
  )
);

CREATE INDEX contratos_editoriales_obra_estado_idx
  ON contratos_editoriales (obra_editorial_id, estado, id);
CREATE INDEX contratos_editoriales_colaborador_estado_idx
  ON contratos_editoriales (colaborador_editorial_id, estado, id);
CREATE INDEX contratos_editoriales_vigencia_idx
  ON contratos_editoriales (estado, vigente_desde, vigente_hasta, id);
CREATE TRIGGER contratos_editoriales_actualizado_en_trg
  BEFORE UPDATE ON contratos_editoriales
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE TABLE contrato_editorial_transiciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_editorial_id BIGINT NOT NULL
    REFERENCES contratos_editoriales(id) ON DELETE RESTRICT,
  estado_anterior VARCHAR(12),
  estado_nuevo VARCHAR(12) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(500) NOT NULL,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT contrato_editorial_transiciones_anterior_check CHECK (
    estado_anterior IS NULL OR estado_anterior IN (
      'BORRADOR', 'VIGENTE', 'SUSPENDIDO', 'TERMINADO'
    )
  ),
  CONSTRAINT contrato_editorial_transiciones_nuevo_check CHECK (
    estado_nuevo IN ('BORRADOR', 'VIGENTE', 'SUSPENDIDO', 'TERMINADO')
  ),
  CONSTRAINT contrato_editorial_transiciones_cambio_check CHECK (
    (estado_anterior IS NULL AND estado_nuevo = 'BORRADOR')
    OR (estado_anterior = 'BORRADOR' AND estado_nuevo IN ('VIGENTE', 'TERMINADO'))
    OR (estado_anterior = 'VIGENTE' AND estado_nuevo IN ('SUSPENDIDO', 'TERMINADO'))
    OR (estado_anterior = 'SUSPENDIDO' AND estado_nuevo IN ('VIGENTE', 'TERMINADO'))
  ),
  CONSTRAINT contrato_editorial_transiciones_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT contrato_editorial_transiciones_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE UNIQUE INDEX contrato_editorial_transiciones_inicial_uq
  ON contrato_editorial_transiciones (contrato_editorial_id)
  WHERE estado_anterior IS NULL;
CREATE INDEX contrato_editorial_transiciones_contrato_idx
  ON contrato_editorial_transiciones (contrato_editorial_id, id);
CREATE TRIGGER contrato_editorial_transiciones_inmutables_trg
  BEFORE UPDATE OR DELETE ON contrato_editorial_transiciones
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();

CREATE OR REPLACE FUNCTION validar_cadena_transicion_editorial()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_ultimo_estado TEXT;
BEGIN
  IF TG_TABLE_NAME = 'obra_editorial_transiciones' THEN
    SELECT estado_nuevo INTO v_ultimo_estado
    FROM obra_editorial_transiciones
    WHERE obra_editorial_id = NEW.obra_editorial_id
    ORDER BY id DESC LIMIT 1;
  ELSE
    SELECT estado_nuevo INTO v_ultimo_estado
    FROM contrato_editorial_transiciones
    WHERE contrato_editorial_id = NEW.contrato_editorial_id
    ORDER BY id DESC LIMIT 1;
  END IF;

  IF NEW.estado_anterior IS DISTINCT FROM v_ultimo_estado THEN
    RAISE EXCEPTION 'La transición editorial no continúa el historial vigente.'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER obra_editorial_transiciones_cadena_trg
  BEFORE INSERT ON obra_editorial_transiciones
  FOR EACH ROW EXECUTE FUNCTION validar_cadena_transicion_editorial();
CREATE TRIGGER contrato_editorial_transiciones_cadena_trg
  BEFORE INSERT ON contrato_editorial_transiciones
  FOR EACH ROW EXECUTE FUNCTION validar_cadena_transicion_editorial();

CREATE OR REPLACE FUNCTION validar_contrato_colaborador_obra()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM obra_editorial_colaboradores oc
    WHERE oc.obra_editorial_id = NEW.obra_editorial_id
      AND oc.colaborador_editorial_id = NEW.colaborador_editorial_id
  ) THEN
    RAISE EXCEPTION 'El colaborador debe pertenecer al equipo de la obra.'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER contratos_editoriales_colaborador_obra_trg
  BEFORE INSERT OR UPDATE OF obra_editorial_id, colaborador_editorial_id
  ON contratos_editoriales
  FOR EACH ROW EXECUTE FUNCTION validar_contrato_colaborador_obra();

CREATE OR REPLACE FUNCTION proteger_vinculo_con_contrato_editorial()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF EXISTS (
    SELECT 1 FROM contratos_editoriales c
    WHERE c.obra_editorial_id = OLD.obra_editorial_id
      AND c.colaborador_editorial_id = OLD.colaborador_editorial_id
      AND c.estado <> 'TERMINADO'
  ) THEN
    RAISE EXCEPTION 'El vínculo pertenece a un contrato editorial no terminado.'
      USING ERRCODE = '55000';
  END IF;
  RETURN OLD;
END
$function$;

CREATE TRIGGER obra_editorial_colaboradores_contrato_trg
  BEFORE DELETE OR UPDATE OF obra_editorial_id, colaborador_editorial_id
  ON obra_editorial_colaboradores
  FOR EACH ROW EXECUTE FUNCTION proteger_vinculo_con_contrato_editorial();

CREATE OR REPLACE FUNCTION proteger_obra_editorial()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Las obras editoriales no se eliminan; deben archivarse.'
      USING ERRCODE = '55000';
  END IF;
  IF NEW.id <> OLD.id OR NEW.folio <> OLD.folio
     OR NEW.creado_por_usuario_id <> OLD.creado_por_usuario_id
     OR NEW.creado_en <> OLD.creado_en THEN
    RAISE EXCEPTION 'No se puede modificar la identidad de la obra editorial.'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER obras_editoriales_proteger_trg
  BEFORE UPDATE OR DELETE ON obras_editoriales
  FOR EACH ROW EXECUTE FUNCTION proteger_obra_editorial();

CREATE OR REPLACE FUNCTION proteger_contrato_editorial()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Los contratos editoriales no se eliminan; deben terminarse.'
      USING ERRCODE = '55000';
  END IF;
  IF NEW.id <> OLD.id OR NEW.folio <> OLD.folio
     OR NEW.obra_folio <> OLD.obra_folio
     OR NEW.obra_titulo <> OLD.obra_titulo
     OR NEW.colaborador_nombre <> OLD.colaborador_nombre
     OR NEW.creado_por_usuario_id <> OLD.creado_por_usuario_id
     OR NEW.creado_en <> OLD.creado_en THEN
    RAISE EXCEPTION 'No se puede modificar la identidad o snapshots del contrato.'
      USING ERRCODE = '55000';
  END IF;
  IF OLD.estado <> 'BORRADOR' AND (
    NEW.obra_editorial_id <> OLD.obra_editorial_id
    OR NEW.colaborador_editorial_id <> OLD.colaborador_editorial_id
    OR NEW.tipo <> OLD.tipo OR NEW.derechos <> OLD.derechos
    OR NEW.territorio <> OLD.territorio
    OR NEW.idioma_derechos <> OLD.idioma_derechos
    OR NEW.exclusividad <> OLD.exclusividad
    OR NEW.vigente_desde <> OLD.vigente_desde
    OR NEW.vigente_hasta IS DISTINCT FROM OLD.vigente_hasta
    OR NEW.base_regalia <> OLD.base_regalia
    OR NEW.porcentaje_regalia <> OLD.porcentaje_regalia
    OR NEW.anticipo <> OLD.anticipo OR NEW.moneda <> OLD.moneda
    OR NEW.periodicidad_liquidacion <> OLD.periodicidad_liquidacion
    OR NEW.notas IS DISTINCT FROM OLD.notas
  ) THEN
    RAISE EXCEPTION 'Los términos de un contrato activado son inmutables.'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER contratos_editoriales_proteger_trg
  BEFORE UPDATE OR DELETE ON contratos_editoriales
  FOR EACH ROW EXECUTE FUNCTION proteger_contrato_editorial();

CREATE OR REPLACE FUNCTION validar_producto_obra_historial_previo()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_actual BIGINT;
  v_ultimo BIGINT;
  v_tiene_historial BOOLEAN;
BEGIN
  SELECT obra_editorial_id INTO v_actual
  FROM productos WHERE id = NEW.producto_id FOR KEY SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Producto editorial no encontrado.' USING ERRCODE = '23503';
  END IF;
  IF v_actual IS DISTINCT FROM NEW.obra_anterior_id THEN
    RAISE EXCEPTION 'El vínculo anterior del producto cambió.' USING ERRCODE = '23514';
  END IF;

  SELECT TRUE, obra_nueva_id INTO v_tiene_historial, v_ultimo
  FROM producto_obra_editorial_historial
  WHERE producto_id = NEW.producto_id
  ORDER BY id DESC LIMIT 1;
  IF COALESCE(v_tiene_historial, FALSE)
     AND v_ultimo IS DISTINCT FROM NEW.obra_anterior_id THEN
    RAISE EXCEPTION 'El historial del vínculo editorial no es continuo.'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER producto_obra_editorial_historial_previo_trg
  BEFORE INSERT ON producto_obra_editorial_historial
  FOR EACH ROW EXECUTE FUNCTION validar_producto_obra_historial_previo();

CREATE OR REPLACE FUNCTION validar_obra_editorial_conciliada(p_obra_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $function$
DECLARE
  v_estado VARCHAR(16);
  v_ultimo VARCHAR(16);
BEGIN
  SELECT estado INTO v_estado FROM obras_editoriales WHERE id = p_obra_id;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT estado_nuevo INTO v_ultimo
  FROM obra_editorial_transiciones
  WHERE obra_editorial_id = p_obra_id ORDER BY id DESC LIMIT 1;
  IF v_ultimo IS DISTINCT FROM v_estado THEN
    RAISE EXCEPTION 'El historial de la obra % no coincide con su estado.', p_obra_id
      USING ERRCODE = '23514';
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_contrato_editorial_conciliado(p_contrato_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $function$
DECLARE
  v_estado VARCHAR(12);
  v_ultimo VARCHAR(12);
BEGIN
  SELECT estado INTO v_estado FROM contratos_editoriales WHERE id = p_contrato_id;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT estado_nuevo INTO v_ultimo
  FROM contrato_editorial_transiciones
  WHERE contrato_editorial_id = p_contrato_id ORDER BY id DESC LIMIT 1;
  IF v_ultimo IS DISTINCT FROM v_estado THEN
    RAISE EXCEPTION 'El historial del contrato % no coincide con su estado.', p_contrato_id
      USING ERRCODE = '23514';
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_producto_obra_conciliado(p_producto_id INTEGER)
RETURNS VOID
LANGUAGE plpgsql
AS $function$
DECLARE
  v_obra BIGINT;
  v_ultima_obra BIGINT;
  v_tiene_historial BOOLEAN;
BEGIN
  SELECT obra_editorial_id INTO v_obra FROM productos WHERE id = p_producto_id;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT TRUE, obra_nueva_id INTO v_tiene_historial, v_ultima_obra
  FROM producto_obra_editorial_historial
  WHERE producto_id = p_producto_id ORDER BY id DESC LIMIT 1;
  IF COALESCE(v_tiene_historial, FALSE) THEN
    IF v_ultima_obra IS DISTINCT FROM v_obra THEN
      RAISE EXCEPTION 'El historial editorial del producto % no coincide.', p_producto_id
        USING ERRCODE = '23514';
    END IF;
  ELSIF v_obra IS NOT NULL THEN
    RAISE EXCEPTION 'El producto % carece de historial editorial.', p_producto_id
      USING ERRCODE = '23514';
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_editorial_conciliado_trg()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_TABLE_NAME = 'obras_editoriales' THEN
    PERFORM validar_obra_editorial_conciliada(CASE WHEN TG_OP='DELETE' THEN OLD.id ELSE NEW.id END);
  ELSIF TG_TABLE_NAME = 'obra_editorial_transiciones' THEN
    PERFORM validar_obra_editorial_conciliada(
      CASE WHEN TG_OP='DELETE' THEN OLD.obra_editorial_id ELSE NEW.obra_editorial_id END
    );
  ELSIF TG_TABLE_NAME = 'contratos_editoriales' THEN
    PERFORM validar_contrato_editorial_conciliado(CASE WHEN TG_OP='DELETE' THEN OLD.id ELSE NEW.id END);
  ELSIF TG_TABLE_NAME = 'contrato_editorial_transiciones' THEN
    PERFORM validar_contrato_editorial_conciliado(
      CASE WHEN TG_OP='DELETE' THEN OLD.contrato_editorial_id ELSE NEW.contrato_editorial_id END
    );
  ELSIF TG_TABLE_NAME = 'productos' THEN
    PERFORM validar_producto_obra_conciliado(CASE WHEN TG_OP='DELETE' THEN OLD.id ELSE NEW.id END);
  ELSE
    PERFORM validar_producto_obra_conciliado(
      CASE WHEN TG_OP='DELETE' THEN OLD.producto_id ELSE NEW.producto_id END
    );
  END IF;
  RETURN NULL;
END
$function$;

CREATE CONSTRAINT TRIGGER obras_editoriales_conciliacion_trg
  AFTER INSERT OR UPDATE ON obras_editoriales DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_editorial_conciliado_trg();
CREATE CONSTRAINT TRIGGER obra_editorial_transiciones_conciliacion_trg
  AFTER INSERT ON obra_editorial_transiciones DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_editorial_conciliado_trg();
CREATE CONSTRAINT TRIGGER contratos_editoriales_conciliacion_trg
  AFTER INSERT OR UPDATE ON contratos_editoriales DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_editorial_conciliado_trg();
CREATE CONSTRAINT TRIGGER contrato_editorial_transiciones_conciliacion_trg
  AFTER INSERT ON contrato_editorial_transiciones DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_editorial_conciliado_trg();
CREATE CONSTRAINT TRIGGER productos_obra_editorial_conciliacion_trg
  AFTER UPDATE OF obra_editorial_id ON productos DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_editorial_conciliado_trg();
CREATE CONSTRAINT TRIGGER producto_obra_historial_conciliacion_trg
  AFTER INSERT ON producto_obra_editorial_historial DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_editorial_conciliado_trg();

