-- Tirajes editoriales y costos de producción sobre el inventario común.
-- Confirmar un tiraje incrementa productos.stock mediante el mismo kardex
-- inmutable que utilizan compras, ventas, reservas y conteos.

CREATE SEQUENCE tirajes_editoriales_folio_seq START WITH 1;

CREATE TABLE tirajes_editoriales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('TIR-' || LPAD(nextval('tirajes_editoriales_folio_seq')::text, 10, '0')),
  obra_editorial_id BIGINT NOT NULL REFERENCES obras_editoriales(id) ON DELETE RESTRICT,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  obra_folio VARCHAR(24) NOT NULL,
  obra_titulo VARCHAR(240) NOT NULL,
  producto_sku VARCHAR(24) NOT NULL,
  producto_titulo VARCHAR(160) NOT NULL,
  producto_isbn VARCHAR(17),
  cantidad INTEGER NOT NULL,
  fecha_programada DATE NOT NULL,
  moneda CHAR(3) NOT NULL DEFAULT 'MXN',
  estado VARCHAR(12) NOT NULL DEFAULT 'BORRADOR',
  notas TEXT,
  costo_total_confirmado NUMERIC(14,2),
  costo_unitario_confirmado NUMERIC(12,2),
  costo_producto_anterior NUMERIC(12,2),
  costo_producto_nuevo NUMERIC(12,2),
  stock_anterior INTEGER,
  stock_resultante INTEGER,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  confirmado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  confirmado_en TIMESTAMPTZ,
  cancelado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  cancelado_en TIMESTAMPTZ,
  cancelacion_motivo VARCHAR(500),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tirajes_editoriales_obra_snapshot_check CHECK (
    btrim(obra_folio) <> '' AND btrim(obra_titulo) <> ''
  ),
  CONSTRAINT tirajes_editoriales_producto_snapshot_check CHECK (
    btrim(producto_sku) <> '' AND btrim(producto_titulo) <> ''
  ),
  CONSTRAINT tirajes_editoriales_isbn_check CHECK (
    producto_isbn IS NULL OR btrim(producto_isbn) <> ''
  ),
  CONSTRAINT tirajes_editoriales_cantidad_check CHECK (cantidad > 0),
  CONSTRAINT tirajes_editoriales_moneda_check CHECK (moneda ~ '^[A-Z]{3}$'),
  CONSTRAINT tirajes_editoriales_estado_check CHECK (
    estado IN ('BORRADOR', 'CONFIRMADO', 'CANCELADO')
  ),
  CONSTRAINT tirajes_editoriales_notas_check CHECK (
    notas IS NULL OR btrim(notas) <> ''
  ),
  CONSTRAINT tirajes_editoriales_cancelacion_motivo_check CHECK (
    cancelacion_motivo IS NULL OR btrim(cancelacion_motivo) <> ''
  ),
  CONSTRAINT tirajes_editoriales_resultado_check CHECK (
    stock_anterior IS NULL OR stock_resultante = stock_anterior + cantidad
  ),
  CONSTRAINT tirajes_editoriales_costo_check CHECK (
    costo_total_confirmado IS NULL OR (
      costo_total_confirmado > 0
      AND costo_unitario_confirmado = ROUND(costo_total_confirmado / cantidad, 2)
      AND costo_producto_anterior >= 0
      AND costo_producto_nuevo = costo_unitario_confirmado
    )
  ),
  CONSTRAINT tirajes_editoriales_efectos_estado_check CHECK (
    (
      estado = 'BORRADOR'
      AND costo_total_confirmado IS NULL AND costo_unitario_confirmado IS NULL
      AND costo_producto_anterior IS NULL AND costo_producto_nuevo IS NULL
      AND stock_anterior IS NULL AND stock_resultante IS NULL
      AND confirmado_por_usuario_id IS NULL AND confirmado_en IS NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado = 'CONFIRMADO'
      AND costo_total_confirmado IS NOT NULL AND costo_unitario_confirmado IS NOT NULL
      AND costo_producto_anterior IS NOT NULL AND costo_producto_nuevo IS NOT NULL
      AND stock_anterior IS NOT NULL AND stock_resultante IS NOT NULL
      AND confirmado_por_usuario_id IS NOT NULL AND confirmado_en IS NOT NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado = 'CANCELADO'
      AND costo_total_confirmado IS NULL AND costo_unitario_confirmado IS NULL
      AND costo_producto_anterior IS NULL AND costo_producto_nuevo IS NULL
      AND stock_anterior IS NULL AND stock_resultante IS NULL
      AND confirmado_por_usuario_id IS NULL AND confirmado_en IS NULL
      AND cancelado_por_usuario_id IS NOT NULL AND cancelado_en IS NOT NULL
      AND cancelacion_motivo IS NOT NULL
    )
  ),
  CONSTRAINT tirajes_editoriales_id_producto_uq UNIQUE (id, producto_id)
);

CREATE INDEX tirajes_editoriales_obra_estado_idx
  ON tirajes_editoriales (obra_editorial_id, estado, fecha_programada DESC, id DESC);
CREATE INDEX tirajes_editoriales_producto_estado_idx
  ON tirajes_editoriales (producto_id, estado, fecha_programada DESC, id DESC);
CREATE INDEX tirajes_editoriales_estado_fecha_idx
  ON tirajes_editoriales (estado, fecha_programada DESC, id DESC);
CREATE TRIGGER tirajes_editoriales_actualizado_en_trg
  BEFORE UPDATE ON tirajes_editoriales
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE TABLE tiraje_editorial_costos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tiraje_editorial_id BIGINT NOT NULL
    REFERENCES tirajes_editoriales(id) ON DELETE RESTRICT,
  tipo VARCHAR(20) NOT NULL,
  concepto VARCHAR(240) NOT NULL,
  proveedor_id BIGINT REFERENCES proveedores(id) ON DELETE RESTRICT,
  proveedor_nombre VARCHAR(160),
  referencia VARCHAR(100),
  monto NUMERIC(14,2) NOT NULL,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tiraje_editorial_costos_tipo_check CHECK (
    tipo IN (
      'PREPRENSA', 'IMPRESION', 'PAPEL', 'ENCUADERNACION',
      'ACABADOS', 'TRANSPORTE', 'OTRO'
    )
  ),
  CONSTRAINT tiraje_editorial_costos_concepto_check CHECK (btrim(concepto) <> ''),
  CONSTRAINT tiraje_editorial_costos_proveedor_check CHECK (
    (proveedor_id IS NULL AND proveedor_nombre IS NULL)
    OR (proveedor_id IS NOT NULL AND proveedor_nombre IS NOT NULL
        AND btrim(proveedor_nombre) <> '')
  ),
  CONSTRAINT tiraje_editorial_costos_referencia_check CHECK (
    referencia IS NULL OR btrim(referencia) <> ''
  ),
  CONSTRAINT tiraje_editorial_costos_monto_check CHECK (monto > 0)
);

CREATE INDEX tiraje_editorial_costos_tiraje_idx
  ON tiraje_editorial_costos (tiraje_editorial_id, id);
CREATE INDEX tiraje_editorial_costos_proveedor_idx
  ON tiraje_editorial_costos (proveedor_id, id) WHERE proveedor_id IS NOT NULL;
CREATE TRIGGER tiraje_editorial_costos_actualizado_en_trg
  BEFORE UPDATE ON tiraje_editorial_costos
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE TABLE tiraje_editorial_transiciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tiraje_editorial_id BIGINT NOT NULL
    REFERENCES tirajes_editoriales(id) ON DELETE RESTRICT,
  estado_anterior VARCHAR(12),
  estado_nuevo VARCHAR(12) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(500) NOT NULL,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tiraje_editorial_transiciones_anterior_check CHECK (
    estado_anterior IS NULL OR estado_anterior IN ('BORRADOR', 'CONFIRMADO', 'CANCELADO')
  ),
  CONSTRAINT tiraje_editorial_transiciones_nuevo_check CHECK (
    estado_nuevo IN ('BORRADOR', 'CONFIRMADO', 'CANCELADO')
  ),
  CONSTRAINT tiraje_editorial_transiciones_cambio_check CHECK (
    (estado_anterior IS NULL AND estado_nuevo = 'BORRADOR')
    OR (estado_anterior = 'BORRADOR' AND estado_nuevo IN ('CONFIRMADO', 'CANCELADO'))
  ),
  CONSTRAINT tiraje_editorial_transiciones_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT tiraje_editorial_transiciones_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE UNIQUE INDEX tiraje_editorial_transiciones_inicial_uq
  ON tiraje_editorial_transiciones (tiraje_editorial_id)
  WHERE estado_anterior IS NULL;
CREATE INDEX tiraje_editorial_transiciones_tiraje_idx
  ON tiraje_editorial_transiciones (tiraje_editorial_id, id);
CREATE TRIGGER tiraje_editorial_transiciones_inmutables_trg
  BEFORE UPDATE OR DELETE ON tiraje_editorial_transiciones
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();

ALTER TABLE inventario_movimientos
  ADD COLUMN tiraje_editorial_id BIGINT;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_tiraje_editorial_fk
    FOREIGN KEY (tiraje_editorial_id, producto_id)
    REFERENCES tirajes_editoriales(id, producto_id)
    ON DELETE RESTRICT;

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_tipo_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_tipo_check CHECK (
    tipo IN (
      'INICIAL', 'AJUSTE', 'VENTA', 'CANCELACION', 'DEVOLUCION',
      'RESERVA', 'LIBERACION_RESERVA', 'EXPIRACION_RESERVA', 'CONSUMO_RESERVA',
      'RECEPCION_COMPRA', 'DEVOLUCION_PROVEEDOR', 'CONTEO', 'TIRAJE_EDITORIAL'
    )
  );
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_tiraje_aislamiento_check CHECK (
    (tipo = 'TIRAJE_EDITORIAL' AND tiraje_editorial_id IS NOT NULL)
    OR (tipo <> 'TIRAJE_EDITORIAL' AND tiraje_editorial_id IS NULL)
  );

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_origen_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_origen_check CHECK (
    (
      tipo = 'INICIAL'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
    )
    OR (
      tipo = 'AJUSTE'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
    )
    OR (
      tipo = 'VENTA'
      AND venta_id IS NOT NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = 0
    )
    OR (
      tipo = 'CANCELACION'
      AND venta_id IS NULL AND cancelacion_id IS NOT NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
    )
    OR (
      tipo = 'DEVOLUCION'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NOT NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
    )
    OR (
      tipo = 'RESERVA'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico = 0 AND delta_reservado > 0
    )
    OR (
      tipo IN ('LIBERACION_RESERVA', 'EXPIRACION_RESERVA')
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico = 0 AND delta_reservado < 0
    )
    OR (
      tipo = 'CONSUMO_RESERVA'
      AND venta_id IS NOT NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = delta_fisico
    )
    OR (
      tipo = 'RECEPCION_COMPRA'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NOT NULL AND detalle_recepcion_compra_id IS NOT NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'DEVOLUCION_PROVEEDOR'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NOT NULL AND detalle_devolucion_proveedor_id IS NOT NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'CONTEO'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NOT NULL AND detalle_conteo_inventario_id IS NOT NULL
      AND delta_fisico <> 0 AND delta_reservado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'TIRAJE_EDITORIAL'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NOT NULL
      AND delta_fisico > 0 AND delta_reservado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
  );

CREATE UNIQUE INDEX inventario_movimientos_tiraje_uq
  ON inventario_movimientos (tiraje_editorial_id)
  WHERE tipo = 'TIRAJE_EDITORIAL';
CREATE INDEX inventario_movimientos_tiraje_idx
  ON inventario_movimientos (tiraje_editorial_id, id)
  WHERE tiraje_editorial_id IS NOT NULL;

CREATE OR REPLACE FUNCTION validar_cadena_transicion_tiraje()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_ultimo VARCHAR(12);
BEGIN
  SELECT estado_nuevo INTO v_ultimo
  FROM tiraje_editorial_transiciones
  WHERE tiraje_editorial_id=NEW.tiraje_editorial_id
  ORDER BY id DESC LIMIT 1;
  IF NEW.estado_anterior IS DISTINCT FROM v_ultimo THEN
    RAISE EXCEPTION 'La transición del tiraje no continúa el historial vigente.'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER tiraje_editorial_transiciones_cadena_trg
  BEFORE INSERT ON tiraje_editorial_transiciones
  FOR EACH ROW EXECUTE FUNCTION validar_cadena_transicion_tiraje();

CREATE OR REPLACE FUNCTION proteger_tiraje_editorial()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Los tirajes no se eliminan; deben cancelarse.' USING ERRCODE = '55000';
  END IF;
  IF NEW.id <> OLD.id OR NEW.folio <> OLD.folio
     OR NEW.obra_editorial_id <> OLD.obra_editorial_id
     OR NEW.producto_id <> OLD.producto_id
     OR NEW.obra_folio <> OLD.obra_folio OR NEW.obra_titulo <> OLD.obra_titulo
     OR NEW.producto_sku <> OLD.producto_sku
     OR NEW.producto_titulo <> OLD.producto_titulo
     OR NEW.producto_isbn IS DISTINCT FROM OLD.producto_isbn
     OR NEW.creado_por_usuario_id <> OLD.creado_por_usuario_id
     OR NEW.creado_en <> OLD.creado_en THEN
    RAISE EXCEPTION 'No se puede modificar la identidad o snapshots del tiraje.'
      USING ERRCODE = '55000';
  END IF;
  IF OLD.estado <> 'BORRADOR' THEN
    RAISE EXCEPTION 'Un tiraje finalizado es inmutable.' USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER tirajes_editoriales_proteger_trg
  BEFORE UPDATE OR DELETE ON tirajes_editoriales
  FOR EACH ROW EXECUTE FUNCTION proteger_tiraje_editorial();

CREATE OR REPLACE FUNCTION validar_costo_tiraje_borrador()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_tiraje_id BIGINT;
  v_estado VARCHAR(12);
BEGIN
  v_tiraje_id := CASE WHEN TG_OP='DELETE' THEN OLD.tiraje_editorial_id ELSE NEW.tiraje_editorial_id END;
  SELECT estado INTO v_estado
  FROM tirajes_editoriales WHERE id=v_tiraje_id FOR KEY SHARE;
  IF v_estado IS DISTINCT FROM 'BORRADOR' THEN
    RAISE EXCEPTION 'Sólo un tiraje en borrador admite cambios de costos.'
      USING ERRCODE = '55000';
  END IF;
  IF TG_OP='UPDATE' AND NEW.tiraje_editorial_id <> OLD.tiraje_editorial_id THEN
    RAISE EXCEPTION 'Un costo no puede cambiar de tiraje.' USING ERRCODE = '55000';
  END IF;
  RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END
$function$;

CREATE TRIGGER tiraje_editorial_costos_borrador_trg
  BEFORE INSERT OR UPDATE OR DELETE ON tiraje_editorial_costos
  FOR EACH ROW EXECUTE FUNCTION validar_costo_tiraje_borrador();

CREATE OR REPLACE FUNCTION validar_tiraje_editorial_conciliado(p_tiraje_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $function$
DECLARE
  v_tiraje tirajes_editoriales%ROWTYPE;
  v_ultimo_estado VARCHAR(12);
  v_costo_total NUMERIC(14,2);
  v_mov inventario_movimientos%ROWTYPE;
BEGIN
  SELECT * INTO v_tiraje FROM tirajes_editoriales WHERE id=p_tiraje_id;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT estado_nuevo INTO v_ultimo_estado
  FROM tiraje_editorial_transiciones
  WHERE tiraje_editorial_id=p_tiraje_id ORDER BY id DESC LIMIT 1;
  IF v_ultimo_estado IS DISTINCT FROM v_tiraje.estado THEN
    RAISE EXCEPTION 'El historial del tiraje % no coincide con su estado.', p_tiraje_id
      USING ERRCODE = '23514';
  END IF;

  SELECT COALESCE(ROUND(SUM(monto), 2), 0) INTO v_costo_total
  FROM tiraje_editorial_costos WHERE tiraje_editorial_id=p_tiraje_id;
  SELECT * INTO v_mov FROM inventario_movimientos
  WHERE tiraje_editorial_id=p_tiraje_id;

  IF v_tiraje.estado IN ('BORRADOR', 'CANCELADO') THEN
    IF FOUND THEN
      RAISE EXCEPTION 'El tiraje % no confirmado contiene inventario.', p_tiraje_id
        USING ERRCODE = '23514';
    END IF;
    RETURN;
  END IF;

  IF v_costo_total <= 0 OR v_tiraje.costo_total_confirmado <> v_costo_total
     OR v_tiraje.costo_unitario_confirmado <> ROUND(v_costo_total / v_tiraje.cantidad, 2)
     OR v_tiraje.stock_resultante <> v_tiraje.stock_anterior + v_tiraje.cantidad
     OR v_mov.id IS NULL OR v_mov.producto_id <> v_tiraje.producto_id
     OR v_mov.tipo <> 'TIRAJE_EDITORIAL'
     OR v_mov.delta_fisico <> v_tiraje.cantidad OR v_mov.delta_reservado <> 0
     OR v_mov.stock_fisico_resultante <> v_tiraje.stock_resultante
     OR v_mov.usuario_id <> v_tiraje.confirmado_por_usuario_id THEN
    RAISE EXCEPTION 'El tiraje confirmado % no está conciliado.', p_tiraje_id
      USING ERRCODE = '23514';
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_tiraje_editorial_conciliado_trg()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_id BIGINT;
BEGIN
  IF TG_TABLE_NAME='tirajes_editoriales' THEN
    v_id := CASE WHEN TG_OP='DELETE' THEN OLD.id ELSE NEW.id END;
  ELSE
    v_id := CASE WHEN TG_OP='DELETE' THEN OLD.tiraje_editorial_id ELSE NEW.tiraje_editorial_id END;
  END IF;
  PERFORM validar_tiraje_editorial_conciliado(v_id);
  RETURN NULL;
END
$function$;

CREATE CONSTRAINT TRIGGER tirajes_editoriales_conciliacion_trg
  AFTER INSERT OR UPDATE ON tirajes_editoriales DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_tiraje_editorial_conciliado_trg();
CREATE CONSTRAINT TRIGGER tiraje_editorial_transiciones_conciliacion_trg
  AFTER INSERT ON tiraje_editorial_transiciones DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_tiraje_editorial_conciliado_trg();
CREATE CONSTRAINT TRIGGER inventario_tiraje_conciliacion_trg
  AFTER INSERT ON inventario_movimientos DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW WHEN (NEW.tiraje_editorial_id IS NOT NULL)
  EXECUTE FUNCTION validar_tiraje_editorial_conciliado_trg();

