-- Regalías y estados de cuenta editoriales calculados desde las ventas,
-- cancelaciones y devoluciones reales. Se agrega el IVA como snapshot de la
-- línea de venta para no depender de cambios posteriores en el producto.

ALTER TABLE detalle_ventas
  ADD COLUMN iva_porcentaje NUMERIC(5,2),
  ADD COLUMN producto_sku VARCHAR(24),
  ADD COLUMN producto_titulo VARCHAR(160);
UPDATE detalle_ventas dv
SET iva_porcentaje=p.iva,
    producto_sku=p.sku,
    producto_titulo=p.titulo
FROM productos p
WHERE p.id=dv.producto_id;
ALTER TABLE detalle_ventas
  ALTER COLUMN iva_porcentaje SET NOT NULL,
  ALTER COLUMN producto_sku SET NOT NULL,
  ALTER COLUMN producto_titulo SET NOT NULL,
  ADD CONSTRAINT detalle_ventas_iva_porcentaje_check
    CHECK (iva_porcentaje BETWEEN 0 AND 100),
  ADD CONSTRAINT detalle_ventas_producto_snapshot_check
    CHECK (btrim(producto_sku) <> '' AND btrim(producto_titulo) <> '');

CREATE SEQUENCE liquidaciones_regalias_folio_seq START WITH 1;

CREATE TABLE liquidaciones_regalias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('REG-' || LPAD(nextval('liquidaciones_regalias_folio_seq')::text, 10, '0')),
  contrato_editorial_id BIGINT NOT NULL
    REFERENCES contratos_editoriales(id) ON DELETE RESTRICT,
  version INTEGER NOT NULL,
  reemplaza_liquidacion_id BIGINT REFERENCES liquidaciones_regalias(id) ON DELETE RESTRICT,
  periodo_desde DATE NOT NULL,
  periodo_hasta DATE NOT NULL,
  zona_horaria VARCHAR(80) NOT NULL,
  estado VARCHAR(12) NOT NULL DEFAULT 'BORRADOR',
  contrato_folio VARCHAR(24) NOT NULL,
  obra_editorial_id BIGINT NOT NULL REFERENCES obras_editoriales(id) ON DELETE RESTRICT,
  obra_folio VARCHAR(24) NOT NULL,
  obra_titulo VARCHAR(240) NOT NULL,
  colaborador_editorial_id BIGINT NOT NULL
    REFERENCES colaboradores_editoriales(id) ON DELETE RESTRICT,
  colaborador_nombre VARCHAR(160) NOT NULL,
  base_regalia VARCHAR(20) NOT NULL,
  porcentaje_regalia NUMERIC(7,4) NOT NULL,
  moneda CHAR(3) NOT NULL,
  unidades_netas INTEGER NOT NULL,
  base_regalia_total NUMERIC(14,2) NOT NULL,
  regalia_bruta NUMERIC(14,2) NOT NULL,
  saldo_editorial_anterior NUMERIC(14,2) NOT NULL DEFAULT 0,
  saldo_editorial_aplicado NUMERIC(14,2) NOT NULL DEFAULT 0,
  saldo_editorial_nuevo NUMERIC(14,2) NOT NULL DEFAULT 0,
  anticipo_pendiente_antes NUMERIC(14,2) NOT NULL DEFAULT 0,
  anticipo_aplicado NUMERIC(14,2) NOT NULL DEFAULT 0,
  anticipo_pendiente_despues NUMERIC(14,2) NOT NULL DEFAULT 0,
  importe_pagable NUMERIC(14,2) NOT NULL DEFAULT 0,
  notas TEXT,
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  emitido_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  emitido_en TIMESTAMPTZ,
  pagado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  pagado_en TIMESTAMPTZ,
  pago_referencia VARCHAR(160),
  cancelado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  cancelado_en TIMESTAMPTZ,
  cancelacion_motivo VARCHAR(500),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT liquidaciones_regalias_version_check CHECK (version > 0),
  CONSTRAINT liquidaciones_regalias_periodo_check CHECK (periodo_hasta > periodo_desde),
  CONSTRAINT liquidaciones_regalias_zona_check CHECK (btrim(zona_horaria) <> ''),
  CONSTRAINT liquidaciones_regalias_estado_check CHECK (
    estado IN ('BORRADOR', 'EMITIDA', 'PAGADA', 'CANCELADA')
  ),
  CONSTRAINT liquidaciones_regalias_snapshots_check CHECK (
    btrim(contrato_folio) <> '' AND btrim(obra_folio) <> ''
    AND btrim(obra_titulo) <> '' AND btrim(colaborador_nombre) <> ''
  ),
  CONSTRAINT liquidaciones_regalias_base_check CHECK (
    base_regalia IN ('VENTA_NETA', 'PRECIO_LISTA')
  ),
  CONSTRAINT liquidaciones_regalias_porcentaje_check CHECK (
    porcentaje_regalia BETWEEN 0 AND 100
  ),
  CONSTRAINT liquidaciones_regalias_moneda_check CHECK (moneda ~ '^[A-Z]{3}$'),
  CONSTRAINT liquidaciones_regalias_saldos_check CHECK (
    saldo_editorial_anterior >= 0
    AND saldo_editorial_aplicado >= 0
    AND saldo_editorial_nuevo >= 0
    AND saldo_editorial_aplicado <= saldo_editorial_anterior
    AND saldo_editorial_aplicado <= GREATEST(regalia_bruta, 0)
    AND saldo_editorial_nuevo = ROUND(
      saldo_editorial_anterior - saldo_editorial_aplicado
      + GREATEST(-regalia_bruta, 0),
      2
    )
  ),
  CONSTRAINT liquidaciones_regalias_anticipo_check CHECK (
    anticipo_pendiente_antes >= 0 AND anticipo_aplicado >= 0
    AND anticipo_pendiente_despues >= 0
    AND anticipo_aplicado <= anticipo_pendiente_antes
    AND anticipo_aplicado <= GREATEST(regalia_bruta - saldo_editorial_aplicado, 0)
    AND anticipo_pendiente_despues = ROUND(
      anticipo_pendiente_antes - anticipo_aplicado,
      2
    )
  ),
  CONSTRAINT liquidaciones_regalias_pagable_check CHECK (
    importe_pagable >= 0
    AND importe_pagable = GREATEST(
      ROUND(regalia_bruta - saldo_editorial_aplicado - anticipo_aplicado, 2),
      0
    )
  ),
  CONSTRAINT liquidaciones_regalias_notas_check CHECK (
    notas IS NULL OR btrim(notas) <> ''
  ),
  CONSTRAINT liquidaciones_regalias_pago_referencia_check CHECK (
    pago_referencia IS NULL OR btrim(pago_referencia) <> ''
  ),
  CONSTRAINT liquidaciones_regalias_cancelacion_motivo_check CHECK (
    cancelacion_motivo IS NULL OR btrim(cancelacion_motivo) <> ''
  ),
  CONSTRAINT liquidaciones_regalias_efectos_estado_check CHECK (
    (
      estado='BORRADOR'
      AND emitido_por_usuario_id IS NULL AND emitido_en IS NULL
      AND pagado_por_usuario_id IS NULL AND pagado_en IS NULL AND pago_referencia IS NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado='EMITIDA'
      AND emitido_por_usuario_id IS NOT NULL AND emitido_en IS NOT NULL
      AND pagado_por_usuario_id IS NULL AND pagado_en IS NULL AND pago_referencia IS NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado='PAGADA'
      AND emitido_por_usuario_id IS NOT NULL AND emitido_en IS NOT NULL
      AND pagado_por_usuario_id IS NOT NULL AND pagado_en IS NOT NULL
      AND pago_referencia IS NOT NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado='CANCELADA'
      AND pagado_por_usuario_id IS NULL AND pagado_en IS NULL AND pago_referencia IS NULL
      AND cancelado_por_usuario_id IS NOT NULL AND cancelado_en IS NOT NULL
      AND cancelacion_motivo IS NOT NULL
      AND (
        (emitido_por_usuario_id IS NULL AND emitido_en IS NULL)
        OR (emitido_por_usuario_id IS NOT NULL AND emitido_en IS NOT NULL)
      )
    )
  ),
  CONSTRAINT liquidaciones_regalias_periodo_version_uq
    UNIQUE (contrato_editorial_id, periodo_desde, periodo_hasta, version)
);

CREATE INDEX liquidaciones_regalias_contrato_periodo_idx
  ON liquidaciones_regalias (
    contrato_editorial_id, periodo_hasta DESC, periodo_desde DESC, version DESC
  );
CREATE INDEX liquidaciones_regalias_colaborador_estado_idx
  ON liquidaciones_regalias (colaborador_editorial_id, estado, periodo_hasta DESC, id DESC);
CREATE INDEX liquidaciones_regalias_obra_estado_idx
  ON liquidaciones_regalias (obra_editorial_id, estado, periodo_hasta DESC, id DESC);
CREATE INDEX liquidaciones_regalias_estado_fecha_idx
  ON liquidaciones_regalias (estado, actualizado_en DESC, id DESC);
CREATE TRIGGER liquidaciones_regalias_actualizado_en_trg
  BEFORE UPDATE ON liquidaciones_regalias
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE TABLE detalle_liquidaciones_regalias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  liquidacion_regalia_id BIGINT NOT NULL
    REFERENCES liquidaciones_regalias(id) ON DELETE RESTRICT,
  evento_clave VARCHAR(160) NOT NULL,
  tipo_evento VARCHAR(12) NOT NULL,
  movimiento_id INTEGER NOT NULL REFERENCES movimientos(id) ON DELETE RESTRICT,
  venta_id INTEGER NOT NULL REFERENCES ventas(id) ON DELETE RESTRICT,
  detalle_venta_id INTEGER NOT NULL REFERENCES detalle_ventas(id) ON DELETE RESTRICT,
  devolucion_id BIGINT REFERENCES devoluciones(id) ON DELETE RESTRICT,
  detalle_devolucion_id BIGINT REFERENCES detalle_devoluciones(id) ON DELETE RESTRICT,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  producto_sku VARCHAR(24) NOT NULL,
  producto_titulo VARCHAR(160) NOT NULL,
  fecha_evento TIMESTAMPTZ NOT NULL,
  canal VARCHAR(3) NOT NULL,
  cantidad_neta INTEGER NOT NULL,
  precio_lista NUMERIC(12,2) NOT NULL,
  descuento_unitario NUMERIC(12,2) NOT NULL,
  precio_unitario NUMERIC(12,2) NOT NULL,
  iva_porcentaje NUMERIC(5,2) NOT NULL,
  importe_con_iva NUMERIC(14,2) NOT NULL,
  base_venta_neta NUMERIC(14,2) NOT NULL,
  base_precio_lista NUMERIC(14,2) NOT NULL,
  base_regalia NUMERIC(14,2) NOT NULL,
  porcentaje_regalia NUMERIC(7,4) NOT NULL,
  importe_regalia NUMERIC(14,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT detalle_liquidaciones_evento_clave_check CHECK (btrim(evento_clave) <> ''),
  CONSTRAINT detalle_liquidaciones_tipo_check CHECK (
    tipo_evento IN ('VENTA', 'CANCELACION', 'DEVOLUCION')
  ),
  CONSTRAINT detalle_liquidaciones_origen_check CHECK (
    (
      tipo_evento IN ('VENTA', 'CANCELACION')
      AND devolucion_id IS NULL AND detalle_devolucion_id IS NULL
    )
    OR (
      tipo_evento='DEVOLUCION'
      AND devolucion_id IS NOT NULL AND detalle_devolucion_id IS NOT NULL
    )
  ),
  CONSTRAINT detalle_liquidaciones_producto_check CHECK (
    btrim(producto_sku) <> '' AND btrim(producto_titulo) <> ''
  ),
  CONSTRAINT detalle_liquidaciones_canal_check CHECK (canal IN ('POS', 'WEB')),
  CONSTRAINT detalle_liquidaciones_cantidad_check CHECK (
    cantidad_neta <> 0
    AND (
      (tipo_evento='VENTA' AND cantidad_neta > 0)
      OR (tipo_evento IN ('CANCELACION','DEVOLUCION') AND cantidad_neta < 0)
    )
  ),
  CONSTRAINT detalle_liquidaciones_precios_check CHECK (
    precio_lista >= 0 AND descuento_unitario >= 0
    AND precio_unitario >= 0 AND iva_porcentaje BETWEEN 0 AND 100
  ),
  CONSTRAINT detalle_liquidaciones_signos_check CHECK (
    (tipo_evento='VENTA' AND importe_con_iva >= 0
      AND base_venta_neta >= 0 AND base_precio_lista >= 0)
    OR (tipo_evento IN ('CANCELACION','DEVOLUCION') AND importe_con_iva <= 0
      AND base_venta_neta <= 0 AND base_precio_lista <= 0)
  ),
  CONSTRAINT detalle_liquidaciones_porcentaje_check CHECK (
    porcentaje_regalia BETWEEN 0 AND 100
  ),
  CONSTRAINT detalle_liquidaciones_importe_check CHECK (
    importe_regalia = ROUND(base_regalia * porcentaje_regalia / 100, 2)
  ),
  CONSTRAINT detalle_liquidaciones_evento_uq
    UNIQUE (liquidacion_regalia_id, evento_clave)
);

CREATE INDEX detalle_liquidaciones_regalia_idx
  ON detalle_liquidaciones_regalias (liquidacion_regalia_id, fecha_evento, id);
CREATE INDEX detalle_liquidaciones_producto_idx
  ON detalle_liquidaciones_regalias (producto_id, fecha_evento, id);
CREATE INDEX detalle_liquidaciones_movimiento_idx
  ON detalle_liquidaciones_regalias (movimiento_id, id);
CREATE TRIGGER detalle_liquidaciones_regalias_inmutable_trg
  BEFORE UPDATE OR DELETE ON detalle_liquidaciones_regalias
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();

CREATE TABLE liquidacion_regalia_transiciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  liquidacion_regalia_id BIGINT NOT NULL
    REFERENCES liquidaciones_regalias(id) ON DELETE RESTRICT,
  estado_anterior VARCHAR(12),
  estado_nuevo VARCHAR(12) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(500) NOT NULL,
  referencia VARCHAR(160),
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT liquidacion_regalia_transiciones_anterior_check CHECK (
    estado_anterior IS NULL OR estado_anterior IN ('BORRADOR','EMITIDA','PAGADA','CANCELADA')
  ),
  CONSTRAINT liquidacion_regalia_transiciones_nuevo_check CHECK (
    estado_nuevo IN ('BORRADOR','EMITIDA','PAGADA','CANCELADA')
  ),
  CONSTRAINT liquidacion_regalia_transiciones_cambio_check CHECK (
    (estado_anterior IS NULL AND estado_nuevo='BORRADOR')
    OR (estado_anterior='BORRADOR' AND estado_nuevo IN ('EMITIDA','CANCELADA'))
    OR (estado_anterior='EMITIDA' AND estado_nuevo IN ('PAGADA','CANCELADA'))
  ),
  CONSTRAINT liquidacion_regalia_transiciones_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT liquidacion_regalia_transiciones_referencia_check CHECK (
    referencia IS NULL OR btrim(referencia) <> ''
  ),
  CONSTRAINT liquidacion_regalia_transiciones_pago_check CHECK (
    (estado_nuevo='PAGADA' AND referencia IS NOT NULL)
    OR (estado_nuevo<>'PAGADA' AND referencia IS NULL)
  ),
  CONSTRAINT liquidacion_regalia_transiciones_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE UNIQUE INDEX liquidacion_regalia_transiciones_inicial_uq
  ON liquidacion_regalia_transiciones (liquidacion_regalia_id)
  WHERE estado_anterior IS NULL;
CREATE INDEX liquidacion_regalia_transiciones_liquidacion_idx
  ON liquidacion_regalia_transiciones (liquidacion_regalia_id, id);
CREATE TRIGGER liquidacion_regalia_transiciones_inmutable_trg
  BEFORE UPDATE OR DELETE ON liquidacion_regalia_transiciones
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();

CREATE OR REPLACE FUNCTION validar_periodo_liquidacion_regalia()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  PERFORM pg_advisory_xact_lock(
    hashtextextended('LIQUIDACION_REGALIA:' || NEW.contrato_editorial_id::text, 0)
  );
  IF EXISTS (
    SELECT 1 FROM liquidaciones_regalias l
    WHERE l.contrato_editorial_id=NEW.contrato_editorial_id
      AND l.estado <> 'CANCELADA'
      AND daterange(l.periodo_desde, l.periodo_hasta, '[)')
          && daterange(NEW.periodo_desde, NEW.periodo_hasta, '[)')
  ) THEN
    RAISE EXCEPTION 'El periodo se superpone con otra liquidación vigente.'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER liquidaciones_regalias_periodo_trg
  BEFORE INSERT ON liquidaciones_regalias
  FOR EACH ROW EXECUTE FUNCTION validar_periodo_liquidacion_regalia();

CREATE OR REPLACE FUNCTION validar_cadena_transicion_liquidacion_regalia()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_ultimo VARCHAR(12);
BEGIN
  SELECT estado_nuevo INTO v_ultimo
  FROM liquidacion_regalia_transiciones
  WHERE liquidacion_regalia_id=NEW.liquidacion_regalia_id
  ORDER BY id DESC LIMIT 1;
  IF NEW.estado_anterior IS DISTINCT FROM v_ultimo THEN
    RAISE EXCEPTION 'La transición de la liquidación no continúa el historial.'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER liquidacion_regalia_transiciones_cadena_trg
  BEFORE INSERT ON liquidacion_regalia_transiciones
  FOR EACH ROW EXECUTE FUNCTION validar_cadena_transicion_liquidacion_regalia();

CREATE OR REPLACE FUNCTION proteger_liquidacion_regalia()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP='DELETE' THEN
    RAISE EXCEPTION 'Las liquidaciones no se eliminan; deben cancelarse.'
      USING ERRCODE = '55000';
  END IF;
  IF NEW.id <> OLD.id OR NEW.folio <> OLD.folio
     OR NEW.contrato_editorial_id <> OLD.contrato_editorial_id
     OR NEW.version <> OLD.version
     OR NEW.reemplaza_liquidacion_id IS DISTINCT FROM OLD.reemplaza_liquidacion_id
     OR NEW.periodo_desde <> OLD.periodo_desde OR NEW.periodo_hasta <> OLD.periodo_hasta
     OR NEW.zona_horaria <> OLD.zona_horaria
     OR NEW.contrato_folio <> OLD.contrato_folio
     OR NEW.obra_editorial_id <> OLD.obra_editorial_id
     OR NEW.obra_folio <> OLD.obra_folio OR NEW.obra_titulo <> OLD.obra_titulo
     OR NEW.colaborador_editorial_id <> OLD.colaborador_editorial_id
     OR NEW.colaborador_nombre <> OLD.colaborador_nombre
     OR NEW.base_regalia <> OLD.base_regalia
     OR NEW.porcentaje_regalia <> OLD.porcentaje_regalia
     OR NEW.moneda <> OLD.moneda OR NEW.unidades_netas <> OLD.unidades_netas
     OR NEW.base_regalia_total <> OLD.base_regalia_total
     OR NEW.regalia_bruta <> OLD.regalia_bruta
     OR NEW.saldo_editorial_anterior <> OLD.saldo_editorial_anterior
     OR NEW.saldo_editorial_aplicado <> OLD.saldo_editorial_aplicado
     OR NEW.saldo_editorial_nuevo <> OLD.saldo_editorial_nuevo
     OR NEW.anticipo_pendiente_antes <> OLD.anticipo_pendiente_antes
     OR NEW.anticipo_aplicado <> OLD.anticipo_aplicado
     OR NEW.anticipo_pendiente_despues <> OLD.anticipo_pendiente_despues
     OR NEW.importe_pagable <> OLD.importe_pagable
     OR NEW.notas IS DISTINCT FROM OLD.notas
     OR NEW.creado_por_usuario_id <> OLD.creado_por_usuario_id
     OR NEW.creado_en <> OLD.creado_en THEN
    RAISE EXCEPTION 'El cálculo y los snapshots de la liquidación son inmutables.'
      USING ERRCODE = '55000';
  END IF;
  IF OLD.estado IN ('PAGADA','CANCELADA') THEN
    RAISE EXCEPTION 'Una liquidación finalizada es inmutable.' USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER liquidaciones_regalias_proteger_trg
  BEFORE UPDATE OR DELETE ON liquidaciones_regalias
  FOR EACH ROW EXECUTE FUNCTION proteger_liquidacion_regalia();

CREATE OR REPLACE FUNCTION validar_liquidacion_regalia_conciliada(p_liquidacion_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $function$
DECLARE
  v_liquidacion liquidaciones_regalias%ROWTYPE;
  v_ultimo VARCHAR(12);
  v_unidades INTEGER;
  v_base NUMERIC(14,2);
  v_regalia NUMERIC(14,2);
BEGIN
  SELECT * INTO v_liquidacion FROM liquidaciones_regalias WHERE id=p_liquidacion_id;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT estado_nuevo INTO v_ultimo
  FROM liquidacion_regalia_transiciones
  WHERE liquidacion_regalia_id=p_liquidacion_id ORDER BY id DESC LIMIT 1;
  IF v_ultimo IS DISTINCT FROM v_liquidacion.estado THEN
    RAISE EXCEPTION 'El historial de la liquidación % no coincide con su estado.', p_liquidacion_id
      USING ERRCODE = '23514';
  END IF;
  SELECT COALESCE(SUM(cantidad_neta),0)::int,
         COALESCE(ROUND(SUM(base_regalia),2),0),
         COALESCE(ROUND(SUM(importe_regalia),2),0)
  INTO v_unidades, v_base, v_regalia
  FROM detalle_liquidaciones_regalias
  WHERE liquidacion_regalia_id=p_liquidacion_id;
  IF v_unidades <> v_liquidacion.unidades_netas
     OR v_base <> v_liquidacion.base_regalia_total
     OR v_regalia <> v_liquidacion.regalia_bruta THEN
    RAISE EXCEPTION 'El detalle de la liquidación % no está conciliado.', p_liquidacion_id
      USING ERRCODE = '23514';
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_liquidacion_regalia_conciliada_trg()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_id BIGINT;
BEGIN
  IF TG_TABLE_NAME='liquidaciones_regalias' THEN
    v_id := CASE WHEN TG_OP='DELETE' THEN OLD.id ELSE NEW.id END;
  ELSE
    v_id := CASE WHEN TG_OP='DELETE' THEN OLD.liquidacion_regalia_id ELSE NEW.liquidacion_regalia_id END;
  END IF;
  PERFORM validar_liquidacion_regalia_conciliada(v_id);
  RETURN NULL;
END
$function$;

CREATE CONSTRAINT TRIGGER liquidaciones_regalias_conciliacion_trg
  AFTER INSERT OR UPDATE ON liquidaciones_regalias DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_liquidacion_regalia_conciliada_trg();
CREATE CONSTRAINT TRIGGER detalle_liquidaciones_regalias_conciliacion_trg
  AFTER INSERT ON detalle_liquidaciones_regalias DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_liquidacion_regalia_conciliada_trg();
CREATE CONSTRAINT TRIGGER liquidacion_regalia_transiciones_conciliacion_trg
  AFTER INSERT ON liquidacion_regalia_transiciones DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_liquidacion_regalia_conciliada_trg();
