-- Distribución y consignación editorial sobre clientes, precios e inventario comunes.
-- productos.stock conserva la existencia física en tienda; stock_consignado
-- identifica existencias propiedad de la empresa que están con un consignatario.

ALTER TABLE clientes
  ADD COLUMN tipo_comercial VARCHAR(16) NOT NULL DEFAULT 'CONSUMIDOR';
ALTER TABLE clientes
  ADD CONSTRAINT clientes_tipo_comercial_check CHECK (
    tipo_comercial IN ('CONSUMIDOR', 'LIBRERIA', 'DISTRIBUIDOR', 'INSTITUCION')
  );
CREATE INDEX clientes_tipo_comercial_activo_idx
  ON clientes (tipo_comercial, nombre, id) WHERE activo;

DROP VIEW IF EXISTS inventario_conciliacion;
ALTER TABLE productos
  ADD COLUMN stock_consignado INTEGER NOT NULL DEFAULT 0;
ALTER TABLE productos DROP CONSTRAINT productos_stock_reservado_check;
ALTER TABLE productos
  ADD CONSTRAINT productos_saldos_inventario_check CHECK (
    stock >= 0
    AND stock_reservado >= 0
    AND stock_consignado >= 0
    AND stock_reservado <= stock
  );

CREATE SEQUENCE consignaciones_editoriales_folio_seq START WITH 1;
CREATE SEQUENCE consignacion_operaciones_folio_seq START WITH 1;

CREATE TABLE consignaciones_editoriales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('CON-' || LPAD(nextval('consignaciones_editoriales_folio_seq')::text, 10, '0')),
  cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,
  cliente_nombre VARCHAR(120) NOT NULL,
  cliente_telefono VARCHAR(30),
  cliente_email VARCHAR(254),
  cliente_direccion TEXT,
  tipo_comercial VARCHAR(16) NOT NULL,
  segmento_precio VARCHAR(10) NOT NULL,
  fecha_envio_programada DATE NOT NULL,
  fecha_limite DATE,
  moneda CHAR(3) NOT NULL DEFAULT 'MXN',
  referencia VARCHAR(120),
  notas TEXT,
  estado VARCHAR(12) NOT NULL DEFAULT 'BORRADOR',
  creado_por_usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  enviado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  enviado_en TIMESTAMPTZ,
  cerrado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  cerrado_en TIMESTAMPTZ,
  cancelado_por_usuario_id INTEGER REFERENCES usuarios(id) ON DELETE RESTRICT,
  cancelado_en TIMESTAMPTZ,
  cancelacion_motivo VARCHAR(500),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT consignaciones_cliente_snapshot_check CHECK (
    btrim(cliente_nombre) <> ''
    AND (cliente_telefono IS NULL OR btrim(cliente_telefono) <> '')
    AND (cliente_email IS NULL OR btrim(cliente_email) <> '')
    AND (cliente_direccion IS NULL OR btrim(cliente_direccion) <> '')
  ),
  CONSTRAINT consignaciones_tipo_comercial_check CHECK (
    tipo_comercial IN ('LIBRERIA', 'DISTRIBUIDOR', 'INSTITUCION')
  ),
  CONSTRAINT consignaciones_segmento_check CHECK (segmento_precio = 'MAYOREO'),
  CONSTRAINT consignaciones_fecha_check CHECK (
    fecha_limite IS NULL OR fecha_limite >= fecha_envio_programada
  ),
  CONSTRAINT consignaciones_moneda_check CHECK (moneda ~ '^[A-Z]{3}$'),
  CONSTRAINT consignaciones_referencia_check CHECK (
    referencia IS NULL OR btrim(referencia) <> ''
  ),
  CONSTRAINT consignaciones_notas_check CHECK (notas IS NULL OR btrim(notas) <> ''),
  CONSTRAINT consignaciones_estado_check CHECK (
    estado IN ('BORRADOR', 'ENVIADA', 'PARCIAL', 'LIQUIDADA', 'CERRADA', 'CANCELADA')
  ),
  CONSTRAINT consignaciones_cancelacion_motivo_check CHECK (
    cancelacion_motivo IS NULL OR btrim(cancelacion_motivo) <> ''
  ),
  CONSTRAINT consignaciones_efectos_estado_check CHECK (
    (
      estado = 'BORRADOR'
      AND enviado_por_usuario_id IS NULL AND enviado_en IS NULL
      AND cerrado_por_usuario_id IS NULL AND cerrado_en IS NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado IN ('ENVIADA', 'PARCIAL', 'LIQUIDADA')
      AND enviado_por_usuario_id IS NOT NULL AND enviado_en IS NOT NULL
      AND cerrado_por_usuario_id IS NULL AND cerrado_en IS NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado = 'CERRADA'
      AND enviado_por_usuario_id IS NOT NULL AND enviado_en IS NOT NULL
      AND cerrado_por_usuario_id IS NOT NULL AND cerrado_en IS NOT NULL
      AND cancelado_por_usuario_id IS NULL AND cancelado_en IS NULL
      AND cancelacion_motivo IS NULL
    )
    OR (
      estado = 'CANCELADA'
      AND enviado_por_usuario_id IS NULL AND enviado_en IS NULL
      AND cerrado_por_usuario_id IS NULL AND cerrado_en IS NULL
      AND cancelado_por_usuario_id IS NOT NULL AND cancelado_en IS NOT NULL
      AND cancelacion_motivo IS NOT NULL
    )
  )
);

CREATE INDEX consignaciones_cliente_estado_idx
  ON consignaciones_editoriales (cliente_id, estado, creado_en DESC, id DESC);
CREATE INDEX consignaciones_tipo_estado_idx
  ON consignaciones_editoriales (tipo_comercial, estado, creado_en DESC, id DESC);
CREATE INDEX consignaciones_estado_fecha_idx
  ON consignaciones_editoriales (estado, fecha_envio_programada DESC, id DESC);
CREATE TRIGGER consignaciones_actualizado_en_trg
  BEFORE UPDATE ON consignaciones_editoriales
  FOR EACH ROW EXECUTE FUNCTION marcar_actualizado_en();

CREATE TABLE consignacion_detalles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consignacion_editorial_id BIGINT NOT NULL
    REFERENCES consignaciones_editoriales(id) ON DELETE RESTRICT,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  producto_sku VARCHAR(24) NOT NULL,
  producto_titulo VARCHAR(160) NOT NULL,
  producto_isbn VARCHAR(17),
  cantidad_enviada INTEGER NOT NULL,
  cantidad_vendida INTEGER NOT NULL DEFAULT 0,
  cantidad_devuelta INTEGER NOT NULL DEFAULT 0,
  precio_lista NUMERIC(12,2) NOT NULL,
  descuento_unitario NUMERIC(12,2) NOT NULL,
  precio_unitario NUMERIC(12,2) NOT NULL,
  iva_porcentaje NUMERIC(5,2) NOT NULL,
  regla_precio_id BIGINT REFERENCES reglas_precio(id) ON DELETE RESTRICT,
  subtotal_enviado NUMERIC(14,2) NOT NULL,
  descuento_enviado NUMERIC(14,2) NOT NULL,
  iva_enviado NUMERIC(14,2) NOT NULL,
  importe_enviado NUMERIC(14,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT consignacion_detalles_producto_snapshot_check CHECK (
    btrim(producto_sku) <> '' AND btrim(producto_titulo) <> ''
    AND (producto_isbn IS NULL OR btrim(producto_isbn) <> '')
  ),
  CONSTRAINT consignacion_detalles_cantidades_check CHECK (
    cantidad_enviada > 0
    AND cantidad_vendida >= 0
    AND cantidad_devuelta >= 0
    AND cantidad_vendida + cantidad_devuelta <= cantidad_enviada
  ),
  CONSTRAINT consignacion_detalles_precios_check CHECK (
    precio_lista >= 0 AND descuento_unitario >= 0 AND precio_unitario >= 0
    AND precio_unitario = precio_lista - descuento_unitario
    AND iva_porcentaje BETWEEN 0 AND 100
  ),
  CONSTRAINT consignacion_detalles_importes_check CHECK (
    importe_enviado = ROUND(precio_unitario * cantidad_enviada, 2)
    AND descuento_enviado = ROUND(descuento_unitario * cantidad_enviada, 2)
    AND iva_enviado = ROUND(importe_enviado - subtotal_enviado, 2)
    AND subtotal_enviado = ROUND(importe_enviado / (1 + iva_porcentaje / 100), 2)
  ),
  CONSTRAINT consignacion_detalles_producto_uq
    UNIQUE (consignacion_editorial_id, producto_id),
  CONSTRAINT consignacion_detalles_compuesto_uq
    UNIQUE (id, consignacion_editorial_id, producto_id)
);

CREATE INDEX consignacion_detalles_producto_idx
  ON consignacion_detalles (producto_id, consignacion_editorial_id);

CREATE TABLE consignacion_operaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(24) NOT NULL UNIQUE
    DEFAULT ('COP-' || LPAD(nextval('consignacion_operaciones_folio_seq')::text, 10, '0')),
  consignacion_editorial_id BIGINT NOT NULL
    REFERENCES consignaciones_editoriales(id) ON DELETE RESTRICT,
  tipo VARCHAR(12) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  referencia VARCHAR(160),
  motivo VARCHAR(500) NOT NULL,
  subtotal NUMERIC(14,2) NOT NULL,
  descuento NUMERIC(14,2) NOT NULL,
  iva NUMERIC(14,2) NOT NULL,
  total NUMERIC(14,2) NOT NULL,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT consignacion_operaciones_tipo_check CHECK (
    tipo IN ('ENVIO', 'VENTA', 'DEVOLUCION')
  ),
  CONSTRAINT consignacion_operaciones_referencia_check CHECK (
    referencia IS NULL OR btrim(referencia) <> ''
  ),
  CONSTRAINT consignacion_operaciones_venta_referencia_check CHECK (
    tipo <> 'VENTA' OR referencia IS NOT NULL
  ),
  CONSTRAINT consignacion_operaciones_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT consignacion_operaciones_importes_check CHECK (
    subtotal >= 0 AND descuento >= 0 AND iva >= 0 AND total >= 0
    AND total = subtotal + iva
  ),
  CONSTRAINT consignacion_operaciones_origen_check CHECK (btrim(origen_clave) <> ''),
  CONSTRAINT consignacion_operaciones_compuesto_uq UNIQUE (id, consignacion_editorial_id)
);

CREATE INDEX consignacion_operaciones_documento_idx
  ON consignacion_operaciones (consignacion_editorial_id, creado_en, id);
CREATE INDEX consignacion_operaciones_tipo_fecha_idx
  ON consignacion_operaciones (tipo, creado_en DESC, id DESC);

CREATE TABLE consignacion_operacion_detalles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consignacion_operacion_id BIGINT NOT NULL,
  consignacion_editorial_id BIGINT NOT NULL,
  consignacion_detalle_id BIGINT NOT NULL,
  producto_id INTEGER NOT NULL,
  cantidad INTEGER NOT NULL,
  precio_lista NUMERIC(12,2) NOT NULL,
  descuento_unitario NUMERIC(12,2) NOT NULL,
  precio_unitario NUMERIC(12,2) NOT NULL,
  iva_porcentaje NUMERIC(5,2) NOT NULL,
  subtotal NUMERIC(14,2) NOT NULL,
  descuento NUMERIC(14,2) NOT NULL,
  iva NUMERIC(14,2) NOT NULL,
  importe NUMERIC(14,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT consignacion_operacion_detalles_operacion_fk
    FOREIGN KEY (consignacion_operacion_id, consignacion_editorial_id)
    REFERENCES consignacion_operaciones(id, consignacion_editorial_id)
    ON DELETE RESTRICT,
  CONSTRAINT consignacion_operacion_detalles_linea_fk
    FOREIGN KEY (consignacion_detalle_id, consignacion_editorial_id, producto_id)
    REFERENCES consignacion_detalles(id, consignacion_editorial_id, producto_id)
    ON DELETE RESTRICT,
  CONSTRAINT consignacion_operacion_detalles_cantidad_check CHECK (cantidad > 0),
  CONSTRAINT consignacion_operacion_detalles_precios_check CHECK (
    precio_lista >= 0 AND descuento_unitario >= 0 AND precio_unitario >= 0
    AND precio_unitario = precio_lista - descuento_unitario
    AND iva_porcentaje BETWEEN 0 AND 100
  ),
  CONSTRAINT consignacion_operacion_detalles_importes_check CHECK (
    importe = ROUND(precio_unitario * cantidad, 2)
    AND descuento = ROUND(descuento_unitario * cantidad, 2)
    AND subtotal = ROUND(importe / (1 + iva_porcentaje / 100), 2)
    AND iva = ROUND(importe - subtotal, 2)
  ),
  CONSTRAINT consignacion_operacion_detalles_linea_uq
    UNIQUE (consignacion_operacion_id, consignacion_detalle_id),
  CONSTRAINT consignacion_operacion_detalles_compuesto_uq
    UNIQUE (id, consignacion_operacion_id, producto_id)
);

CREATE INDEX consignacion_operacion_detalles_producto_idx
  ON consignacion_operacion_detalles (producto_id, consignacion_operacion_id);

CREATE TABLE consignacion_transiciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consignacion_editorial_id BIGINT NOT NULL
    REFERENCES consignaciones_editoriales(id) ON DELETE RESTRICT,
  estado_anterior VARCHAR(12),
  estado_nuevo VARCHAR(12) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  motivo VARCHAR(500) NOT NULL,
  origen_clave VARCHAR(180) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT consignacion_transiciones_anterior_check CHECK (
    estado_anterior IS NULL
    OR estado_anterior IN ('BORRADOR', 'ENVIADA', 'PARCIAL', 'LIQUIDADA', 'CERRADA', 'CANCELADA')
  ),
  CONSTRAINT consignacion_transiciones_nuevo_check CHECK (
    estado_nuevo IN ('BORRADOR', 'ENVIADA', 'PARCIAL', 'LIQUIDADA', 'CERRADA', 'CANCELADA')
  ),
  CONSTRAINT consignacion_transiciones_cambio_check CHECK (
    (estado_anterior IS NULL AND estado_nuevo='BORRADOR')
    OR (estado_anterior='BORRADOR' AND estado_nuevo IN ('ENVIADA', 'CANCELADA'))
    OR (estado_anterior='ENVIADA' AND estado_nuevo IN ('PARCIAL', 'LIQUIDADA'))
    OR (estado_anterior='PARCIAL' AND estado_nuevo='LIQUIDADA')
    OR (estado_anterior='LIQUIDADA' AND estado_nuevo='CERRADA')
  ),
  CONSTRAINT consignacion_transiciones_motivo_check CHECK (btrim(motivo) <> ''),
  CONSTRAINT consignacion_transiciones_origen_check CHECK (btrim(origen_clave) <> '')
);

CREATE UNIQUE INDEX consignacion_transiciones_inicial_uq
  ON consignacion_transiciones (consignacion_editorial_id)
  WHERE estado_anterior IS NULL;
CREATE INDEX consignacion_transiciones_documento_idx
  ON consignacion_transiciones (consignacion_editorial_id, id);

ALTER TABLE inventario_movimientos
  ADD COLUMN delta_consignado INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN stock_consignado_resultante INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN consignacion_operacion_id BIGINT,
  ADD COLUMN detalle_consignacion_operacion_id BIGINT;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_consignacion_detalle_fk
    FOREIGN KEY (
      detalle_consignacion_operacion_id, consignacion_operacion_id, producto_id
    ) REFERENCES consignacion_operacion_detalles(
      id, consignacion_operacion_id, producto_id
    ) ON DELETE RESTRICT;

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_delta_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_delta_check CHECK (
    tipo = 'INICIAL'
    OR delta_fisico <> 0 OR delta_reservado <> 0 OR delta_consignado <> 0
  );
ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_saldos_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_saldos_check CHECK (
    stock_fisico_resultante >= 0
    AND stock_reservado_resultante >= 0
    AND stock_consignado_resultante >= 0
    AND stock_reservado_resultante <= stock_fisico_resultante
  );
ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_inicial_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_inicial_check CHECK (
    tipo <> 'INICIAL'
    OR (
      actor='MIGRACION' AND usuario_id IS NULL
      AND delta_fisico >= 0 AND delta_reservado >= 0 AND delta_consignado=0
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
    )
  );
ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_ajuste_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_ajuste_check CHECK (
    tipo <> 'AJUSTE'
    OR (
      actor='USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo,'')) <> ''
      AND delta_fisico <> 0 AND delta_reservado=0 AND delta_consignado=0
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
    )
  );
ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_tipo_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_tipo_check CHECK (
    tipo IN (
      'INICIAL', 'AJUSTE', 'VENTA', 'CANCELACION', 'DEVOLUCION',
      'RESERVA', 'LIBERACION_RESERVA', 'EXPIRACION_RESERVA', 'CONSUMO_RESERVA',
      'RECEPCION_COMPRA', 'DEVOLUCION_PROVEEDOR', 'CONTEO', 'TIRAJE_EDITORIAL',
      'SALIDA_CONSIGNACION', 'VENTA_CONSIGNACION', 'DEVOLUCION_CONSIGNACION'
    )
  );
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_consignacion_aislamiento_check CHECK (
    (
      tipo IN ('SALIDA_CONSIGNACION', 'VENTA_CONSIGNACION', 'DEVOLUCION_CONSIGNACION')
      AND consignacion_operacion_id IS NOT NULL
      AND detalle_consignacion_operacion_id IS NOT NULL
    )
    OR (
      tipo NOT IN ('SALIDA_CONSIGNACION', 'VENTA_CONSIGNACION', 'DEVOLUCION_CONSIGNACION')
      AND consignacion_operacion_id IS NULL
      AND detalle_consignacion_operacion_id IS NULL
    )
  );

ALTER TABLE inventario_movimientos DROP CONSTRAINT inventario_movimientos_origen_check;
ALTER TABLE inventario_movimientos
  ADD CONSTRAINT inventario_movimientos_origen_check CHECK (
    (
      tipo IN ('INICIAL', 'AJUSTE')
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_consignado = 0
    )
    OR (
      tipo = 'VENTA'
      AND venta_id IS NOT NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = 0 AND delta_consignado = 0
    )
    OR (
      tipo = 'CANCELACION'
      AND venta_id IS NULL AND cancelacion_id IS NOT NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0 AND delta_consignado = 0
    )
    OR (
      tipo = 'DEVOLUCION'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NOT NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0 AND delta_consignado = 0
    )
    OR (
      tipo = 'RESERVA'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico = 0 AND delta_reservado > 0 AND delta_consignado = 0
    )
    OR (
      tipo IN ('LIBERACION_RESERVA', 'EXPIRACION_RESERVA')
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico = 0 AND delta_reservado < 0 AND delta_consignado = 0
    )
    OR (
      tipo = 'CONSUMO_RESERVA'
      AND venta_id IS NOT NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NOT NULL AND reserva_id IS NOT NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = delta_fisico AND delta_consignado = 0
    )
    OR (
      tipo = 'RECEPCION_COMPRA'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NOT NULL AND detalle_recepcion_compra_id IS NOT NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0 AND delta_consignado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'DEVOLUCION_PROVEEDOR'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NOT NULL AND detalle_devolucion_proveedor_id IS NOT NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = 0 AND delta_consignado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'CONTEO'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NOT NULL AND detalle_conteo_inventario_id IS NOT NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico <> 0 AND delta_reservado = 0 AND delta_consignado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'TIRAJE_EDITORIAL'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NOT NULL
      AND delta_fisico > 0 AND delta_reservado = 0 AND delta_consignado = 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'SALIDA_CONSIGNACION'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico < 0 AND delta_reservado = 0
      AND delta_consignado = -delta_fisico
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'VENTA_CONSIGNACION'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico = 0 AND delta_reservado = 0 AND delta_consignado < 0
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
    OR (
      tipo = 'DEVOLUCION_CONSIGNACION'
      AND venta_id IS NULL AND cancelacion_id IS NULL AND devolucion_id IS NULL
      AND pedido_id IS NULL AND reserva_id IS NULL
      AND recepcion_compra_id IS NULL AND detalle_recepcion_compra_id IS NULL
      AND devolucion_proveedor_id IS NULL AND detalle_devolucion_proveedor_id IS NULL
      AND conteo_inventario_id IS NULL AND detalle_conteo_inventario_id IS NULL
      AND tiraje_editorial_id IS NULL
      AND delta_fisico > 0 AND delta_reservado = 0
      AND delta_consignado = -delta_fisico
      AND actor = 'USUARIO' AND usuario_id IS NOT NULL
      AND btrim(COALESCE(motivo, '')) <> ''
    )
  );

CREATE UNIQUE INDEX inventario_movimientos_consignacion_detalle_uq
  ON inventario_movimientos (detalle_consignacion_operacion_id)
  WHERE detalle_consignacion_operacion_id IS NOT NULL;
CREATE INDEX inventario_movimientos_consignacion_operacion_idx
  ON inventario_movimientos (consignacion_operacion_id, id)
  WHERE consignacion_operacion_id IS NOT NULL;

CREATE OR REPLACE FUNCTION validar_cadena_transicion_consignacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_ultimo VARCHAR(12);
BEGIN
  SELECT estado_nuevo INTO v_ultimo
  FROM consignacion_transiciones
  WHERE consignacion_editorial_id=NEW.consignacion_editorial_id
  ORDER BY id DESC LIMIT 1;
  IF NEW.estado_anterior IS DISTINCT FROM v_ultimo THEN
    RAISE EXCEPTION 'La transición de consignación no continúa el historial vigente.'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER consignacion_transiciones_cadena_trg
  BEFORE INSERT ON consignacion_transiciones
  FOR EACH ROW EXECUTE FUNCTION validar_cadena_transicion_consignacion();

CREATE TRIGGER consignacion_transiciones_inmutables_trg
  BEFORE UPDATE OR DELETE ON consignacion_transiciones
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();
CREATE TRIGGER consignacion_operaciones_inmutables_trg
  BEFORE UPDATE OR DELETE ON consignacion_operaciones
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();
CREATE TRIGGER consignacion_operacion_detalles_inmutables_trg
  BEFORE UPDATE OR DELETE ON consignacion_operacion_detalles
  FOR EACH ROW EXECUTE FUNCTION impedir_mutacion_registro_auditoria();

CREATE OR REPLACE FUNCTION proteger_consignacion_editorial()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP='DELETE' THEN
    RAISE EXCEPTION 'Las consignaciones no se eliminan; deben cancelarse o cerrarse.'
      USING ERRCODE = '55000';
  END IF;
  IF ROW(
    NEW.id, NEW.folio, NEW.cliente_id, NEW.cliente_nombre,
    NEW.cliente_telefono, NEW.cliente_email, NEW.cliente_direccion,
    NEW.tipo_comercial, NEW.segmento_precio, NEW.fecha_envio_programada,
    NEW.fecha_limite, NEW.moneda, NEW.referencia, NEW.notas,
    NEW.creado_por_usuario_id, NEW.creado_en
  ) IS DISTINCT FROM ROW(
    OLD.id, OLD.folio, OLD.cliente_id, OLD.cliente_nombre,
    OLD.cliente_telefono, OLD.cliente_email, OLD.cliente_direccion,
    OLD.tipo_comercial, OLD.segmento_precio, OLD.fecha_envio_programada,
    OLD.fecha_limite, OLD.moneda, OLD.referencia, OLD.notas,
    OLD.creado_por_usuario_id, OLD.creado_en
  ) THEN
    RAISE EXCEPTION 'No se puede modificar la identidad o snapshots de la consignación.'
      USING ERRCODE = '55000';
  END IF;
  IF ROW(
    NEW.estado, NEW.enviado_por_usuario_id, NEW.enviado_en,
    NEW.cerrado_por_usuario_id, NEW.cerrado_en,
    NEW.cancelado_por_usuario_id, NEW.cancelado_en, NEW.cancelacion_motivo
  ) IS DISTINCT FROM ROW(
    OLD.estado, OLD.enviado_por_usuario_id, OLD.enviado_en,
    OLD.cerrado_por_usuario_id, OLD.cerrado_en,
    OLD.cancelado_por_usuario_id, OLD.cancelado_en, OLD.cancelacion_motivo
  ) AND COALESCE(current_setting('libra.aplicando_consignacion', TRUE), '') <> '1' THEN
    RAISE EXCEPTION 'El estado de la consignación sólo cambia mediante su flujo auditado.'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER consignaciones_proteger_trg
  BEFORE UPDATE OR DELETE ON consignaciones_editoriales
  FOR EACH ROW EXECUTE FUNCTION proteger_consignacion_editorial();

CREATE OR REPLACE FUNCTION proteger_consignacion_detalle()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP='DELETE' THEN
    RAISE EXCEPTION 'El detalle de consignación es inmutable.' USING ERRCODE = '55000';
  END IF;
  IF ROW(
    NEW.id, NEW.consignacion_editorial_id, NEW.producto_id,
    NEW.producto_sku, NEW.producto_titulo, NEW.producto_isbn,
    NEW.cantidad_enviada, NEW.precio_lista, NEW.descuento_unitario,
    NEW.precio_unitario, NEW.iva_porcentaje, NEW.regla_precio_id,
    NEW.subtotal_enviado, NEW.descuento_enviado, NEW.iva_enviado,
    NEW.importe_enviado, NEW.creado_en
  ) IS DISTINCT FROM ROW(
    OLD.id, OLD.consignacion_editorial_id, OLD.producto_id,
    OLD.producto_sku, OLD.producto_titulo, OLD.producto_isbn,
    OLD.cantidad_enviada, OLD.precio_lista, OLD.descuento_unitario,
    OLD.precio_unitario, OLD.iva_porcentaje, OLD.regla_precio_id,
    OLD.subtotal_enviado, OLD.descuento_enviado, OLD.iva_enviado,
    OLD.importe_enviado, OLD.creado_en
  ) THEN
    RAISE EXCEPTION 'El detalle comercial de consignación es inmutable.'
      USING ERRCODE = '55000';
  END IF;
  IF ROW(NEW.cantidad_vendida, NEW.cantidad_devuelta)
     IS DISTINCT FROM ROW(OLD.cantidad_vendida, OLD.cantidad_devuelta)
     AND COALESCE(current_setting('libra.aplicando_consignacion', TRUE), '') <> '1' THEN
    RAISE EXCEPTION 'Los saldos de consignación sólo cambian mediante operaciones auditadas.'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END
$function$;

CREATE TRIGGER consignacion_detalles_proteger_trg
  BEFORE UPDATE OR DELETE ON consignacion_detalles
  FOR EACH ROW EXECUTE FUNCTION proteger_consignacion_detalle();

CREATE OR REPLACE FUNCTION validar_consignacion_conciliada(p_consignacion_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $function$
DECLARE
  v_consignacion consignaciones_editoriales%ROWTYPE;
  v_ultimo_estado VARCHAR(12);
  v_envios INTEGER;
  v_actividad INTEGER;
  v_pendiente BIGINT;
BEGIN
  SELECT * INTO v_consignacion
  FROM consignaciones_editoriales WHERE id=p_consignacion_id;
  IF NOT FOUND THEN RETURN; END IF;

  SELECT estado_nuevo INTO v_ultimo_estado
  FROM consignacion_transiciones
  WHERE consignacion_editorial_id=p_consignacion_id
  ORDER BY id DESC LIMIT 1;
  IF v_ultimo_estado IS DISTINCT FROM v_consignacion.estado THEN
    RAISE EXCEPTION 'El historial de la consignación % no coincide con su estado.', p_consignacion_id
      USING ERRCODE = '23514';
  END IF;

  SELECT COUNT(*) FILTER (WHERE tipo='ENVIO')::int,
         COUNT(*) FILTER (WHERE tipo IN ('VENTA','DEVOLUCION'))::int
  INTO v_envios, v_actividad
  FROM consignacion_operaciones
  WHERE consignacion_editorial_id=p_consignacion_id;
  SELECT COALESCE(SUM(cantidad_enviada-cantidad_vendida-cantidad_devuelta),0)
  INTO v_pendiente
  FROM consignacion_detalles
  WHERE consignacion_editorial_id=p_consignacion_id;

  IF EXISTS (
    SELECT 1
    FROM consignacion_detalles d
    LEFT JOIN (
      SELECT od.consignacion_detalle_id,
             COALESCE(SUM(od.cantidad) FILTER (WHERE o.tipo='ENVIO'),0)::int AS enviada,
             COALESCE(SUM(od.cantidad) FILTER (WHERE o.tipo='VENTA'),0)::int AS vendida,
             COALESCE(SUM(od.cantidad) FILTER (WHERE o.tipo='DEVOLUCION'),0)::int AS devuelta
      FROM consignacion_operacion_detalles od
      JOIN consignacion_operaciones o ON o.id=od.consignacion_operacion_id
      WHERE o.consignacion_editorial_id=p_consignacion_id
      GROUP BY od.consignacion_detalle_id
    ) x ON x.consignacion_detalle_id=d.id
    WHERE d.consignacion_editorial_id=p_consignacion_id
      AND (
        COALESCE(x.enviada,0) <> CASE WHEN v_consignacion.estado IN ('BORRADOR','CANCELADA')
                                     THEN 0 ELSE d.cantidad_enviada END
        OR COALESCE(x.vendida,0) <> d.cantidad_vendida
        OR COALESCE(x.devuelta,0) <> d.cantidad_devuelta
      )
  ) THEN
    RAISE EXCEPTION 'Las cantidades de la consignación % no están conciliadas.', p_consignacion_id
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM consignacion_operaciones o
    LEFT JOIN (
      SELECT consignacion_operacion_id,
             ROUND(COALESCE(SUM(subtotal),0),2) AS subtotal,
             ROUND(COALESCE(SUM(descuento),0),2) AS descuento,
             ROUND(COALESCE(SUM(iva),0),2) AS iva,
             ROUND(COALESCE(SUM(importe),0),2) AS total
      FROM consignacion_operacion_detalles
      GROUP BY consignacion_operacion_id
    ) d ON d.consignacion_operacion_id=o.id
    WHERE o.consignacion_editorial_id=p_consignacion_id
      AND (o.subtotal<>COALESCE(d.subtotal,0) OR o.descuento<>COALESCE(d.descuento,0)
           OR o.iva<>COALESCE(d.iva,0) OR o.total<>COALESCE(d.total,0))
  ) THEN
    RAISE EXCEPTION 'Los importes de la consignación % no están conciliados.', p_consignacion_id
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM consignacion_operacion_detalles od
    JOIN consignacion_operaciones o ON o.id=od.consignacion_operacion_id
    LEFT JOIN inventario_movimientos m
      ON m.detalle_consignacion_operacion_id=od.id
    WHERE o.consignacion_editorial_id=p_consignacion_id
      AND (
        m.id IS NULL OR m.usuario_id<>o.usuario_id
        OR (o.tipo='ENVIO' AND (m.tipo<>'SALIDA_CONSIGNACION'
            OR m.delta_fisico<>-od.cantidad OR m.delta_reservado<>0
            OR m.delta_consignado<>od.cantidad))
        OR (o.tipo='VENTA' AND (m.tipo<>'VENTA_CONSIGNACION'
            OR m.delta_fisico<>0 OR m.delta_reservado<>0
            OR m.delta_consignado<>-od.cantidad))
        OR (o.tipo='DEVOLUCION' AND (m.tipo<>'DEVOLUCION_CONSIGNACION'
            OR m.delta_fisico<>od.cantidad OR m.delta_reservado<>0
            OR m.delta_consignado<>-od.cantidad))
      )
  ) THEN
    RAISE EXCEPTION 'El kardex de la consignación % no está conciliado.', p_consignacion_id
      USING ERRCODE = '23514';
  END IF;

  IF v_consignacion.estado IN ('BORRADOR','CANCELADA') THEN
    IF v_envios<>0 OR v_actividad<>0 OR EXISTS (
      SELECT 1 FROM consignacion_detalles
      WHERE consignacion_editorial_id=p_consignacion_id
        AND (cantidad_vendida<>0 OR cantidad_devuelta<>0)
    ) THEN
      RAISE EXCEPTION 'La consignación % sin enviar contiene operaciones.', p_consignacion_id
        USING ERRCODE = '23514';
    END IF;
  ELSIF v_consignacion.estado='ENVIADA' THEN
    IF v_envios<>1 OR v_actividad<>0 OR v_pendiente<=0 THEN
      RAISE EXCEPTION 'La consignación enviada % no coincide con sus saldos.', p_consignacion_id
        USING ERRCODE = '23514';
    END IF;
  ELSIF v_consignacion.estado='PARCIAL' THEN
    IF v_envios<>1 OR v_actividad<=0 OR v_pendiente<=0 THEN
      RAISE EXCEPTION 'La consignación parcial % no coincide con sus saldos.', p_consignacion_id
        USING ERRCODE = '23514';
    END IF;
  ELSIF v_consignacion.estado IN ('LIQUIDADA','CERRADA') THEN
    IF v_envios<>1 OR v_actividad<=0 OR v_pendiente<>0 THEN
      RAISE EXCEPTION 'La consignación liquidada % conserva unidades pendientes.', p_consignacion_id
        USING ERRCODE = '23514';
    END IF;
  END IF;
END
$function$;

CREATE OR REPLACE FUNCTION validar_consignacion_conciliada_trg()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  v_id BIGINT;
BEGIN
  IF TG_TABLE_NAME='consignaciones_editoriales' THEN
    v_id := CASE WHEN TG_OP='DELETE' THEN OLD.id ELSE NEW.id END;
  ELSIF TG_TABLE_NAME='consignacion_detalles' THEN
    v_id := CASE WHEN TG_OP='DELETE' THEN OLD.consignacion_editorial_id ELSE NEW.consignacion_editorial_id END;
  ELSIF TG_TABLE_NAME='consignacion_operaciones' THEN
    v_id := CASE WHEN TG_OP='DELETE' THEN OLD.consignacion_editorial_id ELSE NEW.consignacion_editorial_id END;
  ELSIF TG_TABLE_NAME='consignacion_operacion_detalles' THEN
    v_id := CASE WHEN TG_OP='DELETE' THEN OLD.consignacion_editorial_id ELSE NEW.consignacion_editorial_id END;
  ELSIF TG_TABLE_NAME='consignacion_transiciones' THEN
    v_id := CASE WHEN TG_OP='DELETE' THEN OLD.consignacion_editorial_id ELSE NEW.consignacion_editorial_id END;
  ELSE
    SELECT consignacion_editorial_id INTO v_id
    FROM consignacion_operaciones
    WHERE id=CASE WHEN TG_OP='DELETE' THEN OLD.consignacion_operacion_id
                  ELSE NEW.consignacion_operacion_id END;
  END IF;
  PERFORM validar_consignacion_conciliada(v_id);
  RETURN NULL;
END
$function$;

CREATE CONSTRAINT TRIGGER consignaciones_conciliacion_trg
  AFTER INSERT OR UPDATE ON consignaciones_editoriales DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_consignacion_conciliada_trg();
CREATE CONSTRAINT TRIGGER consignacion_detalles_conciliacion_trg
  AFTER INSERT OR UPDATE ON consignacion_detalles DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_consignacion_conciliada_trg();
CREATE CONSTRAINT TRIGGER consignacion_operaciones_conciliacion_trg
  AFTER INSERT ON consignacion_operaciones DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_consignacion_conciliada_trg();
CREATE CONSTRAINT TRIGGER consignacion_operacion_detalles_conciliacion_trg
  AFTER INSERT ON consignacion_operacion_detalles DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_consignacion_conciliada_trg();
CREATE CONSTRAINT TRIGGER consignacion_transiciones_conciliacion_trg
  AFTER INSERT ON consignacion_transiciones DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION validar_consignacion_conciliada_trg();
CREATE CONSTRAINT TRIGGER inventario_consignacion_conciliacion_trg
  AFTER INSERT ON inventario_movimientos DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW WHEN (NEW.consignacion_operacion_id IS NOT NULL)
  EXECUTE FUNCTION validar_consignacion_conciliada_trg();

-- Las liquidaciones de regalías pueden incorporar ventas de consignación sin
-- inventar una venta de caja. Se conservan referencias exclusivas por origen.
ALTER TABLE detalle_liquidaciones_regalias
  ALTER COLUMN movimiento_id DROP NOT NULL,
  ALTER COLUMN venta_id DROP NOT NULL,
  ALTER COLUMN detalle_venta_id DROP NOT NULL,
  ALTER COLUMN canal TYPE VARCHAR(12),
  ADD COLUMN consignacion_operacion_id BIGINT,
  ADD COLUMN detalle_consignacion_operacion_id BIGINT;
ALTER TABLE detalle_liquidaciones_regalias
  ADD CONSTRAINT detalle_liquidaciones_consignacion_detalle_fk
    FOREIGN KEY (
      detalle_consignacion_operacion_id, consignacion_operacion_id, producto_id
    ) REFERENCES consignacion_operacion_detalles(
      id, consignacion_operacion_id, producto_id
    ) ON DELETE RESTRICT;
ALTER TABLE detalle_liquidaciones_regalias
  DROP CONSTRAINT detalle_liquidaciones_origen_check,
  DROP CONSTRAINT detalle_liquidaciones_canal_check;
ALTER TABLE detalle_liquidaciones_regalias
  ADD CONSTRAINT detalle_liquidaciones_origen_check CHECK (
    (
      canal IN ('POS','WEB')
      AND movimiento_id IS NOT NULL AND venta_id IS NOT NULL
      AND detalle_venta_id IS NOT NULL
      AND consignacion_operacion_id IS NULL
      AND detalle_consignacion_operacion_id IS NULL
      AND (
        (tipo_evento IN ('VENTA','CANCELACION')
          AND devolucion_id IS NULL AND detalle_devolucion_id IS NULL)
        OR (tipo_evento='DEVOLUCION'
          AND devolucion_id IS NOT NULL AND detalle_devolucion_id IS NOT NULL)
      )
    )
    OR (
      canal='CONSIGNACION' AND tipo_evento='VENTA'
      AND movimiento_id IS NULL AND venta_id IS NULL AND detalle_venta_id IS NULL
      AND devolucion_id IS NULL AND detalle_devolucion_id IS NULL
      AND consignacion_operacion_id IS NOT NULL
      AND detalle_consignacion_operacion_id IS NOT NULL
    )
  );
ALTER TABLE detalle_liquidaciones_regalias
  ADD CONSTRAINT detalle_liquidaciones_canal_check CHECK (
    canal IN ('POS', 'WEB', 'CONSIGNACION')
  );

-- Fuente comercial común. Ventas y regalías consumen estas vistas; caja sigue
-- leyendo exclusivamente movimientos para no atribuir efectivo a consignación.
CREATE OR REPLACE VIEW eventos_comerciales AS
SELECT ('POS:'||m.id)::text AS evento_clave,
       m.tipo::text AS tipo_evento,
       'POS'::text AS fuente,
       m.creado_en AS fecha_evento,
       m.id AS movimiento_id,
       m.sesion_id,
       m.caja_id,
       m.usuario_id,
       m.metodo_pago,
       m.monto AS importe,
       CASE WHEN m.tipo='VENTA' THEN m.monto ELSE -m.monto END AS importe_neto,
       v.id AS venta_id,
       NULL::bigint AS consignacion_editorial_id,
       NULL::bigint AS consignacion_operacion_id,
       v.folio,
       v.cliente_id,
       v.cliente AS cliente_nombre,
       CASE WHEN ped.canal='WEB' THEN 'WEB' ELSE 'POS' END::text AS canal,
       CASE
         WHEN v.pedido_id IS NULL THEN 'VENTA_DIRECTA'
         WHEN ped.canal='WEB' THEN 'PEDIDO_WEB'
         ELSE 'PEDIDO_INTERNO'
       END::text AS origen,
       c.nombre AS caja_nombre,
       u.nombre AS usuario,
       m.referencia,
       m.concepto
FROM movimientos m
LEFT JOIN cancelaciones_venta cv ON cv.id=m.cancelacion_id
LEFT JOIN devoluciones dev ON dev.id=m.devolucion_id
JOIN ventas v ON v.id=COALESCE(m.venta_id, cv.venta_id, dev.venta_id)
LEFT JOIN pedidos ped ON ped.id=v.pedido_id
JOIN caja c ON c.id=m.caja_id
JOIN usuarios u ON u.id=m.usuario_id
WHERE m.tipo IN ('VENTA','CANCELACION','DEVOLUCION')

UNION ALL

SELECT ('CONSIGNACION:'||o.id)::text,
       'VENTA'::text,
       'CONSIGNACION'::text,
       o.creado_en,
       NULL::integer,
       NULL::integer,
       NULL::integer,
       o.usuario_id,
       NULL::varchar(20),
       o.total,
       o.total,
       NULL::integer,
       c.id,
       o.id,
       o.folio,
       c.cliente_id,
       c.cliente_nombre,
       'CONSIGNACION'::text,
       c.tipo_comercial::text,
       NULL::varchar(80),
       u.nombre,
       o.referencia,
       ('Venta consignada de '||c.folio)::text
FROM consignacion_operaciones o
JOIN consignaciones_editoriales c ON c.id=o.consignacion_editorial_id
JOIN usuarios u ON u.id=o.usuario_id
WHERE o.tipo='VENTA';

CREATE OR REPLACE VIEW lineas_comerciales AS
SELECT ('VENTA:'||m.id||':'||dv.id)::text AS evento_clave,
       'VENTA'::text AS tipo_evento,
       'POS'::text AS fuente,
       m.creado_en AS fecha_evento,
       m.id AS movimiento_id,
       m.sesion_id,
       m.caja_id,
       m.usuario_id,
       m.metodo_pago,
       v.id AS venta_id,
       dv.id AS detalle_venta_id,
       NULL::bigint AS devolucion_id,
       NULL::bigint AS detalle_devolucion_id,
       NULL::bigint AS consignacion_editorial_id,
       NULL::bigint AS consignacion_operacion_id,
       NULL::bigint AS detalle_consignacion_operacion_id,
       v.cliente_id,
       v.cliente AS cliente_nombre,
       CASE WHEN ped.canal='WEB' THEN 'WEB' ELSE 'POS' END::text AS canal,
       1::int AS signo,
       dv.producto_id,
       dv.producto_sku,
       dv.producto_titulo,
       dv.cantidad::int AS cantidad,
       dv.precio_lista,
       dv.descuento_unitario,
       dv.precio_unitario,
       dv.iva_porcentaje,
       dv.importe,
       ROUND(dv.descuento_unitario*dv.cantidad,2) AS descuento
FROM movimientos m
JOIN ventas v ON v.id=m.venta_id
JOIN detalle_ventas dv ON dv.venta_id=v.id
LEFT JOIN pedidos ped ON ped.id=v.pedido_id
WHERE m.tipo='VENTA'

UNION ALL

SELECT ('CANCELACION:'||m.id||':'||dv.id)::text,
       'CANCELACION'::text, 'POS'::text, m.creado_en,
       m.id, m.sesion_id, m.caja_id, m.usuario_id, m.metodo_pago,
       v.id, dv.id, NULL::bigint, NULL::bigint,
       NULL::bigint, NULL::bigint, NULL::bigint,
       v.cliente_id, v.cliente,
       CASE WHEN ped.canal='WEB' THEN 'WEB' ELSE 'POS' END::text,
       -1::int, dv.producto_id, dv.producto_sku, dv.producto_titulo,
       dv.cantidad::int, dv.precio_lista, dv.descuento_unitario,
       dv.precio_unitario, dv.iva_porcentaje, dv.importe,
       ROUND(dv.descuento_unitario*dv.cantidad,2)
FROM movimientos m
JOIN cancelaciones_venta cv ON cv.id=m.cancelacion_id
JOIN ventas v ON v.id=cv.venta_id
JOIN detalle_ventas dv ON dv.venta_id=v.id
LEFT JOIN pedidos ped ON ped.id=v.pedido_id
WHERE m.tipo='CANCELACION'

UNION ALL

SELECT ('DEVOLUCION:'||m.id||':'||dd.id)::text,
       'DEVOLUCION'::text, 'POS'::text, m.creado_en,
       m.id, m.sesion_id, m.caja_id, m.usuario_id, m.metodo_pago,
       v.id, dv.id, dev.id, dd.id,
       NULL::bigint, NULL::bigint, NULL::bigint,
       v.cliente_id, v.cliente,
       CASE WHEN ped.canal='WEB' THEN 'WEB' ELSE 'POS' END::text,
       -1::int, dv.producto_id, dv.producto_sku, dv.producto_titulo,
       dd.cantidad::int, dv.precio_lista, dv.descuento_unitario,
       dv.precio_unitario, dv.iva_porcentaje, dd.importe,
       ROUND(dv.descuento_unitario*dd.cantidad,2)
FROM movimientos m
JOIN devoluciones dev ON dev.id=m.devolucion_id
JOIN ventas v ON v.id=dev.venta_id
JOIN detalle_devoluciones dd ON dd.devolucion_id=dev.id
JOIN detalle_ventas dv ON dv.id=dd.detalle_venta_id
LEFT JOIN pedidos ped ON ped.id=v.pedido_id
WHERE m.tipo='DEVOLUCION'

UNION ALL

SELECT ('CONSIGNACION:'||o.id||':'||od.id)::text,
       'VENTA'::text, 'CONSIGNACION'::text, o.creado_en,
       NULL::integer, NULL::integer, NULL::integer, o.usuario_id,
       NULL::varchar(20), NULL::integer, NULL::integer,
       NULL::bigint, NULL::bigint,
       c.id, o.id, od.id,
       c.cliente_id, c.cliente_nombre, 'CONSIGNACION'::text,
       1::int, od.producto_id, d.producto_sku, d.producto_titulo,
       od.cantidad::int, od.precio_lista, od.descuento_unitario,
       od.precio_unitario, od.iva_porcentaje, od.importe, od.descuento
FROM consignacion_operaciones o
JOIN consignaciones_editoriales c ON c.id=o.consignacion_editorial_id
JOIN consignacion_operacion_detalles od ON od.consignacion_operacion_id=o.id
JOIN consignacion_detalles d ON d.id=od.consignacion_detalle_id
WHERE o.tipo='VENTA';

CREATE OR REPLACE VIEW inventario_conciliacion AS
WITH kardex AS (
  SELECT producto_id,
         COALESCE(SUM(delta_fisico), 0)::BIGINT AS fisico_kardex,
         COALESCE(SUM(delta_reservado), 0)::BIGINT AS reservado_kardex,
         COALESCE(SUM(delta_consignado), 0)::BIGINT AS consignado_kardex
  FROM inventario_movimientos GROUP BY producto_id
), reservas AS (
  SELECT producto_id, COALESCE(SUM(cantidad), 0)::BIGINT AS reservado_activo
  FROM reservas_stock WHERE estado='ACTIVA' GROUP BY producto_id
), consignado AS (
  SELECT d.producto_id,
         COALESCE(SUM(d.cantidad_enviada-d.cantidad_vendida-d.cantidad_devuelta),0)::BIGINT
           AS consignado_activo
  FROM consignacion_detalles d
  JOIN consignaciones_editoriales c ON c.id=d.consignacion_editorial_id
  WHERE c.estado IN ('ENVIADA','PARCIAL','LIQUIDADA','CERRADA')
  GROUP BY d.producto_id
)
SELECT p.id AS producto_id, p.sku, p.titulo,
       p.stock::BIGINT AS stock_fisico,
       COALESCE(k.fisico_kardex,0) AS stock_fisico_kardex,
       p.stock::BIGINT-COALESCE(k.fisico_kardex,0) AS diferencia_fisico_kardex,
       p.stock_reservado::BIGINT AS stock_reservado,
       COALESCE(r.reservado_activo,0) AS reservado_activo,
       COALESCE(k.reservado_kardex,0) AS stock_reservado_kardex,
       p.stock_reservado::BIGINT-COALESCE(r.reservado_activo,0) AS diferencia_reservas_activas,
       p.stock_reservado::BIGINT-COALESCE(k.reservado_kardex,0) AS diferencia_reservado_kardex,
       p.stock_consignado::BIGINT AS stock_consignado,
       COALESCE(c.consignado_activo,0) AS consignado_activo,
       COALESCE(k.consignado_kardex,0) AS stock_consignado_kardex,
       p.stock_consignado::BIGINT-COALESCE(c.consignado_activo,0) AS diferencia_consignaciones_activas,
       p.stock_consignado::BIGINT-COALESCE(k.consignado_kardex,0) AS diferencia_consignado_kardex,
       p.stock_disponible::BIGINT AS stock_disponible,
       (
         p.stock=COALESCE(k.fisico_kardex,0)
         AND p.stock_reservado=COALESCE(r.reservado_activo,0)
         AND p.stock_reservado=COALESCE(k.reservado_kardex,0)
         AND p.stock_consignado=COALESCE(c.consignado_activo,0)
         AND p.stock_consignado=COALESCE(k.consignado_kardex,0)
       ) AS conciliado
FROM productos p
LEFT JOIN kardex k ON k.producto_id=p.id
LEFT JOIN reservas r ON r.producto_id=p.id
LEFT JOIN consignado c ON c.producto_id=p.id;
