BEGIN;

CREATE TABLE IF NOT EXISTS roles (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE,
  CONSTRAINT roles_nombre_check CHECK (nombre IN ('ADMIN', 'SUPERVISOR', 'CAJERO'))
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  email VARCHAR(120) NOT NULL,
  password_hash VARCHAR(60) NOT NULL,
  rol_id SMALLINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_email_lower_uq
  ON usuarios (lower(email));

CREATE TABLE IF NOT EXISTS categorias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS productos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku VARCHAR(24) NOT NULL UNIQUE,
  codigo_barras VARCHAR(30),
  isbn VARCHAR(17),
  titulo VARCHAR(160) NOT NULL,
  autor VARCHAR(120),
  editorial VARCHAR(120),
  categoria_id INTEGER REFERENCES categorias(id) ON DELETE SET NULL,
  precio NUMERIC(12,2) NOT NULL,
  costo NUMERIC(12,2) NOT NULL DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0,
  iva NUMERIC(5,2) NOT NULL DEFAULT 16,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT productos_precio_check CHECK (precio >= 0),
  CONSTRAINT productos_costo_check CHECK (costo >= 0),
  CONSTRAINT productos_stock_check CHECK (stock >= 0),
  CONSTRAINT productos_iva_check CHECK (iva >= 0 AND iva <= 100)
);

CREATE UNIQUE INDEX IF NOT EXISTS productos_codigo_barras_uq
  ON productos (codigo_barras) WHERE codigo_barras IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS productos_isbn_uq
  ON productos (isbn) WHERE isbn IS NOT NULL;
CREATE INDEX IF NOT EXISTS productos_categoria_idx ON productos (categoria_id);
CREATE INDEX IF NOT EXISTS productos_busqueda_fts_idx
  ON productos USING GIN (
    to_tsvector('spanish', titulo || ' ' || COALESCE(autor, ''))
  );

CREATE TABLE IF NOT EXISTS caja (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS sesiones_caja (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caja_id INTEGER NOT NULL REFERENCES caja(id) ON DELETE RESTRICT,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  fondo_inicial NUMERIC(12,2) NOT NULL,
  estado VARCHAR(10) NOT NULL DEFAULT 'ABIERTA',
  fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_cierre TIMESTAMPTZ,
  CONSTRAINT sesiones_fondo_check CHECK (fondo_inicial >= 0),
  CONSTRAINT sesiones_estado_check CHECK (estado IN ('ABIERTA', 'CERRADA'))
);

CREATE UNIQUE INDEX IF NOT EXISTS sesiones_caja_abierta_uq
  ON sesiones_caja (caja_id) WHERE estado = 'ABIERTA';
CREATE INDEX IF NOT EXISTS sesiones_caja_estado_idx ON sesiones_caja (estado);

CREATE SEQUENCE IF NOT EXISTS ventas_folio_seq START WITH 1;

CREATE TABLE IF NOT EXISTS ventas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio VARCHAR(20) NOT NULL UNIQUE
    DEFAULT ('V-' || LPAD(nextval('ventas_folio_seq')::text, 8, '0')),
  sesion_id INTEGER NOT NULL REFERENCES sesiones_caja(id) ON DELETE RESTRICT,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  cliente VARCHAR(120) NOT NULL DEFAULT 'PÚBLICO GENERAL',
  metodo_pago VARCHAR(20) NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL,
  iva NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  recibido NUMERIC(12,2),
  cambio NUMERIC(12,2),
  estado VARCHAR(15) NOT NULL DEFAULT 'COMPLETADA',
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ventas_metodo_check CHECK (metodo_pago IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA')),
  CONSTRAINT ventas_estado_check CHECK (estado = 'COMPLETADA'),
  CONSTRAINT ventas_subtotal_check CHECK (subtotal >= 0),
  CONSTRAINT ventas_iva_check CHECK (iva >= 0),
  CONSTRAINT ventas_total_check CHECK (total >= 0),
  CONSTRAINT ventas_recibido_check CHECK (recibido IS NULL OR recibido >= 0),
  CONSTRAINT ventas_cambio_check CHECK (cambio IS NULL OR cambio >= 0)
);

CREATE INDEX IF NOT EXISTS ventas_sesion_idx ON ventas (sesion_id);
CREATE INDEX IF NOT EXISTS ventas_usuario_idx ON ventas (usuario_id);
CREATE INDEX IF NOT EXISTS ventas_creado_en_idx ON ventas (creado_en DESC);

CREATE TABLE IF NOT EXISTS detalle_ventas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id INTEGER NOT NULL REFERENCES ventas(id) ON DELETE RESTRICT,
  producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL,
  precio_unitario NUMERIC(12,2) NOT NULL,
  importe NUMERIC(12,2) NOT NULL,
  CONSTRAINT detalle_cantidad_check CHECK (cantidad > 0),
  CONSTRAINT detalle_precio_check CHECK (precio_unitario >= 0),
  CONSTRAINT detalle_importe_check CHECK (importe >= 0)
);

CREATE INDEX IF NOT EXISTS detalle_ventas_venta_idx ON detalle_ventas (venta_id);
CREATE INDEX IF NOT EXISTS detalle_ventas_producto_idx ON detalle_ventas (producto_id);

CREATE TABLE IF NOT EXISTS movimientos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sesion_id INTEGER NOT NULL REFERENCES sesiones_caja(id) ON DELETE RESTRICT,
  tipo VARCHAR(12) NOT NULL,
  referencia VARCHAR(40),
  concepto VARCHAR(160),
  monto NUMERIC(12,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT movimientos_tipo_check CHECK (tipo IN ('APERTURA', 'VENTA', 'RETIRO', 'INGRESO', 'CIERRE'))
);

CREATE INDEX IF NOT EXISTS movimientos_sesion_idx ON movimientos (sesion_id);

CREATE TABLE IF NOT EXISTS cortes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sesion_id INTEGER NOT NULL UNIQUE REFERENCES sesiones_caja(id) ON DELETE RESTRICT,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  n_ventas INTEGER NOT NULL,
  ventas_efectivo NUMERIC(12,2) NOT NULL,
  ventas_tarjeta NUMERIC(12,2) NOT NULL,
  ventas_transf NUMERIC(12,2) NOT NULL,
  ingresos NUMERIC(12,2) NOT NULL,
  retiros NUMERIC(12,2) NOT NULL,
  efectivo_esperado NUMERIC(12,2) NOT NULL,
  efectivo_contado NUMERIC(12,2) NOT NULL,
  diferencia NUMERIC(12,2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT cortes_n_ventas_check CHECK (n_ventas >= 0),
  CONSTRAINT cortes_ventas_efectivo_check CHECK (ventas_efectivo >= 0),
  CONSTRAINT cortes_ventas_tarjeta_check CHECK (ventas_tarjeta >= 0),
  CONSTRAINT cortes_ventas_transf_check CHECK (ventas_transf >= 0),
  CONSTRAINT cortes_ingresos_check CHECK (ingresos >= 0),
  CONSTRAINT cortes_retiros_check CHECK (retiros >= 0),
  CONSTRAINT cortes_efectivo_contado_check CHECK (efectivo_contado >= 0)
);

CREATE INDEX IF NOT EXISTS cortes_usuario_idx ON cortes (usuario_id);

COMMIT;
